#!/usr/bin/env python3
"""Build Chapter 59 (CATELYN) close-reading Markdown."""
from pathlib import Path

from agot_extract import extract_range
from agot_reader_common import write_chapter
from build_agot_chapter58_reader import VOCAB as BASE_VOCAB

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs" / "AGOT_逐章精读"

SUMMARIES = [
    "军队离开Neck进入riverlands，Catelyn的忧惧随路程加深，却用冷峻面孔遮住。",
    "她担心Hoster、Edmure、Ned、女儿和留在Winterfell的儿子，却强迫自己只保留帮助Robb的力量。",
    "Robb轮流听取每位lord意见，模仿Ned的统帅方式；Catelyn既欣慰又担心他学得不够。",
    "Blackfish率精选骑兵侦察掩护，报告Walder Frey已在Green Fork的Twins集结近四千人。",
    "Catelyn想起Trident时Walder迟到的旧事，恼怒他未按封臣义务南援Riverrun。",
    "Robb不解Walder为何独自集兵，推测他会与North军合流。",
    "Catelyn提醒Robb不要对Walder抱期待，以免被其反复立场打个措手不及。",
    "Robb指出Walder是Hoster的bannerman。",
    "Catelyn解释誓言约束力因人而异，Walder又与Casterly Rock有婚姻联系，但这尚不能单独证明背叛。",
    "Robett Glover询问Walder是否准备把他们交给Lannisters。",
    "Catelyn认为Walder自己可能也未决定；年老谨慎、年轻般野心与一贯狡猾同时驱动他。",
    "Robb强调必须取得Twins，因为附近没有其他过河道路。",
    "Catelyn指出Walder也完全清楚这一战略依赖。",
    "Theon转述Blackfish的侦察：已杀死Lannister scouts，Ser Addam南撤焚烧，并知道North军大致位置但不知何时分兵。",
    "Catelyn担心Walder用raven泄密，命弓手击落任何离堡信鸟。",
    "Theon说Blackfish早已布置，还用blackbird pie和feather hat开玩笑。",
    "Catelyn承认叔父先想到这一步，追问Freys面对掠夺做了什么。",
    "Theon说双方有小规模冲突，但Walder主力仍留在Twins。",
    "Catelyn把这种做法认作Walder的典型策略：等待、观察、非被迫不冒险。",
    "Robb把冲突视为Walder仍守誓的迹象。",
    "Catelyn区分保卫自家土地与公开迎战Tywin，认为证据还不够。",
    "Robb询问Blackfish是否找到其他渡过Green Fork的方法。",
    "Theon说水位高、流速快，这一带无法涉水。",
    "Robb焦躁地盘算游马与木筏方案，却受盔甲、木材和时间限制。",
    "Theon凭五倍兵力主张必要时攻下Twins。",
    "Catelyn指出攻城既不容易也来不及，Tywin会从背后夹击。",
    "Robb在无解时显出十五岁少年的稚嫩，问Ned会怎么做。",
    "Catelyn回答Ned会不惜代价找到过河办法。",
    "次日Blackfish亲自回报，换上更适合侦骑的轻甲，仍佩obsidian fish。",
    "他从俘虏处得知Riverrun城下战败，Jaime击溃Edmure军。",
    "Catelyn立即追问Edmure命运。",
    "Blackfish说Edmure负伤被俘，Lord Blackwood等残军被围在Riverrun。",
    "Robb因此更急于渡河救援。",
    "Blackfish警告Walder已把全部兵力撤入闭锁的Twins。",
    "Robb愤怒威胁若Walder不让路就摧毁城堡。",
    "Catelyn严厉说这是孩子面对障碍的冲动，lord必须懂得words有时胜过swords。",
    "Robb忍住羞恼，谦逊请母亲解释。",
    "Catelyn说Freys守桥六百年，也收了六百年通行代价。",
    "Robb问Walder想要什么toll。",
    "Catelyn说谈判的任务正是找出价格。",
    "Robb问若拒绝支付会怎样。",
    "Catelyn列出退回Moat Cailin、迎战Tywin或长出翅膀三种选择，并思考Ned是否教Robb在必要时低头。",
    "中午前锋看见作为Lords of the Crossing领地的Twins。",
    "Green Fork上的石桥、Water Tower、arrow slits、murder holes和portcullises把交通控制变成财富与武力。",
    "两座外形相同的石堡从两岸锁住桥头，多重门堡让任何人都无法未经许可通过。",
    "满墙武器、弓手和关闭的防御设施使Catelyn一眼判定强攻不可行。",
    "Greatjon咒骂、Karstark沉默，Roose Bolton冷静断言无法攻取。",
    "Tallhart指出若无西岸军队包围另一堡也无法围城，况且他们没有时间。",
    "sally port开启，Stevron率Walder诸子出迎，礼貌询问谁统率大军。",
    "Robb披甲、带Grey Wind上前表明自己是统帅。",
    "Stevron虽略觉好笑，坐骑却怕direwolf；他邀请Robb进堡饮食并说明来意。",
    "这项邀请像catapult石弹般砸进众lords，引发一致反对。",
    "Galbart Glover恳求Robb不要相信Walder。",
    "Roose说明Robb独自入堡就会任人囚禁、出卖或杀死。",
    "Wendel主张Walder若真想谈，就开门招待全体。",
    "Wylis建议Walder到两军眼前会谈。",
    "Catelyn同样怀疑，但看出再争下去会失去谈判机会，于是主动提出入堡。",
    "Greatjon惊讶确认是否由她前往。",
    "Robb也明显不放心母亲。",
    "Catelyn谎称自己从未如此确定，并以旧识与封臣关系安抚众人，心里却承认Walder会为利益伤害她。",
    "Stevron接受，由Perwyn留下作保证Catelyn安全回返的人质。",
    "Robb称Perwyn为honored guest，要求母亲在evenfall前回来。",
    "Catelyn随Frey使团进堡，不回头看身后。",
    "大厅里庞大的儿孙、私生子与后代，让Hoster关于Walder能从breeches里生出军队的讽语具象化。",
    "九十岁的Walder体弱多病，由第八任、年仅十六岁的妻子陪在litter旁。",
    "Catelyn用礼貌话语问候多年未见的Walder。",
    "Walder拒绝客套，怀疑Robb因骄傲才派母亲来，并直接追问目的。",
    "Catelyn回想他本就易怒刻薄，年老后更甚，提醒自己谨慎措辞且不受冒犯牵动。",
    "Stevron责备父亲忘了礼数，指出Catelyn是受邀客人。",
    "Walder强调Stevron在自己死前还不是lord，拒绝儿子教训。",
    "另一名儿子也说他不该这样对贵客说话。",
    "Walder以粗俗羞辱压制Ryger，并命Danwell、Whalen扶他到座位。",
    "众人把Walder移到雕有Twins的高座；他完成最低限度礼节后再问Catelyn来意。",
    "Catelyn正式请求开门，让Robb军过河。",
    "Walder讥笑自己仍能读地图，早知他们要去Riverrun。",
    "Catelyn确认目的，并反问为何作为Hoster封臣的Walder不在Riverrun。",
    "Walder声称原打算集齐兵力后派儿子出发，并让Jared为其说法作证。",
    "Jared以honor确认父亲所言。",
    "Walder把未参战归因于Edmure败得太快，又以惨败为不该赶去送死的理由。",
    "Catelyn压下杀意，以evenfall期限为重，冷静要求私下谈判。",
    "Walder赶走全家，拿他们等自己死来取笑，并宣称不肯为了让Stevron继位而死。",
    "Catelyn顺着他的虚荣祝他活到一百岁。",
    "Walder觉得那会气坏继承人，催她说明请求。",
    "Catelyn直说需要过桥。",
    "Walder赞她直截了当，却问自己凭什么允许。",
    "Catelyn一时发怒，以城外两万军队施压。",
    "Walder逐项列出Ned被囚、Hoster病重、Edmure被俘，断言这两万人很快会成Tywin刀下尸体。",
    "Catelyn提醒他曾向Hoster宣誓。",
    "Walder说自己也向crown宣誓，而Joffrey已是king，因此Starks和Tullys也可被定义为rebels。",
    "Catelyn反问他为何不直接帮助Lannisters。",
    "Walder嘲弄Tywin的傲慢与显赫，表明自己也不愿无条件投向Lannister，若Tywin要帮助也必须亲自来求。",
    "Catelyn确认他愿意交易，谦卑地代表父亲、兄弟、丈夫和儿子请求援助。",
    "[内容省略：涉及未成年角色的性化描述。段落位置与谈判功能保留。] Walder拒绝甜言蜜语，并借年轻妻子与继承问题刺激全家。",
    "Catelyn以一句恭维顺应他的自夸，避免偏离谈判。",
    "Walder罗列Hoster缺席婚礼、给他Late Lord Frey外号、拒绝Edmure婚配等旧怨，把政治帮助定价为长期受辱的补偿。",
    "他又抱怨Lysa：先讲儿子们在tourney丢脸，再用粗俗家族闲话扩展自己的怨恨清单。",
    "Walder说曾提议与Arryn家互换wards；Jon Arryn原计划把Robert送到Dragonstone由Stannis foster，Lysa对此愤怒离场。",
    "Catelyn不安，因为她此前听说Robert Arryn要送往Casterly Rock由Tywin foster。",
    "Walder坚持自己说的是Stannis而非Tywin，并以粗俗自夸维护记忆可靠性；原PDF跨页断句已合并。",
    "Catelyn忽略旁枝，再次确认Jon Arryn是否确要把儿子交给Stannis。",
    "Walder连声确认，却以Jon已死为由轻描淡写，转回过桥问题。",
    "Catelyn再次确认North军确实要渡河。",
    "Walder强调桥由自己控制，Starks与Tullys从未善待他，等待Catelyn报价。",
    "叙述用一句话压缩后续反复讨价还价。",
    "日落前城门打开，Catelyn带着Frey诸子和长列pikemen返回North军。",
    "她宣布Walder准许过桥并提供除四百守军外的兵力，同时建议Robb留四百可信部下监督Twins守信。",
    "Robb接受建议，提出由Helman Tallhart指挥驻军。",
    "Catelyn认可这个选择。",
    "Robb谨慎追问Walder索取的代价。",
    "Catelyn先说要把两名都叫Walder的幼孙带到Winterfell作wards，与Bran作伴。",
    "Robb以为只有两个fosterlings，觉得价格很小。",
    "Catelyn继续说明Olyvar将随军作Robb的squire，并期待日后受封knight。",
    "Robb仍认为条件可以接受。",
    "Catelyn说若Arya平安归来，她成年后须嫁给Walder幼子Elmar。",
    "Robb认为Arya一定会非常反感。",
    "最后一项是Robb战后从Walder诸女中选一人结婚。",
    "Robb没有退缩，只简短表示明白。",
    "Catelyn正式询问他是否同意。",
    "Robb反问自己是否能拒绝。",
    "Catelyn坦白若要过桥就不能拒绝。",
    "Robb郑重同意；Catelyn认为承担婚约政治后果才是lord的成熟，而非玩剑。",
    "evenfall时军队在horned moon下如steel snake般穿过东堡、Water Tower与西堡。",
    "Catelyn与Robb等率十分之九骑兵先过；漫长行列在Walder与murder holes中的眼睛注视下通过。",
    "大部分步兵留在东岸，由Roose Bolton继续南下迎战Tywin主力。",
    "Catelyn以掷骰比喻Robb分兵：决定已经落下，结果无论好坏都无法撤回。",
]

KEY_NOTES = {
    1: "apprehensions不是单一恐惧，而是沿march累积的预感；still and stern face显示她把情绪管理当作统帅责任。",
    2: "You must be a Stark是自我命令，不表示她放弃Tully身份，而是借North的hardness承担Robb当前所需角色。",
    3: "轮换confer能防止偏宠并收集不同判断；结尾问题保留母亲看到的年龄风险。",
    7: "expect nothing是一条针对不可靠盟友的风险管理原则，也预设Walder会利用别人对oath的想当然。",
    11: "old caution／young ambition是悖论式人物概括：年龄让他避险，未满足的地位欲又让他索价。",
    15: "射raven是communications security：阻止Tywin知道分兵时间，而非一般猎鸟行为。",
    19: "hold back、wait、watch三连动词把Walder的被动塑造成主动策略。",
    24: "盔甲不能随horse游渡、木筏缺trees/time，具体物流约束解释为何兵力优势无法消除桥梁瓶颈。",
    27: "armor、sword、stubble构成成人外观，younger than fifteen揭开其经验不足。",
    36: "words/swords对照重定义领主能力：统帅不只会摧毁障碍，也要识别可以交易的利益。",
    42: "how to kneel不是永久屈服，而是为了更大目标暂时接受代价；graveyards让勇敢与智慧分离。",
    44: "桥、塔和税收合为同一制度：地理瓶颈经数代工程转化为Frey权力。",
    45: "两个完全相同的堡垒互相支撑，Twins之名既是外观也是防御逻辑。",
    48: "必须同时invest两岸说明单边围城无效；fortification结构直接决定政治谈判。",
    52: "catapult比喻把一句邀请写成攻击，说明诸lords把礼仪空间视作hostage trap。",
    57: "Catelyn不是确信安全才行动，而是看见negotiation window即将关闭。",
    60: "Never more是必要谎言；内心补句让读者同时看到她公开建立信心和私下精确评估风险。",
    61: "Perwyn留下形成reciprocal hostage，礼貌称vouchsafe/honored guest不能消除其担保功能。",
    64: "庞大家族是Walder的政治资本：子女既是兵力、婚姻接口，也是内部继承竞争。",
    67: "Walder主动破坏常规courtesy，以控制谈判节奏并迫使Catelyn在受辱时仍请求。",
    72: "公开羞辱儿子展示其家内权力；粗俗也被用来表演不受贵族礼法约束。",
    73: "高座雕成两塔一桥，把Walder身体、家族身份与crossing所有权合为一体。",
    79: "Walder把delay重新叙述成对Edmure失败的合理反应，避开自己是否故意观望。",
    80: "内心暴力想象与calmly形成反差：Catelyn的谈判能力首先是控制自己。",
    81: "他既猜疑继承人又以长寿折磨他们；家庭规模没有带来信任，反而放大succession anxiety。",
    87: "Walder不被两万人吓住，因为他用战略处境而非眼前人数估值Catelyn的bargaining power。",
    89: "互相冲突的oaths为他提供选择性解释空间；他暂不表态哪一种忠诚优先。",
    91: "对Tywin的身体化嘲弄削平等级距离，也揭示Walder真正不满的是未获尊重与主动求援。",
    93: "本段只保留谈判功能：Walder拒绝soft persuasion，并把生育、继承和家庭嫉妒当作权力展示。",
    95: "他的grievance archive并非闲话；每项被忽视都转化为今天的政治价格。",
    97: "关键事实是Jon Arryn计划把Robert交给Stannis foster；此处只记录它与Lysa先前说法不同，不解答原因。",
    98: "Catelyn的frown标出信息矛盾已进入她的推理，但disquieted不等于她已得出结论。",
    99: "反复确认记忆是Walder维护可信度的方式；粗俗旁逸同时拖慢Catelyn追索关键线索。",
    104: "Walder把控制bridge转化为negotiation leverage；smirk说明他等待的不是道德论证而是价格。",
    105: "only haggling故意省略谈判过程，只在结果中揭示代价，让读者与Robb一起逐项得知。",
    107: "augment garrison是礼貌包装；真正目的在用四百Northmen提供enforcement，防止Walder改约。",
    111: "wards兼具抚养、联盟纽带与hostage保证；companionship是柔和表述而非全部政治含义。",
    115: "Arya不在场也被纳入dynastic bargain；条件附带safe return与成年后履行，但她当下没有选择权。",
    117: "Robb的marriage将Frey从临时通行提供者变成预期姻亲，这才是Walder要求的身份升级。",
    122: "manly不指武力或年龄外观，而指清楚个人代价仍为军队承担不可回避的lordly obligation。",
    123: "steel snake让军队既强大又狭长脆弱；通过堡内通道时兵力必须服从Frey建筑控制。",
    124: "murder-hole eyes与Walder旁观保留不安：协议成立不等于信任建立。",
    126: "占位，不会使用。",
    125: "thrown the dice把分兵写成不可逆概率决策；Catelyn承认没有确定结果，只有已承担的风险。",
}

STAGES = [
    (1, 28, "North军抵达Green Fork前确认Twins是唯一及时通路；Walder的四千兵和不确定忠诚使桥成为战略瓶颈。"),
    (29, 42, "Riverrun败讯提高时间压力；Catelyn纠正Robb的强攻冲动，把谈判和必要的低头纳入lordship。"),
    (43, 63, "Twins的双岸工事证明攻围皆不可行；Catelyn抓住即将关闭的会谈机会，以Perwyn作担保独自入堡。"),
    (64, 105, "Walder用粗俗、家族规模与多年怨气控制谈判；Catelyn从其反Tywin情绪与身份渴望中找到交易空间。"),
    (106, 125, "协议以兵力、wards、squire与两项婚约换通行；Robb接受私人代价并将骑步兵分开执行战略。"),
]

BACKGROUNDS = {
    4: "**Lord of the Crossing：** Walder Frey以Twins控制Green Fork主要桥梁，近四千兵既能阻路也能成为重要增援。",
    5: "**Late Lord Frey：** Trident之战时Walder迟至胜负已定才到场，因此Hoster给他这个带讥讽的称呼。",
    9: "**Frey–Lannister婚姻：** Walder某子娶Tywin的sister；庞大家族让这种联姻重要却不足以单独决定阵营。",
    14: "**North军计划：** Blackfish负责屏蔽侦察，关键秘密是军队将何时、如何分兵。",
    30: "**Riverrun局势：** Edmure field army已败；Jaime围住Riverrun，救援时间窗口进一步缩短。",
    38: "**crossing toll：** 既可指传统过桥费，也指Walder将索取的政治条件。",
    44: "**Water Tower：** 位于桥中央的防御塔，从桥面上方与两端共同控制通行。",
    45: "**Twins：** Green Fork两岸的成对堡垒，由桥相连；必须控制两座才能真正控制crossing。",
    49: "**House Frey arms：** 淡银灰底上的深蓝双塔，直接描绘其城堡与权力来源。",
    61: "**hostage etiquette：** Perwyn被称为honored guest，但实际保证Catelyn若被扣，Freys也将失去一名家族成员。",
    64: "**Frey family：** Walder多次婚姻且后代众多，使marriage、wardship与继承成为其主要政治工具。",
    65: "**本地安全说明：** 原文仅陈述Walder第八任妻子的年龄和身份；后文若出现性化细节将以占位符处理。",
    89: "**conflicting fealty：** Walder既是Hoster封臣，也宣誓效忠crown；Joffrey继位争议让他能选择对自己有利的义务解释。",
    93: "**内容安全：** 原文中的未成年性化描写不复录；段落位置、Walder拒绝恭维及继承权炫耀均保留。",
    97: "**fostering discrepancy：** Lysa曾声称Robert将交给Tywin；Walder说Jon Arryn安排的是Stannis。矛盾本身是当前可知线索。",
    111: "**ward/fosterling：** 贵族孩子在另一家成长，可建立友谊和教育关系，也常作为联盟履约保证。",
    113: "**squire：** 侍奉knight或lord、学习武艺礼法的贵族少年；Olyvar随Robb也加强Frey对联盟的持续接触。",
    115: "**dynastic betrothal：** 未成年贵族的未来婚约常由家族谈判；本段呈现其政治效力，也明确Arya本人未参与。",
    125: "**split force：** 十分之九骑兵过西岸，大部步兵在Roose指挥下沿东岸南进，分别面向不同战场任务。",
}

EXTRA_VOCAB = [
    ("apprehension", "/ˌæprɪˈhenʃən/", "n.", "忧惧；不祥预感", "Catelyn's fears"),
    ("vanguard", "/ˈvænɡɑːrd/", "n.", "前锋部队", "front of the host"),
    ("screen", "/skriːn/", "v.", "掩护、遮蔽军队行动", "screen movements"),
    ("outrider", "/ˈaʊtraɪdər/", "n.", "外围侦骑", "scouting cavalry"),
    ("holdfast", "/ˈhoʊldfæst/", "n.", "小型堡寨；领主据点", "lands being plundered"),
    ("ford", "/fɔːrd/", "v.", "涉水过河", "river cannot be forded"),
    ("pole", "/poʊl/", "v.", "用长篙撑船", "pole rafts"),
    ("accursed", "/əˈkɜːrsɪd/", "adj.", "该受诅咒的", "river"),
    ("relent", "/rɪˈlent/", "v.", "变缓和；让步", "let army cross"),
    ("exact", "/ɪɡˈzækt/", "v.", "强行索取", "exact a toll"),
    ("deploy", "/dɪˈplɔɪ/", "v.", "部署军队", "meet Tywin"),
    ("usurp", "/juːˈzɜːrp/", "v.", "篡夺；越权取代", "Robb's place"),
    ("span", "/spæn/", "v.", "横跨", "bridge across river"),
    ("murder hole", "/ˈmɜːrdər hoʊl/", "n.", "堡门顶部攻击孔", "fortification"),
    ("portcullis", "/pɔːrtˈkʌlɪs/", "n.", "城堡吊闸", "gate defense"),
    ("barbican", "/ˈbɑːrbɪkən/", "n.", "瓮城；外门防御工事", "bridge approach"),
    ("scorpion", "/ˈskɔːrpiən/", "n.", "弩炮", "battlement weapon"),
    ("crenel", "/krəˈnel/", "n.", "城垛射口", "archer position"),
    ("invest", "/ɪnˈvest/", "v.", "包围（城堡）", "siege usage"),
    ("sally port", "/ˈsæli pɔːrt/", "n.", "守军出击用小门", "castle gate"),
    ("gelding", "/ˈɡeldɪŋ/", "n.", "阉马", "Stevron's mount"),
    ("sidle", "/ˈsaɪdəl/", "v.", "侧身挪动", "horse avoids wolf"),
    ("glibly", "/ˈɡlɪbli/", "adv.", "流利却未必真诚地", "necessary lie"),
    ("vouchsafe", "/ˌvaʊtʃˈseɪf/", "v.", "担保；郑重给予", "good intentions"),
    ("evenfall", "/ˈiːvənfɔːl/", "n.", "黄昏", "return deadline"),
    ("wizened", "/ˈwɪzənd/", "adj.", "干瘪衰老的", "Walder"),
    ("gouty", "/ˈɡaʊti/", "adj.", "患痛风的", "unable to stand"),
    ("irascible", "/ɪˈræsəbəl/", "adj.", "易怒的", "temper"),
    ("snigger", "/ˈsnɪɡər/", "v.", "窃笑；讥笑", "Walder"),
    ("querulous", "/ˈkwerələs/", "adj.", "爱抱怨的；尖刻不满的", "old man"),
    ("fidelity", "/fɪˈdeləti/", "n.", "忠诚；贞守", "double entendre"),
    ("haggling", "/ˈhæɡəlɪŋ/", "n.", "讨价还价", "negotiation"),
    ("augment", "/ɔːɡˈment/", "v.", "增强；补充", "garrison"),
    ("garrison", "/ˈɡærɪsən/", "n.", "守军", "hold the Twins"),
    ("ward", "/wɔːrd/", "n.", "受另一贵族监护的孩子", "alliance guarantee"),
    ("fosterling", "/ˈfɔːstərlɪŋ/", "n.", "寄养在另一家族的孩子", "noble custom"),
    ("nonplussed", "/ˌnɑːnˈplʌst/", "adj.", "困惑、不知如何反应的", "Robb"),
    ("marriage pact", "/ˈmærɪdʒ pækt/", "n.", "政治婚约", "dynastic alliance"),
    ("slat", "/slæt/", "n.", "狭长板条；此处指孔隙格条", "murder holes"),
    ("rank", "/ræŋk/", "n.", "队列；横排", "rank on rank"),
    ("shuffling", "/ˈʃʌfəlɪŋ/", "adj.", "拖步行进的", "pikemen"),
]
VOCAB = BASE_VOCAB + EXTRA_VOCAB


def extract_blocks():
    blocks = extract_range(580, 592, "CATELYN", "CH59")
    # PDF pp.589–590 split one spoken paragraph after “Lord”.
    blocks[98]["text"] = blocks[98]["text"] + " " + blocks[99]["text"]
    blocks[98]["end_page"] = blocks[99]["end_page"]
    del blocks[99]
    # Do not reproduce sexualized description involving a minor.
    blocks[92]["text"] = "[Content omitted: sexualized description involving a minor. Paragraph position preserved.]"
    for order, block in enumerate(blocks, 1):
        block["order"] = order
        block["id"] = f"CH59-P{block['page']:03d}-{order:03d}"
    return blocks


def main():
    blocks = extract_blocks()
    write_chapter(
        out=OUT, chapter=59, pov="CATELYN", page_start=580, page_end=592,
        blocks=blocks, summaries=SUMMARIES, key_notes=KEY_NOTES, stages=STAGES,
        backgrounds=BACKGROUNDS,
        default_background="本段没有新增必须补充的设定；重点在Twins的战略瓶颈、Walder的谈判姿态与Catelyn对Robb政治成长的观察。",
        vocab=VOCAB,
        guide="North军从Neck进入riverlands，却被Green Fork与Walder Frey控制的Twins挡住。Blackfish确认Riverrun战败、Edmure被俘后，时间压力骤增；强攻会拖到Tywin从后方抵达，谈判成为唯一现实选择。Catelyn先教Robb领主不仅要勇敢，也要懂得何时用words、何时kneel，随后在诸lords反对Robb入堡时亲自充当使者。Walder以粗俗、家族规模和多年受轻视的怨气掌控会谈，但他对Tywin同样不满，说明忠诚仍可交易。Catelyn换得过桥权、Frey兵力与暂时合作，代价包括wards、Olyvar作squire、Arya未来婚约和Robb的婚姻承诺。章末骑兵过西岸、大部步兵由Roose沿东岸南进，Robb把战略与个人未来一起押进一次不可逆的掷骰。",
        people=[
            ("Catelyn Stark", "本章视角；压住家庭忧惧，教导Robb并独自入Twins谈判"),
            ("Robb Stark", "十五岁的North统帅；必须在军事时间压力下接受政治婚约"),
            ("Walder Frey", "Lord of the Crossing；凭桥梁、兵力和庞大家族索取联盟价格"),
            ("Brynden Tully", "Blackfish；率侦骑屏蔽军队行动并带回Riverrun败讯"),
            ("Roose Bolton", "判断Twins无法强攻，后受命率步兵在东岸迎向Tywin"),
            ("Stevron Frey", "Walder年长继承人；负责迎接与礼仪沟通"),
            ("Perwyn Frey", "作为Catelyn安全返回的 reciprocal hostage 留在North军中"),
            ("Edmure Tully", "Catelyn兄弟；军队被Jaime击溃，本人负伤被俘"),
        ],
        terms=[
            ("the Twins", "Green Fork两岸的双堡与石桥体系，由House Frey控制"),
            ("Green Fork", "Trident北支；本段水高流急，无法直接fording"),
            ("Lord of the Crossing", "Walder因控制Twins和通路获得的称号与经济、军事权力"),
            ("Water Tower", "桥中央防御塔，以arrow slits、murder holes与portcullises控制桥面"),
            ("ward / fosterling", "寄养于另一贵族家庭的孩子，也可承担联盟担保功能"),
            ("marriage pact", "以未来婚姻把临时军事交易升级为长期家族联盟"),
        ],
        synthesis="Chapter 59把战争的核心从战场人数转到基础设施、时间和可信承诺。Robb有两万人，Walder只有近四千，但Twins让后者握有不可替代的通行权；若强攻，Tywin便能从后方到达。Catelyn因此完成两次关键教育：先告诉Robb words可以胜过swords，再以自己的行动证明谈判同样需要勇气。Walder看似只会抱怨，实际上持续计算双方选择。他既不因旧誓无条件帮助Tully，也不因crown誓言立即帮助Lannister；每一项旧日轻视都被他积存为今日索价依据。Catelyn没有把信任当作协议的结果，而是另留四百Northmen监督garrison，这显示政治承诺必须配合执行机制。Walder最终所得也不仅是回报，而是dynastic recognition：两个孙子进入Winterfell、儿子贴近Robb、Arya和Robb婚约把Freys接入Stark未来。Robb郑重同意之所以显得成熟，是因为他知道领主身份会征用私人生活。最后的steel snake仍从murder holes下通过，提醒读者合作没有消除脆弱性；分兵更把全军命运变成一次已经掷出的骰子。",
        contrasts=[
            "**两万军队／一座桥：** 数量优势被不可替代的地理通道反转。",
            "**words／swords：** 谈判不是战斗的软弱替代，而是时间压力下唯一有效工具。",
            "**公开确定／私下恐惧：** Catelyn用必要谎言稳定Robb和诸lords，同时准确知道自身风险。",
            "**oath／price：** 多重誓言没有自动给出行动答案，Walder借解释空间等待最高政治回报。",
            "**family abundance／family distrust：** 庞大后代提供兵力与婚姻资本，也制造继承猜疑。",
            "**honored guest／hostage：** 礼仪语言柔化了实际担保关系。",
            "**steel snake／murder-hole eyes：** 强大军队在狭窄堡道中仍暴露于Frey控制。",
        ],
        questions=[
            "Jon Arryn为何计划让Robert Arryn由Stannis而非Tywin foster，Lysa此前的说法为何不同？",
            "Walder会在军队通过后持续履行协议，还是继续根据局势重新估价？",
            "Robb与Arya的婚约将如何影响他们个人选择与Stark–Frey关系？",
            "Roose率东岸步兵、Robb率西岸骑兵的分兵将分别承担什么任务？",
            "Catelyn留下四百Northmen是否足以约束Twins守军？",
        ],
        extraction_notes="PDF pp.580–592校勘后共125段。7处跨页续段：pp.580–581、583–584、585–586、586–587、588–589、589–590、591–592；其中pp.589–590的Walder同一句话由提取器误拆，已合并。1段涉及未成年角色的性化描述，使用稳定占位符并保留段落位置、剧情摘要和谈判功能。",
    )
    print(f"Wrote Chapter 59 with {len(blocks)} paragraphs")


if __name__ == "__main__":
    main()
