#!/usr/bin/env python3
"""Build Chapter 15 (SANSA) close-reading Markdown."""

from pathlib import Path

from agot_extract import extract_range
from agot_reader_common import write_chapter
from build_agot_chapter14_reader import VOCAB as BASE_VOCAB

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs" / "AGOT_逐章精读"

SUMMARY_BY_ORDER = {
    1: "早餐时Septa Mordane告诉Sansa，Eddard天亮前应国王召唤离开，可能又去猎取当地仍存的aurochs。",
    2: "Sansa说自己从未见过aurochs，同时在桌下喂Lady培根；direwolf像queen般轻柔地从她手中取食。",
    3: "Septa Mordane不赞成贵族小姐在桌边喂“狗”，自己却让蜂蜜从蜂巢滴到面包上。",
    4: "Sansa纠正Lady是direwolf而非dog，并引用Eddard许可证明可以让它们随身。",
    5: "septa仍不满意，称Sansa平时是好女孩，却在Lady问题上像Arya一样任性，随后追问Arya去向。",
    6: "Sansa说Arya不饿，却清楚妹妹很可能早已去厨房哄cook’s boy给她早餐。",
    7: "Septa Mordane要求Arya穿漂亮灰天鹅绒，因为二人获邀与queen和Myrcella同乘royal wheelhouse。",
    8: "Sansa早已穿最好蓝丝绸并期待一周，只因可能见到未婚夫Joffrey便认定自己爱上他；她唯一担心Arya破坏完美日子。",
    9: "得到离席许可后，Sansa离开旅店common room，Lady紧跟其后。",
    10: "旅店外营地正在拆帐、装车；即使这是Sansa见过最大旅店，也容不下已膨胀到四百多人的王室队伍。",
    11: "Sansa在Trident河岸找到Arya；她穿着连续几日的riding leathers，正勉强替不配合的Nymeria刷掉干泥。",
    12: "Sansa转述septa命令，让Arya换漂亮衣服并一起乘queen的wheelhouse。",
    13: "Arya拒绝，说要与Mycah逆流骑行，到ford寻找rubies。",
    14: "Sansa不明白她所说的是哪些rubies。",
    15: "Arya像看笨蛋般解释，这是Rhaegar的rubies，因为此地是Robert杀死他并赢得王冠的战场。",
    16: "Sansa难以置信地说Myrcella正在等她们，queen的邀请不能拒绝。",
    17: "Arya不在意，并嫌wheelhouse没有窗户，沿途什么也看不见。",
    18: "Sansa认为沿途不过是田野、农场和holdfasts，又恼怒妹妹果然要毁掉自己珍视的邀请。",
    19: "Arya坚持沿途并非无聊，只是Sansa从不和她们一起去看。",
    20: "Sansa强烈表示自己讨厌骑马，因为只会弄脏、积灰和身体酸痛。",
    21: "Arya边与Nymeria纠缠边说穿越Neck时数到三十六种新花，Mycah还带她看了lizard-lion。",
    22: "Sansa回忆自己厌恶Neck十二天的潮湿、狭窄causeway、fungus、quicksand、蛇和潜伏水中的lizard-lions。",
    23: "危险没有阻止Arya；她曾满身泥地带花给Eddard，Sansa希望父亲训她，Eddard却拥抱感谢，使Sansa认为妹妹更任性。",
    24: "花原来叫poison kisses并令Arya起rash，她却笑着接受Mycah用泥止痒的办法；Sansa还看见她身上有来源不明的bruises与welts。",
    25: "Arya继续谈haunted watchtower、wild horses等南行见闻，同时追逐不肯被梳毛的Nymeria。",
    26: "Sansa提醒Arya，Eddard曾禁止她离开队伍。",
    27: "Arya说自己没有走远且Nymeria一直在旁，也并非总离队，有时会沿wagons与不同人交谈。",
    28: "Sansa鄙视Arya结交的squires、grooms、serving girls和出身不明者，尤其讨厌睡meat wagon、带屠宰气味的butcher’s boy Mycah。",
    29: "耐心耗尽的Sansa命Arya随自己回去，因为不能拒绝queen，Septa Mordane也会等她。",
    30: "Arya不理她，粗暴拉刷子惹Nymeria低吼逃开，又追着狼叫它回来。",
    31: "Sansa用成人般合理语气描述lemon cakes、羽毛枕与queen茶会，问Arya为何宁愿骑臭马受累。",
    32: "Arya随口说自己不喜欢queen，令Sansa震惊；她继续抱怨queen不准Nymeria进入wheelhouse。",
    33: "Sansa说royal wheelhouse不适合狼，而且Myrcella害怕它们。",
    34: "Arya说Myrcella像小婴儿，抓住Nymeria后又被挣脱，最终气得扔刷子骂“坏狼”。",
    35: "Sansa想起kennelmaster说动物像主人，便抱住温顺Lady暗笑；Arya察觉后怒视并再次坚持出去骑马。",
    36: "Sansa反说Arya像孩子，自己单独去会更愉快，还故意说要与Lady吃光lemon cakes。",
    37: "Arya临走前提醒queen同样不会让Lady进入wheelhouse，随即追Nymeria离开，使Sansa无从回击。",
    38: "Sansa独自受辱，绕长路返回Septa Mordane等候的旅店。",
    39: "Lady安静陪伴几乎落泪的Sansa；她只希望世界像songs一样漂亮，无法理解Arya为何不像Myrcella般甜美优雅。",
    40: "Sansa甚至幻想Arya若像Jon一样是bastard会更容易解释差异；Catelyn曾明确告诉她Arya是trueborn亲妹妹。",
    41: "接近营地中心时，Sansa被wheelhouse周围蜂群般兴奋人声吸引，暂时忘记苦恼，并听见queen感谢council的礼遇。",
    42: "Sansa向认识的squire询问发生了什么。",
    43: "squire解释council从King’s Landing派来骑手，为国王提供余程honor guard。",
    44: "Sansa让Lady替她从人群中开路，靠近后看见两名穿华美铠甲的骑士跪在queen面前。",
    45: "一名老骑士穿雪白enameled scales与Kingsguard白斗篷，虽头发苍白却仍显强壮优雅。",
    46: "另一名近二十岁的骑士穿forest-green plate、手持金鹿角helm，黑发绿眼，是Sansa见过最英俊的男人。",
    47: "Sansa稍后才注意第三个陌生人：他沉默站在马旁，消瘦麻脸、头发稀少，穿朴素陈旧护甲，背负two-handed greatsword。",
    48: "queen与跪地骑士交谈时Sansa无法移开对第三人的目光；他转头回望，Lady低吼，Sansa被前所未有的恐惧压倒并后退撞人。",
    49: "强壮双手抓住Sansa肩膀，她一度以为是父亲，回头却看见Sandor烧伤的脸和扭曲笑容，被问是否如此怕他。",
    50: "Sansa一直怕Sandor，却觉得他不及第三人可怕；她挣脱后抱住挡在中间警告的Lady，因众人围观嘲笑而羞耻。",
    51: "人群惊讶direwolf出现在营地，Sandor讥讽Starks用狼当wet nurses；Sansa发现两名陌生骑士已拔剑，因此再次恐惧落泪。",
    52: "Sansa听见queen命Joffrey过去帮助她。",
    53: "她心目中的prince随即来到身边。",
    54: "Joffrey命众人放过Sansa、收剑，拉她起身并把Lady称作小宠物，又以“dog”命Sandor离开别吓自己的betrothed。",
    55: "Sandor服从退走；Sansa因自己失态而努力镇定，向Joffrey解释真正令她害怕的是另一人。",
    56: "两名陌生骑士对视，年轻绿甲骑士笑着猜她指的是Payne。",
    57: "白甲老骑士温和说Ser Ilyn有可怕外貌，自己也常被他吓到。",
    58: "queen走下wheelhouse，说King’s Justice理应让wicked害怕，否则便选错了人。",
    59: "Sansa终于恢复礼仪，以“那您一定选对了”回应，引发周围大笑。",
    60: "白甲老人称赞她不愧为Eddard之女，自我介绍为Kingsguard的Ser Barristan Selmy。",
    61: "Sansa认出Barristan the Bold的名声，并准确复述其Lord Commander、councillor及曾服务Aerys的身份，以规范礼辞回应。",
    62: "绿甲骑士调笑他应叫Barristan the Old，又挑战Sansa根据线索说出自己身份。",
    63: "Joffrey因对方称Sansa为wolf girl而僵硬，警告他注意如何称呼自己的betrothed。",
    64: "Sansa赶紧平息Joffrey怒气，根据golden antlers、House Baratheon与年龄推断对方是Renly Baratheon。",
    65: "Ser Barristan用“prancing jackanapes”回敬Renly的年龄玩笑。",
    66: "Renly带头大笑令紧张消退，但Ser Ilyn挤到Sansa面前沉默凝视；她压住Lady并为可能冒犯他而道歉。",
    67: "Ser Ilyn不回答，苍白眼神让Sansa感觉衣服和皮肤都被剥去、灵魂暴露，随后沉默离开。",
    68: "Sansa困惑地问Joffrey自己是否说错话，为何Ser Ilyn拒绝回答。",
    69: "Renly带狡黠笑容说Ser Ilyn十四年来一直不太健谈。",
    70: "Joffrey厌恶地看叔叔，告诉Sansa是Aerys用hot pincers拔掉了Ser Ilyn的舌头。",
    71: "queen说Ser Ilyn会以剑有力表达且忠诚无疑，随后因council会议取消Sansa与Myrcella行程，安排Joffrey陪她。",
    72: "Joffrey正式接受，牵Sansa离开；她因能与prince共度一天而狂喜，把他刚才的帮助比作songs中的英雄救美。",
    73: "Joffrey触碰衣袖便使Sansa心跳加速，他询问她想做什么。",
    74: "Sansa心中只想与他相处，口中却把选择完全交给prince。",
    75: "Joffrey思考后提议出去骑马。",
    76: "刚对Arya声称讨厌骑马的Sansa立刻说自己非常喜欢。",
    77: "Joffrey说Lady可能惊马、Sandor又吓到Sansa，提议把两者都留下并单独出发。",
    78: "Sansa虽迟疑仍同意绑住Lady，但不明白Joffrey所说的dog是谁。",
    79: "Joffrey笑着解释那其实是Cersei的dog，指被安排保护自己的Sandor。",
    80: "Sansa终于明白，因反应慢而责怪自己，又担心prince会因她显得愚笨而不爱她；她询问不带护卫是否安全。",
    81: "Joffrey因问题恼怒，宣称自己接近成人、不用木剑战斗，并展示为十二岁体型缩制的双刃长剑Lion’s Tooth。",
    82: "二人留下Lady和Sandor，只有Lion’s Tooth陪伴，沿Trident北岸向东骑行。",
    83: "Sansa把这天体验成魔法冒险：Joffrey高速骑马、探洞、追踪shadowcat、命holdfast供餐，Sansa还喝下超过以往的wine。",
    84: "Joffrey以betrothed身份替她续杯，说她想喝多少都可以。",
    85: "饭后二人放慢速度，Joffrey甜声唱歌；微醺眩晕的Sansa开始询问是否该返回。",
    86: "Joffrey说前方便是Robert杀Rhaegar的战场，兴奋模仿击碎胸甲，又讲Jaime杀Aerys，随后听见未知声响。",
    87: "Sansa也听见木头连续碰撞的声音，感到紧张并再次提议回去。",
    88: "Joffrey坚持查看并转马追声，Sansa只得跟随；声音逐渐变成木击、粗重呼吸与grunt。",
    89: "Sansa焦虑地确认前方有人，并开始想念被留下的Lady。",
    90: "Joffrey拔出Lion’s Tooth保证她安全，钢刃出鞘声反而令她发抖，随后带路穿过树林。",
    91: "空地中Mycah和Arya正用broom handles模拟骑士交手；年长强壮的Mycah占优，击中Arya手指使她掉落木棍。",
    92: "Joffrey发笑，Mycah惊慌丢棍；Arya怒视并吸吮受伤指节，Sansa震惊认出妹妹。",
    93: "Arya含着愤怒眼泪命二人离开，不要打扰她们。",
    94: "Joffrey确认Arya是Sansa妹妹，又以不受Mycah年长影响的命令口吻盘问其身份。",
    95: "Mycah认出prince后避开目光，低声报出姓名并称m’lord。",
    96: "Sansa用阶级身份介绍Mycah是butcher’s boy。",
    97: "Arya立即纠正Mycah是自己的friend，并要求Joffrey别碰他。",
    98: "Joffrey持剑下马，以Mycah想当knight为由命他捡起木棍，声称要测试他。",
    99: "Mycah因恐惧僵在原地。",
    100: "Joffrey逼近，嘲弄他是否只敢和小女孩打斗。",
    101: "Mycah反复解释是Arya主动要求对练。",
    102: "Sansa从Arya脸红便知道Mycah说真话，但Joffrey受wine影响已经wild，不愿听解释，只继续逼他捡“剑”。",
    103: "Mycah摇头强调那只是一根stick，不是真剑。",
    104: "Joffrey以他只是butcher’s boy、不是knight回应，把Lion’s Tooth抵在其眼下脸颊并压出流血伤口。",
    105: "Arya尖叫让他停止，捡起自己掉落的木棍。",
    106: "害怕的Sansa命Arya不要介入。",
    107: "Joffrey仍盯着Mycah，用“不会伤他太多”回应Arya。",
    108: "Arya直接向Joffrey冲去。",
    109: "Sansa下马太慢；Arya击破木棍打伤Joffrey后脑，Joffrey以真剑反击并把她逼向树，Mycah逃跑、马匹受惊，Sansa只会哭喊双方正在毁掉一切。",
    110: "Nymeria像灰影冲来，咬住Joffrey持剑手臂，把他扑倒并迫使Lion’s Tooth落地。",
    111: "Arya用鞭子般的声音叫Nymeria停下。",
    112: "direwolf立刻回到Arya身边；Joffrey抱着流血手臂呜咽，Arya拾起Lion’s Tooth，用他刚才的话说狼没有伤他“太多”。",
    113: "Joffrey恐惧地求Arya别伤害自己，并威胁要告诉mother。",
    114: "Sansa尖叫要求Arya别再碰Joffrey。",
    115: "Arya把Lion’s Tooth全力扔进Trident，随后骑马带Nymeria逃离。",
    116: "Sansa跪到受伤Joffrey身边，把事件表述成“他们对你做的”，温柔安慰并准备去holdfast求援。",
    117: "Joffrey睁眼只以憎恨和轻蔑看她，吐出命令让她离开且别碰自己。",
}

SUMMARIES = [SUMMARY_BY_ORDER[i] for i in range(1, 118)]

KEY_NOTES = {
    2: "Lady取培根“as delicate as a queen”，把direwolf行为写成Sansa理想贵族女性气质的镜像。",
    3: "septa一边训斥桌边喂动物，一边让蜂蜜滴落，细节使礼仪权威带有轻微喜剧性的选择性。",
    5: "把Sansa和Arya相提并论是septa最有效的批评，因为Sansa的自我认同正建立在“我不像妹妹”上。",
    8: "Sansa承认并不了解Joffrey，却已“爱上”他所符合的prince模板；她爱的是故事角色与外貌线索先于真实人格。",
    10: "四百余人使王室旅行像移动城镇；沿途资源紧张也解释Arya为何能接触不同阶级的大量人员。",
    13: "rubies对Arya是可探索的历史遗物，对Sansa却是无法立即放进礼仪日程的陌生词；姐妹关注系统完全不同。",
    18: "Sansa称沿途“只是”田野和农场，Arya认为真正问题是她没有观看；这不是风景本身，而是注意力方式之争。",
    20: "Sansa此刻明确说hate riding，后面面对Joffrey却会立即宣称love riding，暴露她如何为浪漫期待改写偏好。",
    21: "三十六种新花和lizard-lion说明Arya不是无目的逃规矩，她正在用身体旅行建立自己的自然知识。",
    22: "Neck描写同时证明Sansa并非“什么都没看见”；她观察细致，只把所见组织成危险、污秽和不适，而非发现。",
    23: "Sansa期待父亲用高贵小姐规范惩罚Arya，Eddard却感谢花；她把父亲的接纳理解为纵容，因为它威胁单一好女孩标准。",
    24: "rash似乎应成为教训，Arya却把它变成可笑故事和新知识；姐妹对错误的理解分别是羞耻与经验。",
    28: "Sansa列举Arya朋友时以职业、衣着和出生分类，Mycah的气味更让阶级成为身体反感。",
    31: "Sansa自称“adult and reasonable”，但论证完全由cakes、pillows和queen构成；成熟姿态与儿童欲望并存。",
    32: "Arya一句“不喜欢queen”让Sansa震惊，不是因具体理由，而是她认为王权对象本身不应被个人喜恶评价。",
    35: "动物像主人这一说法让Sansa以Lady温顺证明自己优雅，也以Nymeria反衬Arya；她主动选择最利于自我形象的解释。",
    37: "Arya指出Lady也会被排除，击穿Sansa“我与Lady一起享受茶会”的炫耀，令Sansa感到被妹妹羞辱。",
    39: "Sansa想要一切“像songs一样漂亮”，这是全章核心过滤器：现实价值取决于能否维持既定故事形式。",
    40: "她用bastard身份想象解释姐妹差异，显示合法出生在她心中不仅是法律地位，也被误当成性格和外貌一致性的保证。",
    44: "Lady清路让Sansa快速靠近权力中心，同时也令普通人因direwolf恐惧退让；她把动物保护力量体验为社交通行证。",
    45: "Sansa先看见白甲雪色与优雅，再看见老人身份；她习惯从纹章和外观读取骑士价值。",
    46: "Renly几乎完全按romance男主角视觉语汇出现：青春、英俊、力量、黑发绿眼与金鹿角。",
    47: "Ser Ilyn的朴素旧甲与前两人的闪耀形成反差；“hard use”让装备功能性比装饰更可怕。",
    48: "Lady先于Sansa发出低吼；Sansa的恐惧没有明确理由，来自被第三人反向凝视的瞬间。",
    49: "她先误认抓肩者为father，随后看见Sandor烧伤脸；安全期待和恐怖形象在同一转身中翻转。",
    50: "Sansa此前怕Sandor，如今觉得他“不及另一人一半可怕”，恐惧是比较性的；围观笑声又立刻将危险转成羞耻。",
    51: "Sandor的wet nurse笑话把Stark与direwolf亲密关系幼儿化；拔剑骑士则表明围观者的笑闹可能迅速变成动物威胁。",
    53: "独立句“And her prince was there”模拟songs中的英雄登场，完全贴合Sansa的期待结构。",
    54: "Joffrey此刻确实制止拔剑、扶她起身并驱走Sandor；精读应保留这些可见行为，同时注意他把保护者称作dog。",
    59: "Sansa把恐惧转成合乎courtly wit的回答，笑声不再针对她而由她引发，礼仪技能帮助她重新控制场面。",
    61: "她的知识不是空洞背诵：能准确识别官职、过去君主与歌谣名号，使她在陌生权力网络中迅速找到恰当语言。",
    64: "Sansa根据sigil、家族结构与年龄完成推理，证明她具有敏锐的heraldic和court知识。",
    66: "Sansa用手按住Lady的头，主动压制保护性警告以维持礼貌；社交规则在她判断中暂时高于动物直觉。",
    67: "Ser Ilyn的无声凝视被写成逐层剥除衣服、皮肤到灵魂，恐惧来自完全暴露而非具体动作。",
    70: "Joffrey以具体酷刑解释沉默；他对Renly的loathing也短暂暴露王室内部并非Sansa想象的和谐家庭。",
    71: "Cersei称Ser Ilyn以剑“eloquently”表达，将失语与执行暴力重新包装成忠诚职业能力。",
    72: "Sansa把Joffrey刚才的介入直接翻译为Serwyn或Aemon式英雄救美，删去他对Sandor的侮辱与母亲的安排。",
    74: "她心中有明确愿望，却口头把选择权交给Joffrey；取悦prince使自我偏好不再被表达。",
    76: "“Oh, I love riding”与第20段的“I hate riding”构成最清晰自我改写，Sansa在浪漫机会前调整过去事实。",
    77: "Joffrey把Lady与Sandor并列为可留下的wolf和dog，表面追求私密，实际同时移除双方最强保护者。",
    80: "Sansa不是只没听懂比喻，她立即担忧“显得愚蠢便不被爱”，说明关系想象已要求她持续自我审查。",
    81: "Lion’s Tooth是按十二岁身体缩制的真剑；Joffrey用“不玩木头”把拥有致命武器等同接近成年。",
    82: "“no company save Lion’s Tooth”把剑拟成唯一同伴，暗示二人的私密冒险由武器而非保护者陪伴。",
    83: "Sansa以glorious、magical、adventures组织一天；Joffrey命holdfast供食与她过量饮酒，都被浪漫滤镜吸收。",
    84: "“my betrothed”听来像宠爱，也让十二岁Joffrey以关系身份越过Eddard对酒量的限制。",
    86: "Joffrey把Rhaegar死亡表演成crunch音效和挥锤游戏，历史暴力成为少年继承王权的兴奋故事。",
    87: "未知木击声令Sansa第二次提出回去；她的危险直觉存在，但总被Joffrey的选择压过。",
    89: "真正靠近风险时，她开始想念Lady，说明先前同意绑狼并非没有安全代价。",
    91: "文本明确二人在playing at knights，武器是broom handles；Mycah占优和Arya受伤都发生在双方同意的练习中。",
    92: "Joffrey笑声先让Mycah意识到社会权力进入游戏；木棍落地标志平等练习结束。",
    96: "Sansa用“butcher’s boy”而非姓名回答，替Joffrey提供阶级分类；Arya下一句则用friend恢复个人关系。",
    98: "Joffrey把捡木棍称为骑士测试，但自己拿真剑、对方面对prince，根本不存在公平决斗条件。",
    102: "Sansa知道Mycah说真话，也看出wine使Joffrey失控；她不是没看见，而是尚未让这些观察改变对prince的总体判断。",
    104: "Joffrey用“only”同时缩小Mycah身份和他的木棍，随后用真钢在眼下见血，阶级语言转化为身体暴力。",
    107: "“not hurt him much”是威胁性弱化；后面Arya会原样返还，使语言成为权力翻转标记。",
    109: "Sansa反复喊“you’re spoiling it”，把真实刀剑危险首先理解为毁掉浪漫日；她的故事滤镜此刻成为行动瘫痪。",
    110: "Nymeria像grey blur进入，重复direwolf在紧急时刻超越人类反应速度的模式；目标精准是持剑手臂。",
    111: "Arya的声音“像鞭子”，与Catelyn和Robb等危机中的权威声音呼应；direwolf立即服从。",
    112: "Arya原样回敬“没有伤太多”，把Joffrey的轻蔑威胁变成对他自身行为的镜像审判。",
    113: "失去剑与保护者后，Joffrey的威胁退化为告诉mother，显示“almost a man grown”外表下仍是依赖母权的孩子。",
    115: "Arya没有用Lion’s Tooth伤害倒地者，而是扔进河里，实际消除继续暴力的武器后逃走。",
    116: "Sansa说“他们对你做的”已把Joffrey归为纯受害者、Arya和Nymeria归为共同施害者，删去了Mycah被剑逼迫的前因。",
    117: "结尾用loathing和contempt彻底反转prince的温柔外观；Sansa的抚触不再被读作爱，而被Joffrey体验为屈辱见证。",
}

STAGES = [
    (1, 21, "本段建立Sansa对Joffrey和queen茶会的期待，并用rubies、骑行和沿途景物展示姐妹完全不同的注意方式。"),
    (22, 40, "本段通过Neck回忆、朋友阶级和direwolf性格加深姐妹冲突；Sansa的核心愿望是让家人与世界符合songs的漂亮秩序。"),
    (41, 72, "本段让King’s Landing人物以铠甲、纹章和宫廷礼仪登场；Sansa成功识别Barristan与Renly，也把Joffrey的介入解释成英雄救美。"),
    (73, 90, "本段让Sansa为取悦Joffrey改写自己对骑马的喜好，并同意留下Lady与Sandor；魔法般的一天逐渐被酒、真剑和危险直觉侵入。"),
    (91, 117, "本段从Arya与Mycah的木棍练习升级为Joffrey持真剑的阶级欺凌；Arya和Nymeria反击后，Sansa的浪漫叙事彻底破裂。"),
]

BACKGROUNDS = {
    1: "**动物：** aurochs是体型巨大的野牛；Robert此时可能正在进行另一场狩猎。",
    15: "**历史背景：** Trident是Robert击败Rhaegar的战场；Rhaegar铠甲上的rubies在战斗中散落河中。",
    22: "**地理：** Neck是北境南缘湿地，kingsroad沿狭窄causeway穿过；quicksand与lizard-lions构成真实危险。",
    28: "**阶级：** Mycah是随王室队伍南行的butcher’s boy；Sansa以职业和气味评价他，Arya则称其为friend。",
    43: "**政治：** King’s Landing council派honor guard迎接国王队伍，带来Ser Barristan、Renly和Ser Ilyn。",
    45: "**身份：** Ser Barristan Selmy是Kingsguard Lord Commander，绰号Barristan the Bold，曾先后服务Aerys与Robert。",
    58: "**职务：** King’s Justice是王室headsman，负责执行死刑；Ser Ilyn Payne担任该职。",
    64: "**身份：** Renly Baratheon是Robert最年轻的兄弟、Lord of Storm’s End和councillor，纹章线索来自Baratheon crowned stag。",
    70: "**文本事实：** Ser Ilyn十四年前被Aerys以hot pincers拔舌，因此无法说话。",
    81: "**武器：** Lion’s Tooth是为十二岁Joffrey体型缩制的castle-forged双刃长剑，不是木制训练武器。",
    86: "**历史叙述：** Joffrey概括Robert在Trident杀Rhaegar、Jaime杀Aerys；其crunch式表演是少年主观讲述。",
    91: "**文本事实：** Arya与Mycah正在双方同意下用木棍练习；Mycah年长强壮并击中Arya，但没有使用真剑。",
    102: "**文本事实：** Sansa从Arya反应判断Mycah所说属实，也判断wine使Joffrey变得wild。",
    110: "**文本事实：** Nymeria咬的是Joffrey持剑手臂；Arya一声命令后它立即松口。",
}

EXTRA_VOCAB = [
    ("break one's fast", "/breɪk wʌnz fæst/", "phr.", "吃早餐；结束夜间禁食", "古风表达"),
    ("aurochs", "/ˈaʊrɑːks/", "n.", "原牛；大型野牛", "狩猎动物"),
    ("comb", "/koʊm/", "n.", "蜂巢块", "此处不是梳子"),
    ("appease", "/əˈpiːz/", "v.", "安抚；使满意", "septa仍不满意"),
    ("willful", "/ˈwɪlfəl/", "adj.", "任性的；固执违抗的", "贵族教育评价"),
    ("wheedle", "/ˈwiːdəl/", "v.", "哄骗；用甜言蜜语说服", "向厨房少年讨早餐"),
    ("betrothed", "/bɪˈtroʊðd/", "n./adj.", "未婚夫或未婚妻；订婚的", "政治婚约身份"),
    ("causeway", "/ˈkɔːzweɪ/", "n.", "堤道；穿越湿地的高路", "Neck交通"),
    ("clammy", "/ˈklæmi/", "adj.", "湿冷黏腻的", "空气触感"),
    ("fungus", "/ˈfʌŋɡəs/", "n.", "真菌；菌类", "树枝垂挂"),
    ("stagnant", "/ˈstæɡnənt/", "adj.", "停滞不流的", "沼泽水面"),
    ("quicksand", "/ˈkwɪksænd/", "n.", "流沙", "离开causeway的危险"),
    ("rash", "/ræʃ/", "n.", "皮疹", "poison kisses造成"),
    ("welt", "/welt/", "n.", "隆起伤痕；鞭痕", "Arya身上淤伤"),
    ("prattle", "/ˈprætəl/", "v.", "喋喋不休；天真地说个不停", "Sansa对Arya话语的评价"),
    ("heedless", "/ˈhiːdləs/", "adj.", "不留心的；不顾后果的", "无视Sansa震惊"),
    ("intricate", "/ˈɪntrɪkət/", "adj.", "复杂精细的", "铠甲工艺"),
    ("enameled", "/ɪˈnæməld/", "adj.", "饰有珐琅的", "白色甲片"),
    ("chasing", "/ˈtʃeɪsɪŋ/", "n.", "錾刻金属纹饰", "silver chasings"),
    ("antlered", "/ˈæntlərd/", "adj.", "带鹿角的", "Renly头盔"),
    ("pockmarked", "/ˈpɑːkmɑːrkt/", "adj.", "有麻点痘疤的", "Ser Ilyn面貌"),
    ("fearsome aspect", "/ˈfɪrsəm ˈæspekt/", "phr.", "可怕外表", "正式礼貌说法"),
    ("jackanapes", "/ˈdʒækəneɪps/", "n.", "轻浮自负的年轻人", "古风玩笑性骂词"),
    ("quell", "/kwel/", "v.", "平息；压制", "平息Joffrey怒气"),
    ("eloquently", "/ˈeləkwəntli/", "adv.", "雄辩地；有表现力地", "以剑表达的冷酷双关"),
    ("worshipfully", "/ˈwɜːrʃɪpfəli/", "adv.", "崇拜地", "Sansa凝视Joffrey"),
    ("adroitly", "/əˈdrɔɪtli/", "adv.", "灵巧地；巧妙地", "按少年比例缩制"),
    ("pommel", "/ˈpɑːməl/", "n.", "剑柄末端球饰", "lion’s-head pommel"),
    ("courser", "/ˈkɔːrsər/", "n.", "快速战马或骑乘马", "Joffrey坐骑"),
    ("reckless abandon", "/ˈrekləs əˈbændən/", "phr.", "不顾一切的放纵", "高速骑行方式"),
    ("lair", "/ler/", "n.", "野兽巢穴", "shadowcat栖身处"),
    ("lustily", "/ˈlʌstɪli/", "adv.", "有力而兴致勃勃地", "木棍对练"),
    ("ungainly", "/ʌnˈɡeɪnli/", "adj.", "笨拙不雅的", "Mycah外貌"),
    ("avert", "/əˈvɜːrt/", "v.", "移开；避开", "avert one’s eyes"),
    ("lunge", "/lʌndʒ/", "v./n.", "猛冲；突刺", "练习动作"),
    ("loathe", "/loʊð/", "v.", "憎恶", "loathing名词形式"),
    ("contempt", "/kənˈtempt/", "n.", "轻蔑；鄙视", "结尾Joffrey眼神"),
]
VOCAB = BASE_VOCAB + EXTRA_VOCAB

def main():
    blocks = extract_range(133, 144, "SANSA", "CH15")
    write_chapter(
        out=OUT, chapter=15, pov="SANSA", page_start=133, page_end=144,
        blocks=blocks, summaries=SUMMARIES, key_notes=KEY_NOTES, stages=STAGES,
        backgrounds=BACKGROUNDS,
        default_background="本段没有新增必须补充的世界观设定；重点在Sansa的浪漫叙事、姐妹差异、宫廷礼仪、阶级判断或河边冲突升级。",
        vocab=VOCAB,
        guide="Sansa期待与queen、Myrcella及Joffrey共度完美一天，却先与Arya为衣着、骑行、朋友和direwolves争吵。她随后凭铠甲、纹章与礼仪知识成功识别Ser Barristan和Renly，并把Joffrey的介入理解成songs中的英雄救美。为了与prince单独相处，她改口说自己喜欢骑马、同意留下Lady与Sandor，又在wine和冒险气氛中忽略多次想回去的直觉。河边的木棍练习被Joffrey带来的真剑和阶级权力打破；Sansa明知Mycah说真话、也看见Joffrey因酒变得wild，却仍无法让事实取代她心中的prince故事。",
        people=[
            ("Sansa Stark", "本章视角人物；擅长宫廷礼仪，却不断用songs的浪漫结构解释现实"),
            ("Arya Stark", "Sansa的妹妹，与Mycah用木棍练习，在Joffrey威胁后主动反击"),
            ("Joffrey Baratheon", "Sansa的betrothed；先在营地保护她，后持真剑欺凌Mycah并攻击Arya"),
            ("Mycah", "十三岁的butcher’s boy与Arya朋友，在双方同意下陪她练习"),
            ("Lady / Nymeria", "Sansa和Arya的direwolves；分别代表温顺陪伴与危机中的主动保护"),
            ("Ser Barristan Selmy", "Kingsguard Lord Commander，以白甲和礼貌言辞登场"),
            ("Renly Baratheon", "Robert的年轻兄弟、councillor与Lord of Storm’s End"),
            ("Ser Ilyn Payne", "失去舌头的King’s Justice，其沉默凝视令Sansa恐惧"),
            ("Sandor Clegane", "Joffrey的bodyguard，被他以dog称呼并留在营地"),
        ],
        terms=[
            ("Trident", "Robert杀死Rhaegar并取得叛乱决定性胜利的河流战场"),
            ("Rhaegar’s rubies", "Rhaegar铠甲上在Trident战斗中散落的红宝石"),
            ("King’s Justice", "王室死刑执行官，Ser Ilyn Payne担任此职"),
            ("Lion’s Tooth", "Joffrey按少年体型缩制的castle-forged真钢长剑"),
            ("lizard-lion", "Neck湿地水生掠食动物，外观像带眼睛和牙齿的黑木"),
        ],
        synthesis="Chapter 15最重要的不是Sansa“看不见事实”，而是她看见后如何重新编排。她能细致观察Neck危险、识别纹章、推断Renly身份，也能从Arya脸红判断Mycah说真话；她缺少的不是感知能力，而是允许不愉快事实改写理想故事的能力。Joffrey在营地的确做出保护姿态，所以她把他放进英雄模板并非凭空幻想；问题在于模板随后吸收了他的轻蔑、饮酒鼓励、移除保护者、真实刀剑和阶级欺凌。到冲突高潮，她喊的不是“别杀人”，而是“你们在毁掉它”，因为被毁掉的同时是现场安全与她心中的完美日子。结尾Joffrey的loathing迫使浪漫表面第一次无法维持。",
        contrasts=[
            "**Lady／Nymeria：** Sansa用温顺Lady证明自身优雅，Arya的Nymeria则在真实危险中主动保护主人。",
            "**hate riding／love riding：** Sansa对妹妹说讨厌骑马，对Joffrey却立刻宣称热爱，显示取悦关系如何改写自我表达。",
            "**songs／现场事实：** 英雄救美模板能解释营地片刻，却无法容纳河边阶级欺凌与真剑伤害。",
            "**court knowledge／moral judgment：** Sansa能精准识别官职纹章，却没有及时把Mycah的真话转化为对Joffrey的反对。",
            "**wood／steel：** Arya与Mycah的木棍属于游戏和训练，Lion’s Tooth使权力不对等变成致命现实。",
            "**prince外貌／结尾眼神：** 金发、蓝衣和礼貌姿态最终被loathing与contempt取代。",
        ],
        questions=[
            "Sansa会如何向成人讲述河边发生的事情？",
            "Arya和Nymeria逃向哪里，能否安全返回？",
            "Joffrey会如何描述自己受伤的经过？",
            "被扔入Trident的Lion’s Tooth能否找回？",
        ],
        extraction_notes="提取器正确保留PDF pp.134–135、135–136、141–142和143–144的4个跨页段落",
    )
    print(f"Wrote Chapter 15 with {len(blocks)} paragraphs")

if __name__ == "__main__":
    main()
