#!/usr/bin/env python3
"""Build Chapter 16 (EDDARD) close-reading Markdown."""

from pathlib import Path

from agot_extract import extract_range
from agot_reader_common import write_chapter
from build_agot_chapter15_reader import VOCAB as BASE_VOCAB

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs" / "AGOT_逐章精读"

SUMMARY_BY_ORDER = {
    1: "侍卫报告终于找到Arya。",
    2: "Eddard立刻追问是己方还是Lannister的人先找到她。",
    3: "来人说明Jory找到Arya，而且她没有受伤。",
    4: "四天搜索后的Eddard向诸神致谢，并命人立刻把女儿带来。",
    5: "侍卫说Lannister守门人已把消息报告给queen，Arya因此被直接带去见king。",
    6: "Eddard压住怒火，叫上同为事件见证人的Sansa；Sansa已经因等待和担忧而疲惫。",
    7: "他穿过城堡庭院时强迫自己维持Hand应有的尊严，不让焦急变成公开失态。",
    8: "众人暂住Ser Raymun Darry的城堡；Darry家曾为Rhaegar作战，旧仇使王室队伍与主人相处紧张。",
    9: "大厅已经挤满骑士和侍从；Eddard意识到本可私下解决的孩子争执现在成了公开审判。",
    10: "Robert闷闷不乐地坐在高位，Cersei和受伤的Joffrey站在身旁。",
    11: "Arya与Jory站在厅中央；她看见父亲便哭了出来。",
    12: "Eddard跪下拥抱她，Arya一再道歉。",
    13: "他先确认女儿是否受伤，并注意到她又小又瘦，孤零零地面对满厅成人。",
    14: "Arya说自己没有受伤，只是很饿，这几天主要靠野果充饥。",
    15: "Eddard答应给她食物，同时扫视敌意人群；Jaime与Sandor还在北方搜索，他质问为何无人先通知自己。",
    16: "Cersei把他的质问解释成对王后的冒犯。",
    17: "Robert制止妻子并向Eddard道歉，说自己只想尽快把事情处理掉。",
    18: "Eddard要求说明究竟要处理什么。",
    19: "Cersei指控Arya与屠夫的儿子袭击Joffrey，还放direwolf咬他。",
    20: "Arya立刻说Nymeria是因为Joffrey正在伤害Mycah才咬他。",
    21: "Cersei坚持Joffrey的说法：Arya和Mycah用棍棒攻击他，再放狼扑咬。",
    22: "Arya愤怒否认。",
    23: "Joffrey声称三者同时袭击自己，并说Arya把Lion’s Tooth扔进河里；讲述时他不看Arya。",
    24: "Arya直接称Joffrey撒谎。",
    25: "Joffrey命她闭嘴。",
    26: "Robert喝止双方，决定先让Arya完整讲述，再听Joffrey的版本。",
    27: "Arya讲到河边冲突时，Sansa进厅；Renly听到Joffrey被解除武装便忍不住发笑，Robert让他出去。",
    28: "Renly边退边重复一个九岁小女孩用扫帚柄打败Joffrey的画面，使Joffrey的英雄叙述更显可笑。",
    29: "Joffrey随后给出完全不同的版本；Robert因无法从两套故事中判定事实而恼怒。",
    30: "Eddard指出Sansa亲眼见到全过程，可以终结争议。",
    31: "Sansa分别看向妹妹和未婚夫，最后声称自己不记得、事情发生得太快。",
    32: "Arya认为Sansa明明知道真相却不肯说，立即冲过去打她。",
    33: "Jory拉住Arya，Eddard则扶住Sansa，姐妹被强行分开。",
    34: "Cersei把Arya称作失控的野孩子，要求惩罚。",
    35: "Robert把事件降格为孩子争斗，指出没有造成不可挽回的伤害。",
    36: "Cersei反驳Joffrey手臂的伤疤会伴随一生。",
    37: "Robert裁定双方都应吸取教训，并要求Eddard管教Arya、自己管教Joffrey。",
    38: "Eddard以为事情终于结束，感到如释重负。",
    39: "Cersei却追问那只direwolf应如何处置。",
    40: "Robert一时像是真的忘记了狼的存在。",
    41: "Arya紧张起来；Jory报告沿Trident两岸都没有找到Nymeria。",
    42: "Robert接受狼已经逃走，准备就此作罢。",
    43: "Cersei悬赏一百枚gold dragons购买Nymeria的皮。",
    44: "Robert拒绝由王室付钱，叫她用Lannister的金子。",
    45: "Cersei讥讽国王吝啬，又暗示真正的king理应替儿子取得wolfskin。",
    46: "Robert再次强调他们手上根本没有狼。",
    47: "Cersei平静地指出他们确实有一只狼，目标转向一直在场外的Lady。",
    48: "Eddard立刻明白她要以Lady代替Nymeria受罚；Robert厌烦地批准，并让Ser Ilyn执行。",
    49: "Eddard提出抗议。",
    50: "Robert把direwolf称为野兽，断言它终会伤害Sansa，并让Eddard给女儿买一条dog。",
    51: "Sansa这才明白要被杀的是Lady，哭求父亲和king相信Lady没有伤害任何人。",
    52: "Arya也证实Lady当时根本不在现场。",
    53: "Sansa把责任全部推给Nymeria和Arya，以承诺Lady会一直听话来求情。",
    54: "Eddard抱住女儿，再以自己与Robert的友谊和Lyanna的记忆请求他撤回命令。",
    55: "Robert短暂看向Eddard，却最终带着对Cersei的厌恶回避决定。",
    56: "Eddard逼Robert亲自面对裁决，提醒他真正的勇气包括亲手执行自己的判决。",
    57: "Robert仍然离开大厅，把命令及其道德负担留给别人。",
    58: "Cersei立刻询问Lady的位置，Joffrey在旁露出笑容。",
    59: "Ser Barristan明显不愿配合，但仍说明Lady被拴在gatehouse外。",
    60: "Cersei命Ser Ilyn去取狼。",
    61: "Eddard制止他，要求Jory取来自己的greatsword Ice，决定由自己执行。",
    62: "Cersei怀疑他为何要亲自动手。",
    63: "Eddard说Lady属于北方、应该得到比屠夫更好的死亡；Sansa的目光令他像被割伤。",
    64: "Eddard独自陪Lady坐着，想到它确实名副其实：最小、最漂亮、最温顺，也最信任人。",
    65: "Jory把Ice带来。",
    66: "处死Lady后，Eddard命人把尸体送回Winterfell，埋在父亲坟旁。",
    67: "Jory惊讶于要把狼尸运送如此遥远。",
    68: "Eddard坚持如此，因为绝不允许Cersei得到Lady的皮。",
    69: "他准备睡下时，听见Sandor率领的搜索队返回城堡。",
    70: "Sandor说没找到Eddard的女儿，却找到了她的“宠物”，随后把一具裹在血斗篷里的尸体扔到地上。",
    71: "Eddard揭开斗篷，认出Mycah；男孩几乎被从肩到腰劈成两半。",
    72: "Eddard指控Sandor是在追逐中杀死了逃跑的孩子。",
    73: "Sandor承认Mycah逃跑，并以“跑得不够快”的冷笑话结束谈话。",
}

SUMMARIES = [SUMMARY_BY_ORDER[i] for i in range(1, 74)]

KEY_NOTES = {
    1: "开篇省略被找到者的名字，读者与Eddard一样立即知道是Arya；简短报告承接四天搜索的焦虑。",
    5: "Arya从“被找回的女儿”直接变成queen掌控的证人，信息传递顺序本身就是权力争夺。",
    6: "Eddard的父亲愤怒与Hand身份发生冲突；带Sansa不是惩罚，而是因为她是唯一未直接参战的现场证人。",
    7: "他必须把恐惧藏进dignity，表明高位身份并不减少情绪，只规定情绪能否被公开看见。",
    8: "Darry旧日支持Rhaegar，使本来狭小的城堡同时容纳Robert阵营、Lannister势力与战败旧臣的历史紧张。",
    9: "“private and amicable”与挤满旁观者的大厅形成反差；公开场合把家庭纠纷变成王权表演。",
    10: "Joffrey的绷带先于证词出现，视觉上预设他是受害者；Robert的sullen则显示他不愿承担裁决。",
    15: "Eddard先问程序而非立刻辩护，说明他意识到谁控制召集、场地与叙事先后，谁就占优势。",
    17: "Robert说尽快解决看似调停，却也暴露他把复杂事实当成令人厌烦的麻烦。",
    20: "Arya的句子把咬伤放回因果链：Nymeria并非无故攻击，而是在Joffrey伤害Mycah之后介入。",
    23: "Joffrey回避Arya目光是明确动作，可暗示不安，却不能单凭这一点证明整套证词虚假。",
    26: "让双方依次叙述是Robert本章最接近正式审理的做法，但没有追问物证、伤口或Mycah下落。",
    27: "Renly笑的不是受伤本身，而是官方英雄版本与“九岁女孩、扫帚柄、河中宝剑”之间的落差。",
    28: "反复复述把Joffrey最想遮蔽的失面子部分变成大厅共同记忆，也加深叔侄间的敌意。",
    29: "叙事相互冲突后，Robert把真相难题表达成烦躁；裁判者的不耐烦将直接影响弱者能得到多少调查。",
    31: "上一章明确写Sansa在场并作出多项判断；此处“记不得”是拒绝作证。她是出于恐惧、婚约压力还是自我欺骗，文本尚未给出唯一答案。",
    32: "Arya把沉默视为背叛而非中立；姐妹冲突从生活方式差异升级为真相与忠诚之争。",
    35: "Robert的“孩子会打架”通过普遍化降低事件严重性，却掩盖真剑、阶级差异与成人追捕等不对称因素。",
    37: "表面对称的“双边管教”把双方当作同等过错者；它结束争论，却没有查明哪套事实成立。",
    39: "Cersei等到Eddard放松才重新提出狼，把已结束的听证转化为第二轮惩罚谈判。",
    42: "Nymeria逃脱使Robert认为处罚对象不存在；这也解释Cersei为何必须寻找替代目标。",
    45: "Cersei不直接命令Robert，而用king应有的慷慨与父爱刺激其自尊，是典型的间接施压。",
    47: "“We have a wolf”中的we把无辜Lady变成可供王权支配的替代物；平静语气比喊叫更具威胁。",
    48: "Robert知道Lady不是涉事者仍批准处死；裁决从事实判断转为以可得目标满足报复。",
    50: "把direwolf改称dog看似提供安慰，实则否定Stark孩子与狼之间不可替换的关系。",
    51: "Sansa第一次在公开场合让礼仪完全崩塌，因为现实终于直接摧毁她最温顺、最无辜的同伴。",
    52: "Arya为Lady作证非常关键：姐妹刚刚互殴，她仍明确区分事实与私人愤怒。",
    53: "Sansa为了救Lady转而指责Arya和Nymeria，显示恐惧如何迫使受压者争夺谁来承担惩罚。",
    54: "Eddard同时诉诸私人友谊与Lyanna记忆，试图把Robert从king重新唤回曾经的朋友。",
    55: "Robert对Cersei的loathing不是反抗；他以离开表达厌恶，却仍让她得到想要的结果。",
    56: "Eddard用自己在Chapter 1阐明的原则反问Robert：下判决者应亲自挥剑，不能把死亡变成抽象命令。",
    57: "空洞沉默强化权力责任的缺席：king的身体离场，king的命令仍然有效。",
    58: "Joffrey的笑容把Lady之死从法律必要变成私人满足的迹象，但文本没有让他亲口说明动机。",
    61: "Eddard无法救Lady，便争取由信任她的人执行；这是有限处境中的最后一点尊严控制。",
    63: "“butcher”既指职业行刑者，也残酷呼应Mycah的身份；Eddard此时尚不知道男孩已经死亡。",
    64: "Lady最信任人的品质此刻成为悲剧核心：它不会反抗Eddard，也无法理解主人为何带来死亡。",
    66: "送回Winterfell把Lady从王后想要的战利品重新变成Stark家庭成员，并让死亡回归北方墓地秩序。",
    68: "Eddard救不了生命，却能拒绝尸体被剥皮展示；这是对Cersei报复逻辑的最后抵抗。",
    70: "Sandor把Mycah称作Arya的pet，与成年人此前把direwolves动物化的语言呼应，进一步抹去男孩的人格。",
    71: "Mycah的伤势与“活捉失踪孩子”的搜索任务完全不相称；尸体使Robert所谓没有lasting harm成为尖锐反讽。",
    72: "Eddard的质问把被动的“找到尸体”还原为主动追杀；他没有接受Sandor的委婉说法。",
    73: "“not very fast”用速度差把杀死逃跑孩子包装成猎场笑话；笑声显示Sandor拒绝表现悔意。",
}

STAGES = [
    (1, 18, "Arya被找到后，Lannister一方抢先把她带入公开大厅；Eddard在父亲身份与Hand尊严之间进入一场已被布置好的听证。"),
    (19, 38, "Arya与Joffrey给出冲突版本，Sansa拒绝作证；Robert以双方管教的表面对称结束调查，却没有确认真相。"),
    (39, 57, "Cersei把逃脱的Nymeria换成无辜Lady作为处罚对象；Robert在明知替代关系的情况下批准并逃避亲自执行。"),
    (58, 68, "Eddard无法撤销命令，只能亲自给Lady一个尽量有尊严的死亡，并安排尸体回到Winterfell。"),
    (69, 73, "Sandor带回Mycah被劈开的尸体；孩子争执背后真正不可逆的成人暴力在章末才被揭开。"),
]

BACKGROUNDS = {
    8: "**历史背景：** House Darry曾支持Targaryen；Ser Raymun的兄长们在Trident为Rhaegar而死。当前接待Robert阵营带有战败旧臣的压力。",
    15: "**文本事实：** Jaime和Sandor仍带人在Trident北岸搜索Arya；这解释他们没有出现在大厅。",
    23: "**事实／推测：** 文本明确Joffrey不肯看Arya；把这理解为心虚是合理阅读，但不能仅据此完成事实判定。",
    31: "**前文事实：** Sansa亲眼见到冲突，也曾判断Mycah说的是实话。她此刻为何拒绝作证，只能从婚约、恐惧和理想化压力作推测。",
    41: "**文本事实：** Stark与王室人员都没有在河两岸找到Nymeria；它当前下落不明。",
    47: "**指代：** Cersei说的另一只wolf是Sansa的Lady。Lady没有出现在河边冲突中。",
    48: "**裁决：** Robert授权以Lady替代失踪的Nymeria受死，并最初把执行交给King’s Justice Ser Ilyn Payne。",
    61: "**武器：** Ice是House Stark世代相传的Valyrian steel greatsword，也是Eddard执行正式死刑时使用的剑。",
    66: "**北方习俗：** Eddard要求把Lady运回Winterfell、葬在父亲坟旁；这是家族归属和尊严安排，不是普通猎物处理。",
    71: "**文本事实：** Mycah已死亡，伤口几乎从肩劈到腰；这一伤势来自大型利器。",
    73: "**事实／推断：** Sandor承认Mycah逃跑而自己追上了他，并以笑话回应死亡。结合尸体与Eddard质问，文本强烈指向Sandor杀死Mycah。",
}

EXTRA_VOCAB = [
    ("appropriate", "/əˈproʊprieɪt/", "v.", "擅自占有；挪作己用", "appropriate the castle"),
    ("amicably", "/ˈæmɪkəbli/", "adv.", "友好地；和睦地", "settle a dispute amicably"),
    ("sullen", "/ˈsʌlən/", "adj.", "闷闷不乐而阴沉的", "Robert的神情"),
    ("savaged", "/ˈsævɪdʒd/", "v.", "被野兽凶猛撕咬", "Cersei对狼咬的定性"),
    ("bristle", "/ˈbrɪsəl/", "v.", "发怒；像毛竖起般戒备", "at an accusation"),
    ("stifle", "/ˈstaɪfəl/", "v.", "强忍；抑制", "stifle laughter"),
    ("guffaw", "/ɡəˈfɔː/", "n./v.", "响亮粗放的大笑", "Renly失控发笑"),
    ("pummel", "/ˈpʌməl/", "v.", "连续重击", "用拳头打人"),
    ("discipline", "/ˈdɪsəplɪn/", "v./n.", "管教；纪律处分", "discipline a child"),
    ("lasting harm", "/ˈlæstɪŋ hɑːrm/", "phr.", "持久、不可逆的伤害", "Robert的判断"),
    ("pelt", "/pelt/", "n.", "兽皮；带毛皮张", "direwolf pelt"),
    ("niggardly", "/ˈnɪɡərdli/", "adj.", "吝啬的；小气的", "古词，与种族词无关"),
    ("disengage", "/ˌdɪsɪnˈɡeɪdʒ/", "v.", "抽身；解除接触", "避开目光或拥抱"),
    ("bile", "/baɪl/", "n.", "胆汁；比喻苦涩怒意", "bile rising in the throat"),
    ("loathing", "/ˈloʊðɪŋ/", "n.", "强烈憎恶", "Robert看Cersei"),
    ("reluctant", "/rɪˈlʌktənt/", "adj.", "不情愿的；勉强的", "Ser Barristan的反应"),
    ("gatehouse", "/ˈɡeɪthaʊs/", "n.", "城门楼", "Lady被拴住的位置"),
    ("headsman", "/ˈhedzmən/", "n.", "刽子手；斩首执行人", "King’s Justice"),
    ("cleave", "/kliːv/", "v.", "劈开；砍裂", "Mycah的致命伤"),
    ("ride down", "/raɪd daʊn/", "phr.v.", "骑马追上并撞倒或杀死", "Eddard对Sandor的指控"),
]
VOCAB = BASE_VOCAB + EXTRA_VOCAB


def main():
    blocks = extract_range(145, 151, "EDDARD", "CH16")
    write_chapter(
        out=OUT, chapter=16, pov="EDDARD", page_start=145, page_end=151,
        blocks=blocks, summaries=SUMMARIES, key_notes=KEY_NOTES, stages=STAGES,
        backgrounds=BACKGROUNDS,
        default_background="本段没有新增必须补充的世界观设定；重点在证词冲突、公开权力、父亲责任、替代性惩罚或成人暴力如何扩大孩子争执。",
        vocab=VOCAB,
        guide="Arya失踪四天后被Jory找到，却被Lannister一方直接带入Robert主持的公开听证。Arya与Joffrey给出相反证词，唯一完整旁观者Sansa拒绝说明事实，Robert便以双方各自管教结束争议。Cersei随即把逃脱的Nymeria换成无辜Lady作为惩罚对象；Robert明知Lady没有涉事仍批准处死，又拒绝亲自承担判决。Eddard只能亲手给予Lady尽量有尊严的死亡。章末Sandor带回Mycah尸体，使先前所谓“没有持久伤害”的判断显得残酷而荒谬。",
        people=[
            ("Eddard Stark", "本章视角人物；以父亲、Hand与执行判决者三重身份面对王室压力"),
            ("Arya Stark", "被找到后讲述河边冲突，指控Joffrey伤害Mycah"),
            ("Sansa Stark", "完整目击者，却在妹妹和未婚夫之间拒绝作证；Lady的主人"),
            ("Robert Baratheon", "主持听证并批准处死Lady，却回避亲自执行裁决"),
            ("Cersei Lannister", "推动对Arya和direwolf的惩罚，并将报复目标转向Lady"),
            ("Joffrey Baratheon", "受伤一方，提供与Arya冲突的证词"),
            ("Lady / Nymeria", "分别是Sansa与Arya的direwolves；前者无辜被杀，后者仍下落不明"),
            ("Mycah", "butcher’s boy与Arya的朋友，章末被Sandor带回时已经死亡"),
            ("Sandor Clegane", "搜索队领队之一，带回Mycah尸体并以冷酷笑话回应Eddard"),
            ("Renly Baratheon", "Robert的弟弟，以大笑拆穿Joffrey叙述中的失面子部分"),
        ],
        terms=[
            ("House Darry", "曾效忠Targaryen的河间地贵族家族，本章城堡主人"),
            ("King’s Justice", "王室死刑执行官，当前由Ser Ilyn Payne担任"),
            ("Ice", "House Stark的Valyrian steel ancestral greatsword"),
            ("gold dragon", "王国高面额金币；Cersei以一百枚悬赏Nymeria兽皮"),
            ("Trident", "Arya失踪及搜索发生的河流，也是Robert叛乱决定性战场"),
        ],
        synthesis="Chapter 16把“谁说了真话”扩展成“谁有能力让自己的版本变成判决”。Arya与Joffrey的证词并不对称：Sansa拥有关键见闻，却因婚约、恐惧和家庭忠诚的拉扯选择不说；Robert又因厌烦拒绝继续调查。于是Cersei无需证明Nymeria有罪，只需找到一只能被控制的wolf。Lady之死因此不是误认，而是明知无辜仍接受的替代性惩罚。Eddard坚持亲手挥Ice并不能使决定正义，却让判决者与死亡重新发生道德接触。章末Mycah的尸体揭示更大的不对称：贵族孩子争执被讨论、包扎和管教，低阶级孩子却在没有听证的情况下被成人骑士杀死。",
        contrasts=[
            "**私下和解／公开审判：** 原本可由两家父亲处理的争执，被满厅观众与王后先手变成权力表演。",
            "**两套证词／一个沉默证人：** Arya和Joffrey互相否认，Sansa的拒绝使事实空位被权力填补。",
            "**Nymeria／Lady：** 真正咬人的狼逃脱，无辜而温顺的狼因可被掌控而代受惩罚。",
            "**下令／挥剑：** Robert保留king的裁决权，却把执行及其情感代价交给Eddard。",
            "**贵族伤疤／Mycah之死：** Joffrey可能留下疤痕得到公开审理，Mycah的尸体只在章末作为搜索战利品出现。",
            "**Lady的信任／Sandor的笑声：** 一端是无辜动物对人的完全信任，另一端是成人对被杀孩子的彻底去人格化。",
        ],
        questions=[
            "Sansa拒绝作证会怎样影响她与Arya、Eddard和Lady记忆之间的关系？",
            "Nymeria现在在哪里，是否还能回到Arya身边？",
            "Mycah的死亡是否会被正式调查或追责？",
            "Robert与Eddard对‘下判决者应亲自挥剑’的分歧会如何影响两人的合作？",
        ],
        extraction_notes="提取器正确保留PDF pp.145–146和147–148的2个跨页段落",
    )
    print(f"Wrote Chapter 16 with {len(blocks)} paragraphs")


if __name__ == "__main__":
    main()
