#!/usr/bin/env python3
"""Build Chapter 69 (TYRION) close-reading Markdown."""
from pathlib import Path

from agot_extract import extract_range
from agot_reader_common import write_chapter
from build_agot_chapter68_reader import VOCAB as BASE_VOCAB

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs" / "AGOT_逐章精读"

SUMMARIES = [
    "Tywin以‘他们抓住了我的儿子’开场，整场军议被Jaime被俘笼罩。",
    "筋疲力尽、负伤的Crakehall信使确认消息。",
    "Tyrion心想应是‘你的一个儿子’，显出Tywin心中Jaime与自己的地位差；他也承认自己关心Jaime，却庆幸没有同陷Whispering Wood。",
    "captains和bannermen沉默听报，空旷旅店里只剩炉火声。",
    "Tywin军队急行南下付出伤亡、掉队和逃兵代价；Tyrion厌恶重返这家承载旧事的inn。",
    "Tyrion原与Shae休息，却被Riverrun噩耗唤醒；强行军仍未赶在Robb之前。",
    "Harys Swyft把失败归咎于Jaime将围军分成三营。",
    "Tyrion在心中维护Jaime，并鄙视靠姻亲攀附Lannister的Swyft。",
    "Kevan用两河汇流、sluice gates和三角地形说明Riverrun必须由三营分别封锁。",
    "信使确认有palisades也无济于事：北营无预警遭袭，Jaime此前被假情报和诱饵引走。",
    "Gregor追问outriders为何没有示警。",
    "信使说斥候不断失踪，归来者也一无所见。",
    "Gregor以挖眼威胁把侦察失败归结为恐怖惩罚。",
    "Tywin观察Gregor却不表态；异常沉默与未碰的wine暴露紧张。",
    "Kevan催信使继续讲夜袭经过。",
    "Blackfish清除sentries和palisades后突袭北营；西营渡河救援又遭水流、投石机与Stark伏兵夹击。",
    "Flement Brax听到父亲命运，难以置信地发问。",
    "信使确认Lord Brax穿plate-and-mail落水身亡，并称其gallant。",
    "Tyrion拒绝把穿重甲夜渡急流称作勇敢，认为这种gallantry只是愚蠢。",
    "西方两路Stark骑兵攻入河间营地，Robb与direwolf领军；Tytos Blackwood又从Riverrun出击夹后。",
    "Lefford只能以一句祈祷回应灾情。",
    "Greatjon烧毁siege towers，Edmure等俘虏获救；南营有序撤退，但Tyroshi佣兵倒戈。",
    "Kevan说自己早警告Jaime不要信任只忠于钱袋的sellsword。",
    "Tywin仍像面具般静止，但光头上的汗珠泄露压力。",
    "Swyft再次哀叹Jaime被俘、围城失败是catastrophe。",
    "Addam讥讽Swyft只会重复显而易见的问题，要求讨论对策。",
    "Swyft认为补给线被截、Casterly Rock受威胁，主张求和。",
    "Tyrion摔碎wine cup，把破杯比作Joffrey处决Eddard后再也拼不回的和平。",
    "Addam认为两次战斗尚不能决定战争，仍愿与Robb交锋。",
    "Lefford提议停战并交换俘虏。",
    "Tyrion指出双方俘虏价值与数量不对等，Eddard已死更使Jaime无法交换。",
    "Lefford把Cersei掌握Sansa和Arya视作可能筹码。",
    "Addam认为用两名女孩换Jaime极不划算，暴露贵族战争中的性别价值判断。",
    "Lefford转而主张不惜代价赎回Jaime。",
    "Tyrion讽刺Stark若缺gold，大可熔掉Jaime盔甲，说明赎金未必能买回战略人质。",
    "Addam担心求和示弱，主张立即进军；原文此处保留小写开头与姓名拼写异常。",
    "Swyft建议向court求援，并回Casterly Rock另征新军。",
    "Tywin再次说‘他们抓住了我的儿子’，用一句命令结束嘈杂军议。",
    "众人离去时Tywin单独留下Tyrion和Kevan。",
    "Tyrion惊讶坐回，向取酒的Kevan开口。",
    "Tywin把自己一口未饮的wine递给Tyrion。",
    "这罕见举动让Tyrion真正不知所措，只能喝下。",
    "Tywin承认Tyrion判断正确：活着的Eddard本可换来时间，处决他是rank madness。",
    "Tyrion以Joffrey年幼、自己年轻时也犯错为其辩护。",
    "Tywin以Tyrion早年婚姻创伤反刺，表明并无温情宽容。",
    "Tyrion想把杯子砸向Tywin，却只继续喝酒。",
    "Tywin说局势比表面更坏，因为又出现一位king。",
    "Kevan误以为Joffrey出事，惊问新王是谁。",
    "Tywin说明Renly已娶Margaery Tyrell、称王，并得到Tyrell家宣誓效忠。",
    "Kevan意识到这是grave tidings。",
    "Cersei命令Tywin军回King’s Landing防守；Tywin尤其不满女儿以king and council名义命令自己。",
    "Tyrion带黑色幽默询问Joffrey如何反应。",
    "Tywin说Cersei尚未告诉Joffrey，怕他冲动亲征Renly。",
    "Tyrion追问Joffrey能带哪支army，并反对交出当前主力。",
    "Tywin说Joffrey想亲率City Watch。",
    "Kevan指出带走Watch会使首都空虚，Dragonstone的Stannis也构成威胁。",
    "Tywin讽刺真正适合穿motley的不是Tyrion而是Joffrey。",
    "Tyrion把这当近似赞美，并追问作为兄长的Stannis如何看Renly称王。",
    "Tywin认为Stannis最危险，却只有造船、招佣兵和请shadowbinder等未证实whispers，意图不明。",
    "地图显示Lannister军四面受敌：Bolton、Robb、Brotherhood、Arryns、Stannis、Highgarden与Storm’s End形成包围。",
    "Tyrion以Rhaegar仍然死着开冷笑话，暗示至少没有更多王位竞争者。",
    "Tywin要求Tyrion贡献策略而非japes。",
    "Kevan判断Robb与riverlords合流后或已兵力占优，他们还可能被三军夹击。",
    "Tywin决定次日去Harrenhal，先处理Robb；并命Addam的outriders掩护行军，避免再度失踪。",
    "Kevan询问为何选择被传诅咒的Harrenhal。",
    "Tywin不理诅咒，命Gregor、Vargo Hoat和Amory Lorch带骑兵烧遍riverlands。",
    "Kevan接受命令并离开传令。",
    "[内容省略：涉及授权性暴力与劫掠。段落位置保留。] Tywin还想把Tyrion的clansmen编入Vargo队伍。",
    "Tyrion说Shagga和Timett天生会劫掠，却坚持把这些属于自己的、不文明但可信的部下留在身边。",
    "Tywin要求他学会约束clansmen，因为不准他们劫掠即将前往的city。",
    "Tyrion不明白所指是哪座city。",
    "Tywin揭晓要把Tyrion派往King’s Landing的court。",
    "这个任命完全超出Tyrion预料。",
    "Tyrion饮酒思考后询问自己的职责。",
    "Tywin只用一个词回答：Rule；原文缺句末标点，按源页保留。",
    "Tyrion大笑，指出Cersei绝不会轻易让权。",
    "Tywin要Tyrion约束Joffrey、审查council，并批评封Janos Slynt为lord及罢免Barristan Selmy损害王权体面。",
    "Tyrion用‘spikes、heads、walls’概括若councillors背叛时Tywin期待的处置。",
    "Tywin认为Tyrion已学会自己的手段。",
    "Tyrion既暗自高兴又怀疑自己像战场左翼一样只是危险任务的消耗品，于是追问为何选他。",
    "Tywin突然回答：You are my son。",
    "Tyrion却把这句话理解为Tywin已放弃Jaime，自己只是仅剩选择；强烈愤怒仍被压在沉默中。",
    "Tywin踩过碎杯离开，并禁止Tyrion带Shae去court。",
    "Tyrion独坐后回到低矮garret；窗外被Tywin吊死的innkeep如同破败的Lannister hopes。",
    "Shae醒来，以亲密方式回应Tyrion。",
    "Tyrion决定违抗父命，把Shae带去King’s Landing。",
]

KEY_NOTES = {
    1: "开头‘my son’没有说Jaime；Tyrion下一段的心理补词揭开Tywin家庭情感排序。源文缺开引号，校勘时不擅自补写。",
    3: "One of your sons不是口头反抗，而是沉默的内心修正；Tyrion习惯把受伤隐藏在讥讽里。",
    5: "同一inn曾是Catelyn扣押Tyrion之处，如今innkeep被Tywin吊死；地点把私人旧怨与战争报复叠加。",
    9: "三营不是Jaime随意分兵，而是Riverrun水利地形强迫围城者作出的结构性选择。",
    13: "Gregor用递增的四眼、六眼制造黑色恐怖；惩罚无法补救情报体系本身的失败。",
    14: "Tywin的face如mask，但sweat和untouched wine成为身体层面的反证。",
    16: "信使从败军视角重述此前Catelyn章节中的计划，读者现在看见同一行动如何摧毁对方组织。",
    18: "messenger用gallant维护死者荣誉，Tyrion下一段却拆解贵族美化死亡的词汇。",
    24: "mask/sweat对比再次说明Tywin的控制并非无情，而是拒绝让情绪成为公开信息。",
    28: "摔碎cup把抽象的peace变成不可复原的物件；碎片在结尾还会再次出现。",
    33: "Addam衡量的是dynastic and military value，不是Sansa、Arya的人格价值；文本借此呈现战争交换的性别结构。",
    36: "源PDF写作小写‘if’及‘Addarn’，本文件保留并标为源页异常，不静默改写。",
    38: "重复开场句压过babble；Tywin不是被说服，而是决定从公开讨论转入私下决策。",
    41: "Tywin把未饮wine递给Tyrion是一种罕见的亲近或实用信任信号，所以比正式称赞更令他惊讶。",
    43: "Tywin承认Eddard作为活人质的价值，说明Joffrey的处决同时摧毁外交选择与Lannister leverage。",
    45: "Tywin用Tyrion旧婚姻羞辱回应‘boyish follies’，把Joffrey的国家级错误与儿子的私人创伤强行并列。",
    49: "Renly称王不是孤立宣言：与Margaery婚姻把Tyrell资源接入王位主张。",
    53: "Cersei隐瞒消息说明她也知道Joffrey冲动难控；形式上的king与实际信息控制发生分离。",
    57: "motley本属fool服饰；Tywin罕见地承认Tyrion比Joffrey更有判断力，但仍用讽刺表达。",
    59: "Stannis消息全由Varys whispers转述，造船等不能在当前段落当作已完全证实的事实。",
    60: "地图把失败从一场battle扩大为战略包围：补给、撤退、侧后和首都威胁同时存在。",
    64: "Harrenhal选择优先考虑中央位置与巨大防御潜力；curse是Kevan的文化解释，不是已证实因果。",
    66: "Tywin的riverlands order是scorched-earth与terror strategy：不只打军队，也破坏敌方供给和政治秩序。",
    68: "原段对性暴力和全面劫掠作明确授权，故不复录；这不是普通foraging，而是有意识地放任战争暴行。",
    69: "Tyrion保留clansmen既因信任，也因这些人是少数直接依附他个人而非Tywin家主权威的力量。",
    72: "court不是休闲宫廷，而是King’s Landing的权力中枢；上一句‘不准劫掠city’已暗示任务对象。",
    75: "Rule单词极短，重量却最大：Tywin授予职责而未给正式头衔，权力边界天然会与Cersei冲突。",
    77: "Tywin批评Slynt和Selmy不是道德洁癖，而是封赏秩序与symbolic legitimacy：王权不能让职位失去含金量。",
    78: "Tyrion的三个名词已内化Tywin以公开处决制造服从的政治语言。",
    80: "hold the left回忆说明任命也可能是另一场把Tyrion放在最危险位置的考验。",
    81: "You are my son表面是Tyrion渴望的承认；其突然、冷硬和危局语境又使它可能只是血统义务。",
    82: "Tyrion的解释不等于Tywin已明说放弃Jaime，但开头my son与此处任命使这种推断非常有文本依据。",
    83: "碎杯在Tywin脚下crunch，视觉上把他走过自己家族造成的broken peace。",
    84: "innkeep尸体与Lannister hopes明喻把Tywin暴力后果、军局衰败和地点记忆合成一个结尾意象。",
    86: "Tyrion刚得到统治使命便决定违反父亲的私人禁令；自主性与判断风险同时开始。",
}

STAGES = [
    (1, 23, "Tywin军议听取Riverrun败报；Kevan解释地形，信使复盘Blackfish夜袭、三营覆灭与Jaime军瓦解。"),
    (24, 38, "将领讨论求和、换俘和再战；Tyrion以碎杯指出Eddard之死已破坏和平，Tywin解散公开军议。"),
    (39, 60, "Tywin私留Kevan和Tyrion，承认Joffrey犯下madness，并揭示Renly称王、Cersei失控及Lannister四面受敌。"),
    (61, 72, "Tywin决定转往Harrenhal并以reavers焚毁riverlands，随后揭晓Tyrion将被派往King’s Landing。"),
    (73, 86, "Tyrion受命Rule、约束Joffrey与council；‘You are my son’引发复杂解读，结尾他决定带Shae同行。"),
]

BACKGROUNDS = {
    5: "**the inn：** 这是Catelyn此前扣押Tyrion的crossroads inn；Tywin后来以报复性命令处死innkeep。",
    9: "**Riverrun：** Tully seat位于Tumblestone与Red Fork汇流尖端，可开sluice gates把第三面变为moat。",
    16: "**Blackfish：** Brynden Tully，Robb的重要侦察与先锋指挥者；本次夜袭利用情报欺骗和河流隔离。",
    20: "**Riverrun sortie：** 城内Tytos Blackwood在围军迎击Stark骑兵时出城夹后，形成内外合击。",
    22: "**sellsword：** 为报酬作战的职业兵；Tyroshi首领在战局变化时倒戈，体现契约忠诚的不稳定。",
    28: "**broken peace：** Joffrey处决Eddard后，Lannister失去最重要的谈判人质，也把冲突升级为血仇。",
    49: "**Renly–Tyrell alliance：** Renly与Margaery婚姻把Baratheon claim和Highgarden的军粮、人力及贵族网络结合。",
    56: "**City Watch：** King’s Landing治安与城防力量；若被Joffrey带出，首都会直接失去关键守备。",
    59: "**shadowbinder：** 与Asshai神秘传统相关的称呼；此处只是Varys渠道的传闻，真实性尚未确认。",
    60: "**strategic enclosure：** Lannister军被北、西、东、南多方势力牵制，并失去向西安全退回Lannisport的通道。",
    64: "**Harrenhal：** Gods Eye附近的巨大城堡，民间称受诅咒；当前选择首先有军事与交通意义。",
    66: "**reavers：** 以袭掠、纵火和恐吓为任务的骑兵；Tywin让多个残酷指挥官系统性破坏riverlands。",
    68: "**内容安全：** 原段明确授权劫掠与性暴力，不复录；保留这是Tywin主动战争政策而非失控个案。",
    72: "**court mission：** Tyrion将进入King’s Landing权力中心，任务是代表Tywin纠正Joffrey、Cersei和council。",
    77: "**legitimacy symbols：** Harrenhal封爵、Kingsguard声望与sigil都向realm传递统治秩序；Tywin认为错误任免会贬值王权。",
    81: "**没有正式头衔：** Tywin说Rule，却未在本段说明具体官职，因此Tyrion的法定权限仍待明确。",
}

EXTRA_VOCAB = [
    ("relentless", "/rɪˈlentləs/", "adj.", "持续而无情的", "relentless drive"),
    ("grueling", "/ˈɡruːəlɪŋ/", "adj.", "极其艰苦的", "grueling pace"),
    ("take its toll", "/teɪk ɪts toʊl/", "phr.", "造成伤亡或损耗", "march"),
    ("lickspittle", "/ˈlɪkˌspɪtl/", "n.", "卑躬屈膝的马屁精", "Swyft"),
    ("sluice gate", "/sluːs ɡeɪt/", "n.", "水闸门", "Riverrun"),
    ("besieger", "/bɪˈsiːdʒər/", "n.", "围城者", "three camps"),
    ("palisade", "/ˌpælɪˈseɪd/", "n.", "木桩防御栅栏", "camp defense"),
    ("sentry", "/ˈsentri/", "n.", "哨兵", "night assault"),
    ("kindling", "/ˈkɪndlɪŋ/", "n.", "引火柴；碎木", "raft smashed to kindling"),
    ("sortie", "/ˈsɔːrti/", "n.", "守军出城突击", "Tully sortie"),
    ("tabard", "/ˈtæbərd/", "n.", "罩在甲胄外的纹章短袍", "silver-and-purple tabard"),
    ("gallantry", "/ˈɡæləntri/", "n.", "英勇行为；骑士式勇气", "Brax"),
    ("overrun", "/ˌoʊvərˈrʌn/", "v.", "攻占；席卷", "camp"),
    ("make off with", "/meɪk ɔːf wɪð/", "phr.", "带走；夺走", "captives"),
    ("catastrophe", "/kəˈtæstrəfi/", "n.", "灾难性失败", "siege broken"),
    ("sue for peace", "/suː fər piːs/", "phr.", "请求议和", "Swyft"),
    ("truce", "/truːs/", "n.", "停战协议", "exchange prisoners"),
    ("ransom", "/ˈrænsəm/", "v./n.", "赎回；赎金", "Jaime"),
    ("nonplussed", "/ˌnɑːnˈplʌst/", "adj.", "困惑得不知所措", "Tyrion"),
    ("rank madness", "/ræŋk ˈmædnəs/", "phr.", "彻头彻尾的疯狂", "Eddard execution"),
    ("folly", "/ˈfɑːli/", "n.", "愚蠢行为", "Joffrey"),
    ("fortnight", "/ˈfɔːrtnaɪt/", "n.", "两星期", "Renly marriage"),
    ("grave tidings", "/ɡreɪv ˈtaɪdɪŋz/", "phr.", "严重的消息", "Kevan"),
    ("bend the knee", "/bend ðə niː/", "phr.", "屈膝宣誓效忠", "Tyrells"),
    ("poleaxed", "/ˈpoʊlækst/", "adj.", "震惊得目瞪口呆", "Kevan"),
    ("motley", "/ˈmɑːtli/", "n.", "宫廷弄臣的杂色服", "made for motley"),
    ("shadowbinder", "/ˈʃædoʊˌbaɪndər/", "n.", "缚影士；神秘术士称号", "Asshai"),
    ("foraging party", "/ˈfɔːrɪdʒɪŋ ˈpɑːrti/", "n.", "征集粮草的小队", "harried patrols"),
    ("screen", "/skriːn/", "v.", "掩护并遮蔽军事行动", "screen movements"),
    ("reaver", "/ˈriːvər/", "n.", "袭掠者", "Gregor's riders"),
    ("rapine", "/ˈræpɪn/", "n.", "战争中的暴力掠夺", "Tywin's order"),
    ("relish", "/ˈrelɪʃ/", "v.", "以……为乐；享受", "relish pillage"),
    ("plunder", "/ˈplʌndər/", "v.", "劫掠", "the city"),
    ("jackanapes", "/ˈdʒækəneɪps/", "n.", "无礼自负的蠢人（古风辱称）", "council"),
    ("venerable", "/ˈvenərəbəl/", "adj.", "德高望重的；年高可敬的", "Grand Maester"),
    ("curb", "/kɜːrb/", "v.", "约束；控制", "curb the boy"),
    ("sigil", "/ˈsɪdʒəl/", "n.", "纹章标志", "bloody spear"),
    ("cleaver", "/ˈkliːvər/", "n.", "砍肉刀", "butcher imagery"),
    ("jape", "/dʒeɪp/", "n.", "玩笑；戏谑", "Tyrion"),
    ("garret", "/ˈɡærət/", "n.", "顶楼小阁间", "bell tower"),
    ("gibbet", "/ˈdʒɪbɪt/", "n.", "绞刑架", "inn yard"),
]
VOCAB = BASE_VOCAB + EXTRA_VOCAB


def extract_blocks():
    blocks = extract_range(692, 700, "TYRION", "CH69")
    blocks[67]["text"] = "[Content omitted: authorization of sexual violence and pillage. Paragraph position preserved.]"
    return blocks


def main():
    blocks = extract_blocks()
    write_chapter(
        out=OUT,
        chapter=69,
        pov="TYRION",
        page_start=692,
        page_end=700,
        blocks=blocks,
        summaries=SUMMARIES,
        key_notes=KEY_NOTES,
        stages=STAGES,
        backgrounds=BACKGROUNDS,
        default_background="本段没有新增必须展开的设定；重点在Riverrun败局、Lannister战略包围、Tywin的统治方式及Tyrion对父子关系的解读。",
        vocab=VOCAB,
        guide="Tywin在crossroads inn听取Riverrun败报。Jaime被Blackfish的诱敌与夜袭击败并被俘，三座围城营地又因河流彼此隔绝而先后崩溃。公开军议中，Tyrion以摔碎wine cup说明Joffrey处决Eddard已让和平无法复原。Tywin随后只留下Kevan和Tyrion，透露Renly与Margaery结盟称王、Cersei无法控制Joffrey、Stannis动向不明，而Lannister主力已在地图上四面受敌。他决定转往Harrenhal，并派Gregor、Vargo Hoat和Amory Lorch焚毁riverlands。随后Tywin出人意料地派Tyrion到King’s Landing‘Rule’，要求他约束Joffrey、Cersei和council。一句‘You are my son’既像承认，也让Tyrion认定父亲已把Jaime视为失去、自己只是剩余选择。Tywin最后禁止Shae同行，Tyrion当晚便决定违抗。",
        people=[
            ("Tyrion Lannister", "本章视角；分析败局、被派往King’s Landing统治，并决定带Shae同行"),
            ("Lord Tywin Lannister", "面对Jaime被俘与多线危机，制定Harrenhal、riverlands恐怖战和court干预方案"),
            ("Ser Kevan Lannister", "解释Riverrun地形、参与私下战略讨论并执行Tywin命令"),
            ("Ser Jaime Lannister", "未在场；被俘使Lannister军事与家庭秩序同时震动"),
            ("Robb Stark / Blackfish", "以诱敌、侦察封锁、夜袭和城内外协同解救Riverrun"),
            ("Joffrey Baratheon", "处决Eddard破坏和平，冲动统治令Tywin决定派Tyrion约束"),
            ("Cersei Lannister", "控制Joffrey信息并命Tywin回师，将与Tyrion在court形成权力冲突"),
            ("Renly Baratheon / Margaery Tyrell", "通过婚姻联盟提出新的王位主张"),
            ("Shae", "Tyrion的亲密伴侣；Tywin禁止她入court，Tyrion决定带她同行"),
        ],
        terms=[
            ("Riverrun triangle", "两河加人工moat构成的三面水障，使围城军必须分驻三营"),
            ("broken cup", "Eddard被处决后和平不可复原的物质象征"),
            ("scorched-earth strategy", "通过纵火、劫掠和恐怖破坏riverlands资源与秩序"),
            ("Rule", "Tywin给Tyrion的任务核心，但本段未给出明确正式职衔"),
            ("symbolic legitimacy", "封爵、Kingsguard名声和纹章等对王权可信度的公共影响"),
        ],
        synthesis="Chapter 69先拆掉一个简单解释：Jaime不是因为愚蠢地分成三营才败。Riverrun的河流与水闸迫使besieger分营，Blackfish则通过消灭outriders、制造假目标、夜袭和城内sortie把结构弱点转成灾难。败报中的‘gallantry’也被Tyrion重新命名为foolishness，说明他比传统骑士叙事更关心行动后果。军议同样从表面方案走向不可逆事实：求和、换俘、赎金都受Eddard已死制约。Tyrion摔碎的杯子因此不是表演性愤怒，而是一个战略模型——Joffrey毁掉了原本能盛装和平的容器。Tywin随后表现出两套统治。对riverlands，他授权Gregor等人以火与恐怖破坏敌方社会；对King’s Landing，他又高度重视封爵、Barristan名声和council秩序，因为暴力必须服务于可识别的权威等级。Tyrion被选中正因他能理解这两面。他知道spikes、heads、walls，也理解人质、联盟、供给和symbolic legitimacy。然而父子关系让任命无法成为纯粹荣誉。Tywin从开头的my son到结尾的You are my son，似乎终于承认Tyrion；Tyrion却读成Jaime被放弃后的替补通知。文本没有替读者裁决Tywin内心，只让untouched wine、私人留席、尖刻旧伤和冷硬任命同时存在。最终，Tyrion对Shae的决定显示他接受了公共权力，却拒绝父亲完全控制私人生活；这种反抗也把新的风险带进court。",
        contrasts=[
            "**my son／one of your sons：** Tywin语言把Jaime当作中心，Tyrion的内心修正揭示被排除感。",
            "**mask／sweat and untouched wine：** 公共自控与身体泄露的焦虑并存。",
            "**gallantry／foolishness：** 贵族荣誉修辞与Tyrion的结果导向判断冲突。",
            "**peace proposal／broken cup：** 抽象外交愿望对上已经不可撤销的处决。",
            "**curse／strategic position：** Kevan用传说看Harrenhal，Tywin用军事用途看它。",
            "**terror in riverlands／order in the capital：** Tywin在敌区放任破坏，在统治中心强调纪律与体面。",
            "**You are my son／all you have left：** 同一句话可被听成承认，也可被听成替补。",
            "**public obedience／private defiance：** Tyrion接受任务，却立即决定在Shae问题上抗命。",
        ],
        questions=[
            "Tywin授予Tyrion的实际职权和正式身份究竟是什么？",
            "Tyrion能否同时约束Joffrey、Cersei和现有council？",
            "Stannis的造船、sellswords和shadowbinder传闻有多少真实成分？",
            "转往Harrenhal能否避免Lannister军被Robb、Bolton与南方诸侯夹击？",
            "把Shae带入King’s Landing会如何影响Tyrion的任务与弱点？",
        ],
        extraction_notes="PDF pp.692–700校勘后共86段，无跳段或重复。2处真实跨页续段：pp.692–693、696–697。第68段明确授权性暴力与全面劫掠，使用稳定占位符并保留其政策意义。p.692首段缺开引号、p.696一段以小写‘if’开头且‘Addarn’疑为源页拼写、p.699‘Rule’句缺句末标点，均按PDF原文保留并注明。",
    )
    print(f"Wrote Chapter 69 with {len(blocks)} paragraphs")


if __name__ == "__main__":
    main()
