#!/usr/bin/env python3
"""Build Chapter 12 (EDDARD) close-reading Markdown."""

from pathlib import Path

from agot_extract import extract_range
from agot_reader_common import write_chapter
from build_agot_chapter11_reader import VOCAB as BASE_VOCAB

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs" / "AGOT_逐章精读"

SUMMARIES = [
    "天亮前世界仍安静灰暗时，国王的召唤突然到来。",
    "Alyn把睡梦中的Eddard叫醒；他走进寒冷，发现Robert已经骑在马上，穿着厚重毛皮，像一头骑马的熊，并高声说有国事要谈。",
    "Eddard请Robert进入帐篷交谈，Alyn也替他们掀开门帘。",
    "Robert拒绝进入，因为营地到处有耳朵，也想骑马体验北方；面对等候的Kingsguard与卫兵，Eddard只能穿衣上马。",
    "Robert催动黑色战马高速前进，Eddard努力跟随；风吹散说话声，他们离开kingsroad进入雾中平原，护卫退到听不见的位置。",
    "两人在山脊上迎来黎明，Robert终于停下，因自由奔驰而兴奋，又抱怨缓慢的wheelhouse，威胁它再断车轴便烧掉，让Cersei步行。",
    "Eddard笑着说自己很乐意替他点火。",
    "Robert拍他的肩，说自己甚至想把所有人抛下，一直骑下去。",
    "Eddard微笑说，他相信Robert是认真的。",
    "Robert幻想二人像从前一样做流浪骑士，带剑沿路冒险，再找农家女或酒馆女郎陪伴。",
    "Eddard承认那种生活令人向往，却提醒他们如今对王国、孩子和妻子都有责任，早已不是少年。",
    "Robert抱怨Eddard从未真正年轻过，随后回忆自己和Eddard过去认识的女子，最终追问Jon的母亲。",
    "Eddard冷淡而有礼地回答她叫Wylla，并表示不想谈论。",
    "Robert笑称能令Eddard暂时忘记荣誉的女人必定非同寻常，又想追问她的外貌。",
    "Eddard因愤怒收紧嘴角，请Robert看在友谊份上住口，因为他认为自己在神与人面前同时羞辱了自己和Catelyn。",
    "Robert辩称Eddard当时几乎还不了解Catelyn。",
    "Eddard回答，他已经娶她为妻，而且她正怀着他的孩子。",
    "Robert说Eddard一向对自己过于严厉，又用Baelor the Blessed和刺猬家徽开玩笑，最后答应不再追问。",
    "初升太阳穿过白雾照亮褐色平原，Eddard指出地面低矮长丘是First Men的barrows。",
    "Robert皱眉问他们是不是骑进了墓地。",
    "Eddard说北方到处都有barrows，因为这片土地非常古老。",
    "Robert抱怨这里也很冷，随后说明夜里有King’s Landing信使带来Varys的密报，并把纸交给Eddard。",
    "Eddard解释Varys是master of whisperers，曾先后服务Aerys和Robert；他担心信与Lysa指控有关，但读后发现是另一件事，并追问消息来源。",
    "Robert问Eddard是否记得Ser Jorah Mormont。",
    "Eddard希望自己能忘记：Jorah曾把偷猎者卖给Tyroshi奴隶贩子，给北境和House Mormont蒙羞；Eddard赶去执行国王法律时，他已乘船逃亡。",
    "Robert解释Jorah如今身在Pentos，希望以情报换取王室赦免，因此被Varys利用。",
    "Eddard厌恶地说奴隶贩子如今变成间谍，他宁愿Jorah成为尸体。",
    "Robert说Varys认为间谍比尸体有用，随后要求Eddard评价报告内容。",
    "Eddard说报告只是Daenerys嫁给一名Dothraki horselord，并讽刺是否该送结婚礼物。",
    "Robert阴沉地建议送一把利刀，以及一个敢于用刀的人。",
    "Eddard并不惊讶，因为Robert对Targaryens的仇恨近乎疯狂；他回忆Tywin把Rhaegar妻儿尸体献来时，自己称之为谋杀，Robert却称为战争，两人直到Lyanna死后才因共同悲痛和解。",
    "Eddard决定克制脾气，提醒Robert那个女孩仍是孩子，他不该像Tywin一样屠杀无辜；同时想起Rhaegar幼子女当年被杀的惨状。",
    "Robert反问她还能保持无辜多久，并以粗暴语言将她未来可能生育的孩子称为dragonspawn。",
    "Eddard坚持杀害儿童是卑劣且不可言说的行为。",
    "Robert咆哮说Aerys杀害Brandon和Eddard父亲、Rhaegar伤害Lyanna才真正不可言说，并发誓杀尽所有Targaryens。",
    "Eddard知道Robert盛怒时无法被说服，便避开道德争论，平静指出Daenerys如今并不在他能触及的地方。",
    "Robert苦涩承认无法下手，抱怨Illyrio曾保护两名Targaryen、如今又把他们交给Dothraki，并后悔当年听Jon Arryn劝告没有杀掉他们。",
    "Eddard说Jon Arryn是一位明智的人和优秀的Hand。",
    "Robert怒气迅速消退，转而说Drogo据称有十万武士，并问Jon Arryn会如何判断威胁。",
    "Eddard冷静回答，只要Dothraki留在narrow sea另一边，哪怕一百万也不是威胁，因为他们没有船且惧怕开放海域。",
    "Robert仍不安，指出Free Cities有船，也担心国内仍称他Usurper的Targaryen旧部会在Viserys带Dothraki渡海时响应。",
    "Eddard保证Viserys不会渡海，即使成功也会被赶回海中，随后把话题引向新的Warden of the East。",
    "Robert再次拒绝任命年幼病弱的Robert Arryn，认为Targaryen与Dothraki结盟时不能把四分之一王国交给孩子。",
    "Eddard已有准备，建议若不用Robert Arryn，便任命Robert的兄弟，例如在Storm’s End围城中证明过自己的Stannis。",
    "Eddard让Stannis的名字悬在空气中，观察Robert皱眉沉默和明显不适。",
    "Eddard平静地补充，除非Robert已经把这项荣誉许给别人。",
    "Robert短暂惊讶，随即恼怒，反问即使自己已承诺又如何。",
    "Eddard直接猜出被任命者是Jaime Lannister。",
    "Robert重新催马下山，不看Eddard，最后用一个僵硬的“Yes”确认。",
    "Eddard称Jaime为Kingslayer，并谨慎指出Tywin已是Warden of the West，Jaime将来可能继任，任何人都不该同时掌握东西两方；他没有说出的真正担忧是Lannisters会控制半数军队。",
    "Robert固执地说等Tywin死亡、真正出现问题时再处理，又称决定已经像石头般落定，不准Eddard再烦他。",
    "Eddard请求允许自己坦率直言。",
    "Robert抱怨自己似乎从来阻止不了Eddard说真话。",
    "Eddard直接问Robert是否能够信任Jaime。",
    "Robert说Jaime是Cersei的双胞胎兄弟，又是Kingsguard的Sworn Brother，生命、财富和荣誉都与自己绑定。",
    "Eddard提醒Robert，Jaime过去也以同样誓言与Aerys绑定。",
    "Robert反问为何不信任Jaime，因为他一直服从命令，手中剑还帮助Robert取得王位。",
    "Eddard心想那把剑也玷污了王位，却只说Jaime曾发誓以生命保护国王，最后却亲手杀了国王。",
    "Robert在古老barrow旁勒马，认为Aerys总要有人杀；若不是Jaime，就会轮到自己或Eddard。",
    "Eddard指出自己和Robert都不是宣誓护王的Kingsguard，并决定讲出完整往事，问Robert是否记得Trident。",
    "Robert说自己在那里赢得王冠，不可能忘记。",
    "Eddard回忆Robert被Rhaegar所伤后把追击交给自己；Targaryen残军退向King’s Landing，Aerys与数千忠诚者守在Red Keep，他原以为城门会关闭。",
    "Robert不耐烦地说，Eddard到达时己方军队已经攻下城市，并问这有什么关系。",
    "Eddard纠正那不是Robert的军队，而是Lannister军；城墙上飘的是狮旗，不是王冠雄鹿，而且城市靠背叛夺取。",
    "叙述回顾战争近一年时Lannisters始终中立，直到Tywin带一万二千人假称效忠抵达城门；Aerys把这当成神助，亲自把城市向狮子开放。",
    "Robert说Targaryens同样熟悉背叛，Lannisters只是以同样货币偿还，他们罪有应得，不值得自己失眠。",
    "Eddard苦涩地说Robert并不在场；自己十四年来仍被那次无荣誉的征服和长期隐瞒的事情在夜里纠缠。",
    "Robert咒骂Eddard的honor，反问Targaryens何曾懂荣誉，并叫他去crypt询问Lyanna。",
    "Eddard说Robert已经在Trident为Lyanna复仇，同时在心中听见她当年的低语“Promise me, Ned”。",
    "Robert说复仇没有带回Lyanna，王冠是空洞胜利；他真正祈求的是她安全归来并重新属于自己，诸神却同样嘲弄国王与牧牛人。",
    "Eddard说自己无法替诸神回答，只能讲述进入throne room时所见：Aerys倒在血中，龙骨凝视，Jaime披白斗篷和金甲坐在Iron Throne上。",
    "Robert抱怨这件事人人都知道。",
    "Eddard继续回忆自己骑马穿过龙骨之间，在沉默对峙中看着Jaime膝上染有王血的金剑；最终Jaime笑着起身，说只是替Robert把不舒服的王座坐暖。",
    "Robert放声大笑，惊起草中乌鸦；他认为Jaime当时只有十七岁，只在王座坐了片刻，不足以成为不信任理由。",
    "Eddard坚持无论男孩还是成人，Jaime都没有权利坐上王座。",
    "Robert用“杀国王很累”继续开玩笑，又说Iron Throne确实处处不舒服；他宣布这项秘密可以忘掉，厌烦国事并催Eddard赛马追风。",
    "Eddard没有立即跟随，感到语言已经耗尽且深深无力；他怀疑自己为何来到这里，认为自己不是能约束Robert、教他智慧的Jon Arryn，真正属于Winterfell、Catelyn和Bran身边。",
    "但人不可能永远留在自己所属之地；Eddard认命地催马追赶国王。",
]

KEY_NOTES = {
    1: "世界“still and grey”时召唤抵达，国事先以打断睡眠的方式出现；灰色黎明也为全章道德争论定调。",
    2: "Robert被比作骑马的熊，强调他体格、毛皮与吼声构成的粗野活力，与刚醒的Eddard形成反差。",
    4: "Robert说营地“到处有耳朵”，既说明密报敏感，也说明国王即使在自己队伍中仍需主动制造私密空间。",
    5: "Robert用速度而非命令拉开与护卫的距离；风吹走Eddard的话，使谈话开始前先出现无法被听见的形象。",
    6: "Robert把快骑想象成“男人本应有的方式”，把缓慢车队和家庭责任体验为束缚。",
    10: "流浪骑士幻想并非真正计划，而是Robert对失去的少年时代、性自由和无责任生活的怀旧。",
    11: "Eddard用职责逐项回应幻想：realm、children、wife、queen；两人的根本差异是如何看待成年身份。",
    12: "Robert对女人名字的混乱既带喜剧效果，也显示他的众多短暂关系；追问Jon母亲却触碰Eddard不愿娱乐化的记忆。",
    15: "Eddard不把自己的行为解释为男性常态，而将其命名为对自己和Catelyn的双重羞辱，荣誉在这里首先是责任。",
    18: "刺猬家徽玩笑用heraldry语言形容Eddard“扎手”，Robert通过调笑结束一场自己无法理解的严肃自责。",
    19: "阳光像手指穿过雾，古墓丘在视野中显现；私人旧事自然过渡到埋葬历史的土地。",
    21: "“This land is old”极其简短，却把北方身份从寒冷地理扩展为对远古死者与长时段记忆的意识。",
    23: "Eddard看到Varys来信时先想到Lysa，说明她的指控已成为他解读所有王都消息的首要框架。",
    25: "Jorah罪行不是抽象违法：作为Stark bannerman，他使北境领主必须亲自跨越长途执行司法，也把家族贫困与奴隶交易联系起来。",
    27: "“slaver变成spy”的平行句式并不表示赎罪，只表示一种不光彩身份被另一种替代。",
    30: "Robert把Eddard的“婚礼礼物”讽刺接成暗杀建议，几乎不经过过渡，暴露他已预设报告只能导向杀戮。",
    31: "回忆把当下争论放进旧裂痕：Eddard曾因儿童尸体离开Robert，二人的和解来自共同失去Lyanna，而非对谋杀达成一致。",
    32: "Eddard刻意称Daenerys为“girl”和“child”，用年龄抵抗Robert把她抽象成Targaryen威胁的语言。",
    33: "Robert用粗暴性语言把未来可能性说成现成罪行，并将尚不存在的孩子也预先归类为dragonspawn。",
    35: "Robert把Eddard的“不可言说”夺来描述自己家族遭遇；这不是反驳杀童本身，而是以更早伤害为复仇授权。",
    36: "Eddard知道道德劝告在盛怒时无效，便改用现实可达性问题；这是政治沟通策略，不是价值退让。",
    37: "Robert用疾病、食物和异国服饰侮辱Illyrio及其护卫，语言贬低成为无法实际攻击目标时的替代行动。",
    39: "Robert怒气“突然离开”与突然到来一样快，显示他的情绪高度剧烈却不持久；国家决策因此可能被瞬时激情推动。",
    40: "Eddard的判断以物流而非勇气为基础：没有船、畏惧海洋，使人数无法自动转化为跨海军事威胁。",
    41: "Robert的恐惧并非全无根据：他担心的不只是外敌人数，而是外部军队与国内旧忠诚结合。",
    43: "Robert Arryn的法定继承关系与实际军事能力发生冲突；Warden头衔在这里不是纯荣誉，而是国防权力。",
    45: "Eddard故意让Stannis的名字悬停，阅读Robert的沉默和不适；谈判中的停顿本身成为证据。",
    49: "Robert不看Eddard，以一个硬邦邦的“Yes”结束问题；身体回避和单词长度都显示他知道这项决定难以辩护。",
    50: "Eddard公开论证权力集中，内心担忧则更明确：任命会让Lannisters实际控制半数军队。",
    51: "“stone has been set”把政治任命说成已经固定的石头，Robert以不可逆性代替对风险的回应。",
    55: "Robert列举亲属、誓言和利益绑定作为可信证据；这些恰恰与Jaime过去服务Aerys时的结构相似。",
    56: "Eddard只用一行指出这种相似，整个信任论证立即面对反例。",
    58: "Eddard内心的“玷污王位”没有说出，显示他即使获得坦率许可仍控制措辞，以免谈话彻底破裂。",
    59: "Robert关注Aerys是否该死，Eddard关注谁有权杀他；二人争论的是结果正义与誓言义务的不同层级。",
    60: "“我们不是Kingsguard”精确指出角色差异；随后Eddard决定讲完整往事，谈话从抽象原则进入证词。",
    64: "Eddard反复纠正代词“our men”：胜利叙事中的阵营归属被他拆开，Lannister并非从战争开始就属于Robert。",
    65: "Tywin在双方呼吁中保持中立，最后以假效忠进入城门；Aerys的“最后疯狂行为”是把背叛者误认成救援。",
    66: "Robert用“以同样货币偿还”把背叛变成对等报复，因而拒绝考虑攻城过程中的荣誉问题。",
    67: "“你不在场”把争论从宏观胜负拉回目击者经验；Eddard的失眠表明历史在他身上仍是未结束的当下。",
    69: "“Promise me, Ned”以内心回声打断公开对话；文本事实是Lyanna曾提出承诺，但承诺内容截至此处仍未说明。",
    70: "Robert承认王冠是hollow victory：他赢得政治目标却失去真正祈求的人，胜利因此无法满足欲望。",
    71: "金色Jaime、白斗篷、血泊Aerys和墙上龙骨形成强烈色彩与垂直空间；“How he glittered”既写华丽也带道德讽刺。",
    73: "Eddard几乎不说话，只靠骑马进入、军队涌入和等待迫使Jaime离座；沉默在这段记忆中比指控更有压力。",
    74: "Robert的笑惊起乌鸦，环境对他的轻松产生不祥反响；他又用Jaime只有十七岁缩小Eddard所见的象征冒犯。",
    76: "Robert把Iron Throne的“不舒服”同时当作身体笑话和王权负担，却仍用赛马逃离具体制度问题。",
    77: "Eddard的无力来自语言失效：他讲出珍藏十四年的完整证词，Robert却只听见一个可以笑过便忘的少年恶作剧。",
    78: "结尾区分belonging与duty：Eddard知道自己属于Winterfell，却仍必须追随国王，认命不是认同。",
}

STAGES = [
    (1, 21, "本段从秘密晨骑转入少年时代怀旧、婚姻责任与Jon母亲的话题，再以First Men古墓将私人往事连接到北方长久历史。"),
    (22, 40, "本段由Varys密报引出Jorah和Daenerys婚讯；Robert提出暗杀，Eddard则以儿童无辜和跨海物流反驳复仇冲动。"),
    (41, 51, "本段从外部Dothraki威胁转入Warden of the East任命，Eddard逐步逼出Jaime已获承诺的事实，并警告Lannister权力集中。"),
    (52, 65, "本段围绕Jaime是否可信展开，从Kingsguard誓言追溯到Trident与Lannister靠假效忠进入King’s Landing的历史。"),
    (66, 78, "本段让Robert与Eddard以报复和荣誉两套价值解释同一场征服；Eddard的目击证词最终被笑话化，使他再次意识到Hand的无力。"),
]

BACKGROUNDS = {
    19: "**历史背景：** barrows是覆盖古代墓葬的土丘；北方遍布First Men古墓，显示土地的人类历史极其久远。",
    23: "**职务：** master of whisperers负责情报与间谍网络；Varys曾服务Aerys，如今继续服务Robert。",
    25: "**文本事实：** Jorah把偷猎者卖给Tyroshi奴隶贩子，违反王国法律；作为Stark bannerman，本应由Eddard执行判决，但他已逃亡。",
    31: "**历史背景：** Tywin在叛乱末期把Rhaegar妻儿尸体献给Robert。Eddard称之为谋杀，Robert称之为战争，两人曾因此决裂。",
    35: "**人物所述：** Robert将Brandon、Eddard父亲和Lyanna的遭遇归罪Targaryens；关于Lyanna经历的具体全貌截至本段仍主要来自Robert的愤怒叙述。",
    40: "**地理事实：** narrow sea隔开Seven Kingdoms与Free Cities；Dothraki没有自己的舰队，且文化上畏惧开放海域。",
    43: "**制度：** Warden of the East承担东部国防与军事统辖，不只是继承荣誉；Robert Arryn虽继承House Arryn，却年幼体弱。",
    44: "**文本事实：** Stannis Baratheon是Robert的兄弟，曾在Storm’s End围城中证明军事能力。",
    50: "**制度：** Tywin是Warden of the West；若Jaime未来继承西部又现任东部，Lannisters可能控制王国东西两大军事区。",
    55: "**誓言：** Kingsguard成员宣誓以生命保护国王；Jaime现服务Robert，但曾以同样身份服务Aerys。",
    62: "**历史背景：** Robert在Trident击败Rhaegar并负伤，随后由Eddard追击败军至King’s Landing。",
    65: "**文本事实：** Lannisters在战争大部分时间保持中立，最后Tywin率一万二千人假称效忠，Aerys因此打开城门。",
    69: "**无剧透提示：** Eddard记起Lyanna说“Promise me, Ned”，但当前文本没有解释承诺内容。",
    71: "**文本事实：** Eddard进入throne room时，Aerys已死，Jaime仍穿Kingsguard白斗篷并坐在Iron Throne上。",
}

EXTRA_VOCAB = [
    ("summons", "/ˈsʌmənz/", "n.", "召唤；传唤令", "常用于权威人物的正式召见"),
    ("groggy", "/ˈɡrɑːɡi/", "adj.", "昏昏沉沉的", "刚睡醒或受伤后的状态"),
    ("destrier", "/ˈdestriər/", "n.", "战马", "中世纪骑士使用的强壮坐骑"),
    ("exhilarated", "/ɪɡˈzɪləreɪtɪd/", "adj.", "兴奋振奋的", "高速骑行后的情绪"),
    ("axle", "/ˈæksəl/", "n.", "车轴", "wheelhouse机械部件"),
    ("vagabond", "/ˈvæɡəbɑːnd/", "adj./n.", "漂泊的；流浪者", "此处浪漫化无责任生活"),
    ("wench", "/wentʃ/", "n.", "年轻女子；女侍", "古风且常带轻薄语气"),
    ("prickly", "/ˈprɪkli/", "adj.", "易怒扎人的；多刺的", "与hedgehog家徽玩笑呼应"),
    ("sigil", "/ˈsɪdʒəl/", "n.", "家徽；印记", "家族纹章符号"),
    ("hummock", "/ˈhʌmək/", "n.", "低矮小丘", "平原上的隆起"),
    ("barrow", "/ˈbæroʊ/", "n.", "古墓冢；坟丘", "覆盖古代墓葬的土丘"),
    ("trepidation", "/ˌtrepɪˈdeɪʃən/", "n.", "惶恐；忧惧", "面对可能坏消息"),
    ("eunuch", "/ˈjuːnək/", "n.", "宦官", "此处指Varys"),
    ("bannerman", "/ˈbænərmən/", "n.", "封臣；旗下领主", "向更高领主承担效忠义务"),
    ("coffers", "/ˈkɔːfərz/", "n.", "金库；财政资金", "常用复数"),
    ("poacher", "/ˈpoʊtʃər/", "n.", "偷猎者", "非法捕猎他人土地上的动物"),
    ("pardon", "/ˈpɑːrdən/", "n.", "赦免", "王室免除罪责"),
    ("feign", "/feɪn/", "v.", "假装；佯作", "feign surprise"),
    ("token of fealty", "/ˈtoʊkən əv ˈfiːəlti/", "phr.", "效忠的凭证", "以礼物或行动证明忠诚"),
    ("spawn", "/spɔːn/", "n.", "卵；后代", "dragonspawn为侮辱性去人化称呼"),
    ("grimace", "/ˈɡrɪməs/", "n.", "痛苦或厌恶的扭曲表情", "苦涩面部反应"),
    ("bide one's time", "/baɪd wʌnz taɪm/", "idiom", "等待时机", "暂时不行动"),
    ("sickly", "/ˈsɪkli/", "adj.", "体弱多病的", "形容Robert Arryn"),
    ("aloof", "/əˈluːf/", "adj.", "疏离的；置身事外的", "Lannisters在战争中保持中立"),
    ("profess", "/prəˈfes/", "v.", "公开声称；宣称", "不保证所称为真"),
    ("in kind", "/ɪn kaɪnd/", "phr.", "以同样方式", "报复同类行为"),
    ("curb", "/kɜːrb/", "v.", "约束；抑制", "约束Robert的任性"),
    ("tedious", "/ˈtiːdiəs/", "adj.", "冗长乏味的", "Robert对国事的评价"),
]
VOCAB = BASE_VOCAB + EXTRA_VOCAB

def main():
    blocks = extract_range(106, 113, "EDDARD", "CH12")
    write_chapter(
        out=OUT, chapter=12, pov="EDDARD", page_start=106, page_end=113,
        blocks=blocks, summaries=SUMMARIES, key_notes=KEY_NOTES, stages=STAGES,
        backgrounds=BACKGROUNDS,
        default_background="本段没有新增必须补充的世界观设定；重点在Robert与Eddard的价值冲突、旧日战争记忆、王国军权安排或人物主观判断。",
        vocab=VOCAB,
        guide="Robert在黎明前把Eddard带离营地，表面像恢复少年时代的自由骑行，真正目的却是讨论Varys送来的密报：Daenerys已经与Khal Drogo成婚。Robert将这场婚姻视为王朝威胁，甚至提出暗杀，Eddard则坚持儿童无辜并以跨海物流削弱恐慌。谈话随后转向Warden of the East，Eddard逼出Jaime已获任命的事实，并以Kingsguard誓言和King’s Landing陷落时的亲眼所见质疑他是否可信。整章不是简单的“谨慎对冲动”，而是结果、复仇、荣誉、誓言和军权集中之间的多层冲突。",
        people=[
            ("Eddard Stark", "本章视角人物与Hand of the King，试图以荣誉、证词和制度风险劝说Robert"),
            ("Robert Baratheon", "国王；怀念少年自由，对Targaryens怀有强烈复仇欲"),
            ("Daenerys Targaryen", "密报中的年轻Targaryen，与Khal Drogo成婚"),
            ("Ser Jorah Mormont", "被Eddard放逐的旧臣，如今为Varys提供Pentos情报"),
            ("Jaime Lannister", "Kingsguard成员，Robert拟任命的Warden of the East"),
            ("Tywin Lannister", "Warden of the West，在旧战争末期以假效忠进入King’s Landing"),
            ("Jon Arryn", "已故前任Hand，过去曾阻止Robert追杀流亡的Targaryen儿童"),
        ],
        terms=[
            ("master of whisperers", "负责王室情报、密探与秘密消息的官职"),
            ("Warden of the East", "承担王国东部防务和军事统辖的高级职位"),
            ("Kingslayer", "Jaime因杀死自己宣誓保护的Aerys而获得的称号"),
            ("Trident", "Robert击败Rhaegar、奠定叛乱胜局的战场"),
            ("Iron Throne", "Seven Kingdoms王权的座位和象征"),
            ("barrows of the First Men", "北方平原上覆盖First Men古墓的土丘"),
        ],
        synthesis="Chapter 12以一次高速晨骑展示Robert与Eddard仍有少年友情，却已经无法共享同一套成年政治伦理。Robert把自由理解为摆脱车队、妻子、秘密和繁琐国事；Eddard则把成年定义为对realm、children、wife和誓言负责。面对Daenerys，Robert从旧创伤推出未来儿童也可被预先处决，Eddard坚持无辜不因血统消失。面对Jaime，Robert只看Aerys该死和Jaime曾帮助胜利，Eddard则看谁宣过什么誓、城市如何被夺取、军权将集中到谁手中。最沉重之处在于Eddard终于讲出完整目击记忆，Robert却把它化为一则十七岁少年的笑话。Hand能够提供事实、原则和警告，却不能迫使国王重视它们。",
        contrasts=[
            "**自由快骑／成年责任：** Robert怀念没有负担的少年生活，Eddard逐项列出已不能抛弃的义务。",
            "**复仇记忆／儿童无辜：** Robert以旧伤授权未来杀戮，Eddard拒绝让血统替代个体罪责。",
            "**外部威胁／内部军权：** Dothraki是否有船尚不确定，Jaime的任命却会立即改变国内权力分布。",
            "**结果正义／誓言义务：** Robert认为Aerys该死即可证明杀戮合理，Eddard关注Kingsguard是否有权背叛所护之王。",
            "**目击证词／笑话化：** Eddard记忆中的王座场景是道德创伤，在Robert口中却只是疲倦少年找地方坐。",
            "**belonging／duty：** Eddard属于Winterfell和家人，却因职责继续追赶国王。",
        ],
        questions=[
            "Robert是否会真正下令暗杀Daenerys？",
            "Jaime担任Warden of the East会怎样改变Lannister权力？",
            "Lyanna要求Eddard作出的承诺究竟是什么？",
            "Eddard能否像Jon Arryn一样约束Robert的冲动？",
        ],
        extraction_notes="提取器正确保留PDF pp.108–109、110–111和111–112的3个跨页段落",
    )
    print(f"Wrote Chapter 12 with {len(blocks)} paragraphs")

if __name__ == "__main__":
    main()

