#!/usr/bin/env python3
"""Build Chapter 14 (CATELYN) close-reading Markdown."""

from pathlib import Path

from agot_extract import extract_range
from agot_reader_common import write_chapter
from build_agot_chapter13_reader import VOCAB as BASE_VOCAB

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs" / "AGOT_逐章精读"

SUMMARY_BY_ORDER = {
    1: "Eddard与女孩们离开八天后，Maester Luwin带账簿来到Bran病房，要求核算王室访问的花费。",
    2: "Catelyn只看着Bran和他变长的头发，说自己早已知道王室访问真正“花掉”了什么，拒绝看账。",
    3: "Luwin试图说明王室队伍消耗巨大，Winterfell必须补充储备。",
    4: "Catelyn打断他，坚持让steward处理并把账簿拿走。",
    5: "Luwin提醒Poole已南下建立Eddard在King’s Landing的家，因此Winterfell当前没有steward。",
    6: "Catelyn心不在焉地想起此事，随即又只关注Bran苍白的脸和是否能晒到晨光。",
    7: "Luwin调灯芯并列出急需任命的steward、guard captain和master of horse等职位。",
    8: "“master of horse”一词令Catelyn猛然转头，她的声音像鞭子一样尖锐。",
    9: "受惊的Luwin解释Hullen也随Eddard南下，所以需要替代者。",
    10: "Catelyn爆发说儿子正重伤垂死，她根本不在乎马厩，甚至愿亲手杀光所有马匹换Bran睁眼。",
    11: "Luwin低头表示理解，却仍试图把话题带回必须完成的任命。",
    12: "Robb从门口开口，说这些任命由自己处理。",
    13: "Catelyn没听见Robb进来，意识到自己一直在喊叫后突然羞愧，也开始察觉长期疲惫和头痛。",
    14: "Luwin把准备好的候选名单递给Robb，请他考虑空缺职位。",
    15: "Robb看过名单，说都是合适人选，决定第二天再谈；Catelyn注意到他刚从寒冷户外回来。",
    16: "Luwin正式称Robb为my lord，并把名单收回袖中。",
    17: "Robb让Luwin离开，关门后转向Catelyn；她注意到十四岁的儿子已经佩剑，而他质问她在做什么。",
    18: "Catelyn第一次在Tully外貌的Robb脸上看见Eddard式的北方严厉，并困惑地坚持自己只是在照顾Bran。",
    19: "Robb反问这是否算照顾，因为她从Bran受伤后从未离房，甚至没去城门送别Eddard和女孩们。",
    20: "Catelyn说自己在病房告别并从窗口目送；她无法接受Eddard仍然离开，也因害怕Bran随时死亡而不肯松开他的手。",
    21: "Robb放柔声音，转述Luwin判断最危险时期已经过去，Bran不会死。",
    22: "Catelyn反问若Luwin错了、Bran需要她时她却不在怎么办。",
    23: "Robb指出三岁的Rickon以为所有人都抛弃了他，自己也无法独自承担一切；声音破裂时，Catelyn才记起他只有十四岁，却仍无法离开Bran。",
    24: "塔外有一只狼开始嚎叫，Catelyn短暂发抖。",
    25: "Robb认出是Bran的狼并打开窗，让闷热房间进入夜风和更响亮、忧郁绝望的嚎声。",
    26: "Catelyn要求关窗，因为Bran需要保暖。",
    27: "Robb说Bran需要听见它们歌唱；Shaggydog和Grey Wind相继加入，他还能分辨三种声音。",
    28: "嚎叫、寒风、空城与Bran过去爱笑爱爬的记忆使Catelyn崩溃，她捂耳尖叫，甚至要求杀掉direwolves让声音停止。",
    29: "Catelyn不记得自己如何倒地；Robb抱起她，保证direwolves不会伤害Bran，并把她安置在角落小床上休息。",
    30: "Catelyn哭着说不敢睡，害怕Bran在睡梦中死去，并再次尖叫要求关窗。",
    31: "Robb以她必须睡觉为条件走向窗户，却听见所有城堡犬只异常狂吠；他脸色变白，说出了“Fire”。",
    32: "Catelyn第一反应是Bran有危险，急忙坐起要求Robb帮她搬动儿子。",
    33: "Robb似乎没听见，只说起火的是library tower。",
    34: "Catelyn看见远处红光后因Bran安全而松懈，甚至低声感谢诸神，因为火不可能越过bailey烧来。",
    35: "Robb像看疯子一样看她，命她留下，随后带门外守卫冲下楼去灭火。",
    36: "院中充满呼喊、尖叫、奔跑、马嘶与犬吠；Catelyn突然发现direwolves已经停止嚎叫。",
    37: "她走到窗前为Bran安全祈祷，看着library数百年藏书燃烧而感到悲伤，随后关上窗板。",
    38: "Catelyn转身时，房间里已经多了一个陌生男人。",
    39: "男人阴沉地嘟囔她本不该在这里，原计划房里应当没人。",
    40: "陌生人矮小肮脏、带马厩臭味，却不属于Winterfell马夫；他面容消瘦、浅眼深陷，手里握着dagger。",
    41: "Catelyn先看刀再看Bran，只能从喉中挤出微弱的“No”。",
    42: "陌生人听见后称杀死Bran是mercy，因为孩子已经等同死亡。",
    43: "Catelyn找回声音并转身呼救，男人却迅速捂嘴后扯她头发，把dagger抵向气管。",
    44: "Catelyn双手抓住刀刃阻止割喉，在缺氧中咬破男人手掌；他松手后又扯倒她，仍握着沾血dagger重复她不该在场。",
    45: "Bran的direwolf像影子滑入门内，以低沉威胁扑倒男人并咬开他的喉咙。",
    46: "刺客的血像温热雨水喷在Catelyn脸上。",
    47: "direwolf红着嘴看向Catelyn，舔净她手上的血后跳上Bran的床躺在他身边；Catelyn终于认出它并歇斯底里地笑。",
    48: "Robb、Luwin、Ser Rodrik和守卫冲入时看见的就是这幅场景；随后Catelyn被裹暖送回自己的房间，由Old Nan洗去血迹。",
    49: "Luwin处理她几乎见骨的手指伤口和被扯伤的头皮，预告疼痛才刚开始，并给milk of the poppy助眠。",
    50: "Catelyn终于闭上眼睛入睡。",
    51: "她再次醒来已过四天；手上疼痛证明血与悲 grief并非噩梦，但她虽虚弱眩晕，却感到重担被移开般坚定。",
    52: "Catelyn命仆人送来面包蜂蜜并通知Luwin更换绷带，恢复发号施令令众人惊讶。",
    53: "她为此前抛下孩子、丈夫和House责任而羞愧，发誓不再失守，并要展示Riverrun的Tully有多坚强。",
    54: "Robb带Ser Rodrik、Theon和新guard captain Hallis Mollen前来；Catelyn注意到Robb已穿皮甲、ringmail并佩剑。",
    55: "Catelyn首先询问刺客身份。",
    56: "Hallis说无人知道其姓名，他不是Winterfell人，但有人过去几周在城堡附近见过。",
    57: "Catelyn推断他可能属于国王或Lannisters队伍，并故意在其他人离开后留下。",
    58: "Hallis承认可能，但近期陌生人太多，无法确定其所属。",
    59: "Theon根据气味判断刺客一直躲在马厩。",
    60: "Catelyn尖锐追问这样的人为何能一直不被发现。",
    61: "Hallis羞愧解释大量马匹南北调走后马厩半空，躲避stableboys并不难；Hodor或许见过，但他无法清楚表达。",
    62: "Robb补充他们找到刺客睡处，稻草下埋着装有九十枚silver stags的皮袋。",
    63: "Catelyn苦涩反讽，至少自己的儿子没有被廉价出卖。",
    64: "Hallis困惑地确认，Catelyn是否认为陌生人真是来杀Bran。",
    65: "Theon也怀疑这种解释过于疯狂。",
    66: "Catelyn根据刺客反复说她不该在场，推断library火灾是诱饵，原本要把她和守卫引走后杀Bran。",
    67: "Robb难以理解为何有人要杀一个无助熟睡的小男孩。",
    68: "Catelyn以挑战目光要求将来统治北方的Robb自己推理：什么会让人想杀一个熟睡孩子。",
    69: "Robb回答前，仆人送来远超要求的丰盛早餐，Luwin也随之进入。",
    70: "Catelyn看着食物却没有胃口，只询问Bran状况。",
    71: "Luwin低眼回答，Bran情况没有变化。",
    72: "Catelyn早已预期此答案，手伤像刀仍在切割般跳痛；她遣退仆人，再问Robb是否找到答案。",
    73: "Robb推断有人害怕Bran醒来，害怕他说出、做出或知道的某件事。",
    74: "Catelyn为Robb的推理骄傲，并命新guard captain保护Bran，因为若有一个杀手，可能还有更多。",
    75: "Hallis询问她需要多少守卫。",
    76: "Catelyn提醒他，Eddard不在时Robb才是master of Winterfell。",
    77: "Robb因获得正式权威而站得更直，命令病房内一人、门外一人、楼梯下两人昼夜守卫，任何探视须经他或Catelyn许可。",
    78: "Hallis以m’lord称呼Robb并接受命令。",
    79: "Catelyn建议Hallis立即执行，而不是继续留在会议中。",
    80: "Robb补充应让Bran的direwolf继续留在房内。",
    81: "Catelyn第一次、又重复一次同意，让过去想杀direwolves的崩溃反应被新的认识取代。",
    82: "Hallis鞠躬离房执行安排。",
    83: "Ser Rodrik等守卫离开后询问Catelyn是否注意刺客使用的dagger。",
    84: "Catelyn干笑说当时无法仔细检查，但可以为刀锋的锐利作证，并反问原因。",
    85: "Ser Rodrik说dagger仍在死者手中，精美程度远超其身份：刀刃是Valyrian steel，柄是dragonbone，显然由某人提供。",
    86: "Catelyn思考后命Robb关上房门。",
    87: "Robb虽感奇怪，仍照做。",
    88: "Catelyn要求在场者宣誓保密，因为若猜测部分为真，Eddard和女孩们已身陷致命危险，泄密可能害死他们。",
    89: "Theon说Eddard如同自己的第二位父亲，正式宣誓。",
    90: "Maester Luwin也给出誓言。",
    91: "Ser Rodrik同样宣誓保密。",
    92: "Catelyn转向Robb，要求儿子也作出承诺。",
    93: "Robb点头同意保密。",
    94: "Catelyn透露Lysa相信Lannisters谋杀Jon Arryn，又注意Jaime在Bran坠落日没有参加狩猎；她据此怀疑Bran并非失足，而是被人推下。",
    95: "众人震惊，Ser Rodrik认为这是可怕指控，甚至Kingslayer也会因谋杀无辜儿童而退缩。",
    96: "Theon反问Jaime是否真的会退缩，表示怀疑。",
    97: "Catelyn说Lannister的骄傲与野心没有界限。",
    98: "Luwin若有所思地指出Bran过去脚步一向稳健，对Winterfell每块石头都极熟悉。",
    99: "Robb愤怒拔剑挥舞，发誓若猜测属实便亲手杀掉Jaime。",
    100: "Ser Rodrik严厉命他收剑，提醒Lannisters远在百league外，也再次教导除非真要使用，否则绝不拔剑。",
    101: "Robb羞愧收剑，瞬间又像孩子；Catelyn借机指出儿子如今已经佩戴真钢。",
    102: "Ser Rodrik说自己认为是时候让Robb佩剑了。",
    103: "Catelyn回答早就该如此，因为Winterfell可能很快需要所有真剑，而不是木剑。",
    104: "Theon握住剑柄，表示若局势发展到冲突，House Greyjoy欠House Stark一笔大债。",
    105: "Luwin提醒一切目前只是conjecture，被指控者是queen最爱的兄弟；若无proof，他们必须永远沉默。",
    106: "Ser Rodrik认为dagger就是寻找proof的线索，因为如此名贵的刀不可能无人注意。",
    107: "Catelyn意识到只有一个地方可以查清匕首来历，开始说必须有人前往某地。",
    108: "跨页后她说出目的地：King’s Landing。",
    109: "Robb立刻自告奋勇前往。",
    110: "Catelyn拒绝，因为Winterfell必须始终有Stark留守；她评估在场人选后决定亲自去，并用僵硬绷带手指挣扎下床。",
    111: "Luwin质疑这样是否明智，因为Lannisters会对她突然抵达产生怀疑。",
    112: "Robb困惑地问Bran怎么办，无法相信母亲会离开他。",
    113: "Catelyn把受伤的手放在Robb手臂上，说已为Bran做尽一切，他如今交给诸神和Luwin；她必须像Robb提醒的那样考虑其他孩子。",
    114: "Theon提醒她需要强大escort。",
    115: "Robb提议派Hallis带一队guardsmen护送。",
    116: "Catelyn拒绝大型队伍，因为它会吸引注意，她不想让Lannisters预先知道自己到来。",
    117: "Ser Rodrik至少请求亲自陪同，认为女子独行kingsroad很危险。",
    118: "Catelyn接受Ser Rodrik同行，并计划沿White Knife至White Harbor乘船，以两名骑手和顺风抢在Eddard及Lannisters之前到达King’s Landing。",
}

SUMMARIES = [SUMMARY_BY_ORDER[i] for i in range(1, 119)]

KEY_NOTES = {
    1: "Luwin把王室访问的“cost”当作会计数字，Catelyn在下一段把同一词改写为Bran的身体代价。",
    2: "Catelyn不看账而看儿子，拒绝的不是算术能力，而是承认城堡生活仍应按日常制度继续。",
    5: "Luwin像“小灰鼠”咬住问题不放；Catelyn的贬损想象也显示她把必要行政坚持体验为烦扰。",
    8: "“voice was a whip”把母亲的痛苦变成攻击性声音；master of horse直接触发Bran曾经热爱骑乘和将要南下的记忆。",
    10: "杀光马匹的极端假设说明Catelyn此刻把城堡一切功能都放在Bran生命之下，无法进行比例判断。",
    12: "Robb一句“我来任命”填补成人权力真空；他不是等待母亲恢复，而是已经开始履行master of Winterfell职责。",
    13: "Catelyn先因自己在喊叫而羞愧，再问“我怎么了”；这标志她首次从Bran身上短暂转回观察自身崩溃。",
    16: "Luwin称Robb为my lord，将十四岁少年的临时权威正式化；袖中纸张的出现和消失也体现行政秩序继续运作。",
    17: "Robb关门后才质问母亲，既保护她的公开尊严，也让佩剑少年与疲惫母亲形成新的角色倒置。",
    18: "Catelyn第一次在Robb脸上看到Eddard，意味着危机迫使儿子从她熟悉的Tully孩子变成需要承担北方严厉职责的人。",
    20: "她认为Eddard说“没有选择”却仍然“选择着离开”；这一内心修正揭示她拒绝把政治职责当成真正无选择。",
    23: "Robb先列Rickon需求，最后才承认自己也需要母亲；声音破裂瞬间撕开铠甲、剑和命令构成的成人外表。",
    25: "闷热病房与夜间冷风对立；Robb打开的不只是窗，也让Catelyn无法继续隔绝城堡其他生命的声音。",
    27: "Robb称嚎叫为“sing”，Catelyn却听成折磨；同一声音在兄妹与母亲耳中具有保护、联系和死亡恐惧的不同意义。",
    28: "本段以night after night和never changing累积重复压迫，再用Bran过去爱笑、攀爬、梦想骑士的清单制造失去感。",
    29: "Robb保证direwolves不会伤害Bran，后面的袭击将把这句安慰变成可验证的判断。",
    31: "direwolves嚎叫、城堡犬狂吠和火灾依次叠加；动物先于人类辨认异常，声音构成预警系统。",
    34: "Catelyn因火烧library而感谢诸神，Robb因而像看疯子；这不是她憎恨书，而是她的世界已经缩小到Bran是否安全。",
    36: "在院落噪声达到顶点时direwolves反而沉默，说明嚎叫的功能已经完成，新的威胁进入近距离行动阶段。",
    38: "极短转折句把公共灾难突然变成私人密室威胁；读者和Catelyn同时发现男人，没有准备时间。",
    39: "刺客重复“你不该在这里”，首先暴露计划依赖病房无人，而不是暴露雇主身份。",
    41: "Catelyn的“No”从喉中卡出的微声，与她此前对行政人员的鞭状声音对照；真实暴力暂时夺走语言。",
    42: "刺客把谋杀命名为mercy，与Jaime上一章对残疾生命的说法形成当前文本可见的词语回声，但不能仅凭同词证明共同策划。",
    44: "战斗描写集中于抓刃、缺氧、咬伤和气味，没有优雅武技；Catelyn靠母亲本能和身体顽强拖延。",
    45: "direwolf像shadow进入，先以低于snarl的声音警告，再精准咬喉；它的行动与Ghost保护Jon形成物种行为呼应。",
    47: "狼先舔净Catelyn受伤的手再回Bran床边，完成“消除威胁—确认母亲—守护主人”的清晰序列；她的笑是冲击后失控。",
    50: "独立一句“Finally she closed her eyes”是对她此前“不能睡”的直接解决，睡眠由危险变成生存必需。",
    51: "四天睡眠将章节分成崩溃与行动两半；手部疼痛把过去固定为事实，反而让她不再靠持续守床证明母爱。",
    53: "Catelyn把恢复表述为Tully of Riverrun的家族力量，借出生身份重建此前只围绕Bran存在的自我。",
    54: "Robb的皮甲、ringmail和剑不是装饰，而是Catelyn失去行动能力期间他实际接管城堡的外在标志。",
    57: "“国王的人或Lannisters的人”是Catelyn根据时间和陌生人来源提出的假设，并非已经确认的归属。",
    62: "九十silver stags将刺客从孤立疯子转成可能受雇者；钱证明交易存在的可能，但仍不证明谁付款。",
    63: "“没有廉价出售”是极苦的反讽，把儿子生命被标价的震惊伪装成冷静。",
    66: "Catelyn把火灾、刺客原话和守卫调动拼成一条计划链；这是强有力推理，仍需与“幕后是谁”分开。",
    68: "她没有直接给Robb答案，而要求未来领主自己推理；母亲角色在此转成政治教育者。",
    73: "Robb的答案把Bran从无意义受害者变成潜在证人：杀手害怕的不是他能做什么，而是他醒来后能说什么。",
    76: "Catelyn把最终守卫数量交给Robb决定，明确承认Eddard不在时他的正式统治位置。",
    77: "Robb因权威“站得更高”，然后给出分层守卫方案；身体姿态与制度能力同步增长。",
    81: "Catelyn重复“Yes”，不仅同意狼留房，也修正自己崩溃时“杀掉它们”的命令；经验改变了她对direwolf的理解。",
    84: "“可以为刀锋作证”的干笑把手伤转成证词和黑色幽默，显示她已能用语言控制创伤。",
    85: "Valyrian steel与dragonbone把简陋刺客和珍贵武器强烈错配；匕首成为从执行者追向委托者的物质线索。",
    88: "关门、宣誓和错误耳朵会致命的警告把家庭会议转成秘密政治议事。",
    94: "Catelyn将Lysa指控、Jaime未狩猎、Bran坠落和第二次刺杀连接；前两项是真实线索，结论仍是明确标为“I think”的推测。",
    95: "Ser Rodrik以“连Kingslayer也会退缩”表达对骑士边界的残余信念；Theon下一句立刻质疑这种底线是否存在。",
    98: "Luwin提供的是行为概率证据：Bran过去从不失手且熟悉每块石头；这支持怀疑，却不直接识别推手。",
    99: "Robb用拔剑把遥远敌人变成可立即攻击的对象，是愤怒少年对无力的补偿。",
    100: "Ser Rodrik的规则“除非真要用，否则不拔剑”把武器从情绪符号还原为实际承诺。",
    101: "Robb收剑后“突然又是孩子”，说明成人职责和少年冲动并存，不是一次危机便完成成长。",
    103: "木剑／钢剑回扣此前练武场；如今真钢不再是男性自尊游戏，而是Catelyn判断城堡可能面对真实冲突。",
    105: "Luwin把conjecture与proof明确分开，也提醒指控queen最爱的兄弟会产生巨大政治后果。",
    107: "“只有一个地方”把匕首调查和地理行动绑定；跨页断句延迟目的地，制造决定的重量。",
    110: "Catelyn亲自下床把思想决定变成身体行动；僵硬绷带手指强调她不是痊愈后出发，而是带伤重新承担责任。",
    113: "她用Robb此前“其他孩子需要你”的论点回应他，显示儿子的质问真正改变了她，而非仅被刺杀吓醒。",
    116: "拒绝大队护卫说明目标不是公开对质，而是秘密取证；安全人数与隐蔽性发生权衡。",
    118: "White Knife—White Harbor—海路构成避开kingsroad的具体方案；末句“看看会看见什么”保留调查开放性，没有提前宣判。",
}

STAGES = [
    (1, 23, "本段以账簿和职位空缺迫使Catelyn面对Winterfell仍需运转；Robb接管行政并请求母亲照顾Rickon和自己，揭露家庭职责失衡。"),
    (24, 51, "本段从direwolves嚎叫、火灾预警进入刺客袭击；Bran的狼杀死袭击者，Catelyn在受伤和四日睡眠后由崩溃转为坚定。"),
    (52, 81, "本段调查刺客身份、藏身处、银币和诱饵火灾；Catelyn引导Robb推断Bran是潜在证人，并建立多层守卫。"),
    (82, 106, "本段由Valyrian steel匕首引出秘密宣誓与Lannister猜测；在愤怒和拔剑之后，Luwin要求把conjecture转化为proof。"),
    (107, 118, "本段将调查转化为秘密南下计划；Catelyn决定亲往King’s Landing，并以两人海路兼顾速度与隐蔽。"),
]

BACKGROUNDS = {
    1: "**时间：** Eddard及女孩们已离开Winterfell八天；Catelyn仍守在Bran房内。",
    5: "**行政：** steward Poole随Eddard南下建立King’s Landing household，因此Winterfell必须补任管家。",
    17: "**继承秩序：** Eddard不在时，长子Robb作为master of Winterfell承担任命、守卫与城堡管理。",
    23: "**文本事实：** Rickon只有三岁，误以为家人都离弃自己；Robb十四岁，已被迫同时照顾弟弟和管理城堡。",
    27: "**direwolves：** 三声分别来自Bran未命名的狼、Rickon的Shaggydog和Robb的Grey Wind。",
    31: "**文本事实：** direwolves持续嚎叫后，所有普通犬只首次同时狂吠；随后发现library tower起火。",
    45: "**文本事实：** Bran的direwolf进入病房并杀死持刀刺客，随后回到Bran床边守护。",
    49: "**医药：** milk of the poppy是强效止痛、镇静药物；Catelyn服用后沉睡四天。",
    57: "**推断标记：** 刺客可能来自国王或Lannister队伍，是Catelyn根据近期陌生人来源提出的初步假设。",
    62: "**货币：** silver stag是王国银币；九十枚构成明显报酬，支持受雇行凶推测。",
    66: "**证据链：** 已知事实包括火灾、守卫离开、陌生人进入、原话和dagger；“火是故意诱饵”是Catelyn据此作出的合理推断。",
    73: "**推断标记：** Robb认为幕后者害怕Bran醒来作证；这解释动机，但尚未确认Bran知道什么。",
    85: "**材料：** dagger刀刃为Valyrian steel、柄为dragonbone，价值与刺客外表身份明显不符。",
    94: "**推断标记：** Lysa指控与Jaime留城是线索；“Bran被Jaime或Lannister推下”截至此处仍未获得直接证据。",
    105: "**法律与政治：** 指控queen的双胞胎兄弟需要可公开验证的proof；否则猜测本身可能危及Starks。",
    118: "**路线：** White Knife河通往White Harbor；从港口乘船可避开kingsroad和大型车队，争取提前抵达King’s Landing。",
}

EXTRA_VOCAB = [
    ("books of account", "/bʊks əv əˈkaʊnt/", "n.", "账簿", "记录收入、支出与库存"),
    ("replenish", "/rɪˈplenɪʃ/", "v.", "补充；重新装满", "补充储备"),
    ("steward", "/ˈstuːərd/", "n.", "管家；领地事务主管", "城堡高级行政职位"),
    ("wick", "/wɪk/", "n.", "灯芯", "油灯燃烧部件"),
    ("one whit", "/wʌn wɪt/", "phr.", "丝毫；一点点", "常用于否定句"),
    ("vacant", "/ˈveɪkənt/", "adj.", "空缺的；无人占用的", "vacant offices"),
    ("melancholy", "/ˈmelənkɑːli/", "n./adj.", "忧郁；忧伤的", "狼嚎的情绪色彩"),
    ("cacophony", "/kəˈkɑːfəni/", "n.", "刺耳嘈杂声", "多种警报声音叠加"),
    ("bailey", "/ˈbeɪli/", "n.", "城堡外院或内院", "建筑空间"),
    ("gaunt", "/ɡɔːnt/", "adj.", "消瘦憔悴的", "刺客面貌"),
    ("windpipe", "/ˈwɪndpaɪp/", "n.", "气管", "dagger抵住的位置"),
    ("wrench", "/rentʃ/", "v.", "猛扭；猛拉", "direwolf撕扯动作"),
    ("hysterically", "/hɪˈsterɪkli/", "adv.", "歇斯底里地；情绪失控地", "创伤后的笑"),
    ("scalding", "/ˈskɔːldɪŋ/", "adj.", "滚烫的", "scalding hot bath"),
    ("resolute", "/ˈrezəluːt/", "adj.", "坚定果断的", "醒来后的精神状态"),
    ("boiled leather", "/bɔɪld ˈleðər/", "n.", "硬化皮甲", "经处理用于防护"),
    ("ringmail", "/ˈrɪŋmeɪl/", "n.", "环片甲；环状金属甲", "轻型护甲"),
    ("abashed", "/əˈbæʃt/", "adj.", "羞愧尴尬的", "Hallis与Robb受训斥后的反应"),
    ("rasher", "/ˈræʃər/", "n.", "一片培根", "英式食物量词"),
    ("warrant", "/ˈwɔːrənt/", "n.", "授权；许可令", "探视Bran所需许可"),
    ("vouch for", "/vaʊtʃ fɔːr/", "v.", "担保；证明", "为dagger锋利作证"),
    ("hilt", "/hɪlt/", "n.", "刀剑柄", "dragonbone hilt"),
    ("conjecture", "/kənˈdʒektʃər/", "n.", "推测；猜想", "与proof对照"),
    ("league", "/liːɡ/", "n.", "里格；旧距离单位", "此处表示很远"),
    ("impetuous", "/ɪmˈpetʃuəs/", "adj.", "冲动急躁的", "Theon人物判断"),
    ("unyielding", "/ʌnˈjiːldɪŋ/", "adj.", "坚硬不屈的", "绷带手指像石头"),
    ("escort", "/ˈeskɔːrt/", "n.", "护卫队；护送者", "旅行安全"),
    ("perilous", "/ˈperələs/", "adj.", "危险的", "kingsroad旅行风险"),
    ("brisk", "/brɪsk/", "adj.", "轻快的；强劲的", "brisk winds"),
]
VOCAB = BASE_VOCAB + EXTRA_VOCAB

def main():
    blocks = extract_range(123, 132, "CATELYN", "CH14")
    write_chapter(
        out=OUT, chapter=14, pov="CATELYN", page_start=123, page_end=132,
        blocks=blocks, summaries=SUMMARIES, key_notes=KEY_NOTES, stages=STAGES,
        backgrounds=BACKGROUNDS,
        default_background="本段没有新增必须补充的世界观设定；重点在Catelyn的创伤与恢复、Winterfell行政责任、刺客证据链或尚待验证的Lannister推断。",
        vocab=VOCAB,
        guide="Catelyn把自己封闭在Bran病房时，Maester Luwin和Robb被迫提醒她：Winterfell仍需任命官员，Rickon与Robb也仍需要母亲。direwolves的嚎叫和library火灾把情绪崩溃突然转成真正袭击；一名受雇者闯入病房企图杀Bran，Bran的狼及时将其咬死。四日沉睡后，Catelyn从持续守床转向调查：银币证明刺客可能受雇，Valyrian steel dagger则提供可追查的物质线索。她把Lysa的指控、Jaime留城和Bran异常坠落连接起来，但仍需要proof，因此决定秘密前往King’s Landing。",
        people=[
            ("Catelyn Stark", "本章视角人物；从长期守床和崩溃转向调查、保护其他孩子与秘密南下"),
            ("Robb Stark", "十四岁，Eddard不在时担任master of Winterfell并开始正式发号施令"),
            ("Bran Stark", "仍昏迷；第二次成为明确刺杀目标，也可能是幕后者害怕的证人"),
            ("Maester Luwin", "维持Winterfell行政与医疗，并坚持区分conjecture和proof"),
            ("Ser Rodrik Cassel", "master-at-arms，辨认dagger材料并自愿护送Catelyn"),
            ("Theon Greyjoy", "Eddard的ward，参与秘密会议并宣誓支持House Stark"),
            ("Hallis Mollen", "Robb新任命的guard captain，负责加强Bran守卫"),
            ("Bran的direwolf", "预警火灾并在病房内杀死刺客，随后守在Bran身边"),
        ],
        terms=[
            ("silver stags", "王国银币；刺客藏有九十枚，可能是受雇报酬"),
            ("Valyrian steel", "稀有而名贵的刀剑材料，远超普通刺客身份"),
            ("dragonbone", "匕首柄材料，与Valyrian steel共同构成重要来源线索"),
            ("White Knife", "从北境内陆通往White Harbor的河流路线"),
            ("White Harbor", "北境重要港口，Catelyn计划从此乘船南下"),
        ],
        synthesis="Chapter 14不是简单的“Catelyn恢复坚强”，而是重新定义照顾。开头她把守在Bran床边视为唯一母职，所有账簿、职位、Rickon和Robb的需求都像对Bran的背叛；袭击却证明单纯在场既无法让Bran醒来，也不能替其他孩子和城堡承担责任。direwolf先以嚎叫预警，再以身体救下她和Bran，使Catelyn不得不修正自己对这些动物的恐惧。醒来后她把创伤转成证据工作：原话、火灾、银币、匕首材料、Jaime行踪和Bran攀爬能力分别具有不同证明力度。她的最大进步正是接受“强烈怀疑不等于proof”，因此不公开复仇，而是选择隐蔽、快速地去King’s Landing查证。",
        contrasts=[
            "**账面cost／生命cost：** Luwin计算王室消耗，Catelyn只看见Bran受伤这一不可量化代价。",
            "**守床／照顾整个家庭：** 她起初把离房等同抛弃Bran，后来承认Robb、Rickon和南方孩子也需要行动。",
            "**direwolves嚎叫／普通犬狂吠：** 动物声音先于人类发现火灾和近距离威胁。",
            "**mercy说辞／真实谋杀：** 刺客以怜悯包装杀害无助儿童，Catelyn用身体抵抗揭穿其暴力本质。",
            "**conjecture／proof：** Lannister动机链具有解释力，但匕首来源才可能把怀疑推进到可验证证据。",
            "**大队护卫／两人潜行：** 公开力量更安全却暴露目的，秘密调查选择速度和隐蔽。",
        ],
        questions=[
            "谁支付了九十枚silver stags并提供名贵dagger？",
            "Bran究竟看见或知道了什么，令幕后者害怕他醒来？",
            "Catelyn能否在King’s Landing查到匕首来历而不惊动Lannisters？",
            "Bran的direwolf为何能提前感知火灾和刺杀威胁？",
        ],
        extraction_notes="提取器正确保留PDF pp.125–126、127–128和129–130的3个跨页段落",
    )
    print(f"Wrote Chapter 14 with {len(blocks)} paragraphs")

if __name__ == "__main__":
    main()

