#!/usr/bin/env python3
"""Build Chapter 48 (JON) close-reading Markdown."""
from pathlib import Path
from agot_extract import extract_range
from agot_reader_common import write_chapter
from build_agot_chapter47_reader import VOCAB as BASE_VOCAB

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs" / "AGOT_逐章精读"

S = {
1:"Sam兴奋告诉Jon，自己获准与其他recruits一起结束training、成为Night’s Watch brother。",
2:"Jon惊喜地确认消息是否当真。",
3:"Sam将协助Maester Aemon管理library、letters与ravens，正好发挥识字能力。",
4:"Jon真心肯定Sam会胜任。",
5:"Sam怕决定反悔，急着准时赶往sept；融水与阳光让Wall呈现少见的明亮景象。",
6:"sept内crystal把晨光折成rainbow，众人惊讶Sam出现却保持肃静，Celladar也难得清醒。",
7:"Mormont、Aemon、Alliser与三个orders的senior officers正式到场，仪式具有完整组织权威。",
8:"Mormont说众人虽来自罪犯、children、贵族或无名者，过去身份都在Wall被抹平，今后同属一个House。",
9:"他说明evenfall宣誓后，罪与债会被免除，同时必须放弃旧忠诚、怨恨与爱，重新开始。",
10:"Night’s Watch只为realm及其中所有人服务，不为king、lord、gold、glory或爱情；brothers以duty、honor和彼此替代家庭。",
11:"Mormont警告vow终身不可撤回，desertion判死，并给所有人最后一次无羞辱退出的机会。",
12:"没有人选择离开。",
13:"Mormont安排他们在evenfall于sept宣誓，并询问谁仍信old gods。",
14:"Jon起身表明自己信奉old gods。",
15:"Mormont知道Jon会像Benjen一样希望在heart tree前宣誓。",
16:"Jon确认；他把自己与Stark、First Men血统及old gods连接起来。",
17:"Grenn疑惑Castle Black根本没有godswood。",
18:"Pyp用aurochs玩笑嘲弄Grenn迟钝。",
19:"Grenn认真辩称自己一定能远远看见aurochs。",
20:"Mormont解释Wall以北的haunted forest自Dawn Age便存在，不需人工godswood；半league外有weirwood grove。",
21:"Sam出人意料地请求与Jon一起去heart tree前宣誓。",
22:"Mormont问House Tarly是否也信old gods。",
23:"Sam承认家族千年来都在Seven之光下命名，自己也不例外。",
24:"Jaremy Rykker追问他为何放弃父亲与House的神。",
25:"Sam说Night’s Watch如今才是自己的House，而Seven从未回应祈祷，或许old gods会。",
26:"Mormont允许后公布order分配：不同recruit进入builders、rangers或stewards，最后Jon被分到stewards。",
27:"Jon先以为听错，看到Alliser得意目光后立即认定这是对方故意羞辱。",
28:"Mormont结束仪式，Alliser带着笑离开；Jon把结果进一步理解为Alliser获胜。",
29:"Jaremy带走new rangers；Pyp不安，Grenn却因如愿而未察觉Jon的受挫。",
30:"Othell Yarwyck带Haider与Albett去builders。",
31:"Jon只见自己与Sam、Dareon留在stewards，身份落差令他恶心而难以置信。",
32:"Bowen Marsh安排Sam接替Chett，日夜协助Aemon照料rookery、library，并强调Aemon的珍贵。",
33:"Dareon将去Eastwatch，利用贵族餐桌经验帮助Cotter Pyke判断商船货物、价格与食品品质。",
34:"Marsh宣布Mormont亲自点名Jon做personal steward，并住在其tower下层。",
35:"Jon用尖锐反问列举端饭、穿衣、洗澡等servant工作。",
36:"Marsh确认这些职责，还包括传信、添火、换寝具及Mormont要求的一切。",
37:"Jon直接问他们是否把自己当servant。",
38:"Aemon回答他们原以为Jon是Night’s Watch的man，但Jon的反应让这一判断可疑。",
39:"Jon以性别化偏见贬低日常劳动，勉强压住离席冲动并请求离开。",
40:"Marsh允许他走。",
41:"Jon与Sam、Dareon沉默到yard；融化的Wall在他愤怒视角里化成想一击毁掉的对象。",
42:"Sam追上Jon，兴奋地问他是否看懂安排的真正意义。",
43:"Jon只看到Alliser操纵与羞辱，仍在愤怒中拒绝其他解释。",
44:"Dareon以Lord Snow反讽Jon自视高于普通stewards。",
45:"Jon诉诸剑术与骑术优势，认为分配不公平。",
46:"Dareon用自己声称遭诬陷、被流放的经历反击Jon关于fairness的抱怨，随后离开。",
47:"Sam坚持steward身份本身并不羞耻。",
48:"Jon把未来简化成替老人洗内衣，继续只看最低贱的表层任务。",
49:"Sam指出personal steward会参加会议、传递letters、战时作squire，能像shadow般接触Mormont全部工作；更重要的是Mormont亲自要Jon。",
50:"Sam以父亲让heir旁听court的经验类比，推测Mormont正在让Jon观察、学习，为未来command作准备。",
51:"Jon想到Eddard也让Robb参与councils，开始承认Sam可能正确，却仍本能说自己没要求这种安排。",
52:"Sam提醒没有人是按自己意愿来到Wall。",
53:"Jon突然为自己的幼稚与特权感羞愧。",
54:"Jon想到Sam敢接受命运、Benjen曾说他只是summer-smelling green boy，明白Wall迫人迅速成长。",
55:"他承认Sam说得对，自己刚才像child。",
56:"Sam确认Jon是否会留下并与他一起宣誓。",
57:"Jon用old gods在等他们作答，并勉强重新微笑。",
58:"傍晚众人穿过Wall内曲折冰隧道与三重iron bars；巨大冰体的压迫让北侧重见日光成为释放。",
59:"Sam刚到Wall以北便担心wildlings是否敢逼近。",
60:"Jon说他们从未如此靠近，随后召Ghost同行。",
61:"Bowen Marsh的garron惧怕direwolf，他问Jon是否真要带它。",
62:"Jon确认；Ghost像嗅到什么，突然穿过荒地冲入树林消失。",
63:"进入haunted forest后，环境虽像Winterfell wolfswood，氛围却截然不同。",
64:"因为意识到自己越过‘世界尽头’，shadow、sound、snow与leaves都变得ominous，Wall在后、前方未知。",
65:"他们到达九棵weirwoods围成的罕见grove；红叶黑腐、骨白树干与红色sap形成神圣又不安的视觉，Marsh命众人不得亵渎。",
66:"Sam逐一看过不同的carved faces，低声觉得old gods正在注视。",
67:"Jon确认并与Sam一同跪下。",
68:"日光消失、白昼转黑时，两人共同开始宣誓。",
69:"完整vow承诺放弃婚姻、土地、后代、冠冕与荣耀，把生命、职位和honor永久献给Night’s Watch与realm防线。",
70:"树林沉默后，Marsh宣布他们跪下时是boys，起身时已成为Night’s Watch men。",
71:"Jon拉Sam起身，rangers祝贺；只有老forester Dywen因夜晚气味不对而催促立即返程。",
72:"Ghost忽然从两棵weirwoods之间回来；它的白毛红眼与树木相似，使Jon不安。",
73:"Ghost嘴里衔着黑色物体；Marsh皱眉问那是什么。",
74:"Jon跪下命Ghost把东西带来。",
75:"Ghost走近，Sam猛吸一口气，显示他先认出了异常。",
76:"Dywen确认Ghost带回的是一只hand，仪式后的神圣寂静骤然变成现实恐怖。",
}
SUMMARIES = [S[i] for i in range(1, 77)]

KEY_NOTES = {
5:"warm、sunny、sparkle构成短暂安全表象；本章结尾会用night、smell与severed hand反转这种明亮。",
6:"rainbow来自Seven仪式中的crystal，既是宗教光学意象，也把sept与Jon稍后选择的dark grove并置。",
8:"排比反复You came to us，将差异巨大的来历压缩成共同过去；one house直接重写家族归属。",
9:"wash away既指法律赦免，也带宗教净化意味；获得新身份的代价是主动抹去旧爱与旧恨。",
10:"wife/mistress/sons的拟亲属语言说明Watch不是简单职业，而是用institutional family取代私人家庭。",
11:"先给退出机会、再说明desertion death，强调vow只有在说出前才可自由撤回。",
16:"Jon把faith写成blood inheritance；这既是个人信仰，也是他主动认同Stark lineage的方式。",
20:"Castle Black没有godswood并非缺失：越过Wall便进入未经Andal religion改造的古老森林。",
25:"Sam不是突然证明old gods更真实，而是对未回应祈祷的Seven失望，并把选择新神与选择新House绑定。",
26:"名单按organizational need与skills宣布；Jon只听到最后结果，尚未掌握Mormont点名的隐藏语境。源页的with,a为文本层/版面原样。",
27:"obsidian eyes把Alliser写得冷硬锋利；但‘and he knew’仍是Jon主观确信，不等于文本已证明Alliser决定分配。",
28:"源页印作master-at-arms took quite so happy，明显是原文件字符错误；为忠实校勘不擅自改成looked。",
31:"fat boy, a singer . . . and him以Jon带偏见的分类排列；源页此处印作Darcon，与同章Dareon不一致，按源页保留。",
33:"stewards不是只有家务：采购、贸易判断、communications和专业support都属后勤组织能力。源页frightful, Present的大写与逗号按原样保留。",
35:"Jon用问题列出care work，语气不是求知而是把这些任务预先定义为羞辱。",
38:"Aemon把争论从job rank转成identity：man of the Watch服从共同需要，而非只选择符合自我形象的职责。",
39:"churn butter、sew doublets与like a girl暴露Jon把战斗男性气质置于维持组织的劳动之上；文本让偏见属于人物，不要求读者认同。",
41:"Wall融水像hundred thin fingers；同一融化景象从p.472的sparkle变成rage中的侵蚀，环境随视角改义。",
44:"Lord Snow既指Jon的bastard name，也讽刺他表现出的lordly entitlement。",
46:"Dareon叙述是否完整真实尚不可核实；它的当前功能是表明Watch中多数人都认为自己受过不公。",
49:"Sam把相同任务重新框架：端酒与换床单没有消失，但因access、information与apprenticeship获得另一层意义。",
50:"groom you for command是Sam基于家族经验的合理推断，不是Mormont明说；证据是personal request与持续贴身参与。",
53:"一句短段让争论落在自我认识，不靠Mormont或Alliser解释；Jon成长首先表现为能修正自己的叙事。",
54:"summer smell承接全书逐渐逼近的winter motif；在Wall，心理上的summer意味着未经真正危险考验。",
58:"三重bars与twisting tunnel强调Wall既阻挡外敌，也严格控制brothers出入；穿越它具有阈限仪式感。",
64:"end of the world不是地图事实，而是集体文化边界的心理重量；cracking snow like bones把普通声音恐怖化。",
65:"bloodred／black rot／bone pale把life、decay、death叠在sacred grove，拒绝把old gods场所写成温和教堂。",
66:"carved faces不真的移动；they’re watching是Sam面对拟人树像的宗教感受，当前不能当超自然事实。",
68:"evenfall、grey to black把个人身份转换与Night’s Watch名字、职责统一起来。",
69:"vow以一连串第一人称比喻把brother变成sword、watcher、fire、light、horn、shield；个人生命被改写为防线功能。",
70:"boys to men是institutional declaration，不等于年龄、生理或成熟已瞬间改变；Jon此前认错使这一句具有额外心理分量。",
71:"Dywen依赖smell与forest experience感知危险，和officers依赖规则、Jon依赖视觉形成不同知识方式。",
72:"Ghost与weirwoods共享white/red色彩，建立视觉亲缘；like the trees是Jon联想，不揭示原因。",
73:"跨页原本是同一问句，已合并。黑色物体先被延迟命名，以认知悬置制造结尾惊骇。",
76:"hand既是具体尸体线索，也是切断、失去控制与未知来者的恐怖符号；本章只确认物体，不回答所属者或死亡经过。",
}

STAGES = [
(1,20,"Sam获准宣誓；sept仪式说明Night’s Watch以共同House、终身duty与death penalty重建成员身份。"),
(21,41,"Sam选择old gods后，八名recruits被分配orders；Jon因进入stewards而把organizational assignment体验为阶级羞辱。"),
(42,57,"Sam用personal steward的access与heir education经验重新解释安排，Jon承认自己幼稚并决定留下宣誓。"),
(58,70,"众人穿Wall进入haunted forest，在九棵weirwoods前完成vow；空间、日落与誓词共同完成身份转换。"),
(71,76,"Dywen预感夜气异常，Ghost带回一只hand，把成年仪式立刻接入Wall以北的真实危险。"),
]

BACKGROUNDS = {
7:"**三个orders：** rangers负责侦察与战斗，builders维护Wall与fortifications，stewards承担供给、照料、通信与管理；三者共同维持Watch。",
8:"**amnesty与new House：** 加入Watch可洗去旧罪债与社会身份，但成员也放弃原House的政治忠诚。",
11:"**desertion：** vow后擅离Watch是死罪；Jon此前已从Eddard处见过这一法律后果。",
16:"**First Men／old gods：** Starks传统上追溯First Men并在heart trees前敬old gods；Andals后来把Seven带入Westeros。",
20:"**Dawn Age：** 对极古年代的泛称；haunted forest被描述为早于Andal arrival的原始空间。",
23:"**House Tarly：** Sam出身Horn Hill的古老贵族House，传统信仰Seven；此处只说明其宗教传承。",
26:"**order assignment：** new brothers不自行选岗，由senior command按Watch需要和个人能力分配。",
32:"**rookery：** 饲养messenger ravens的地方；识字、写信与管birds是Watch跨fort通信关键。",
33:"**Eastwatch-by-the-Sea：** Wall东端港口，可与merchant galleys交易；steward需要管理采购质量与价格。",
34:"**personal steward：** 既做贴身日常服务，也可接触command messages、meetings与campaigns；具体培养意图仍是Sam推断。",
46:"**Dareon的来历：** 他曾称自己因与lord daughter事件被送到Wall；目前只有其自述，不能验证责任归属。",
50:"**heir education：** 贵族继承人常通过陪父亲听court、出访、议事学习rule；Sam以自己被Dickon取代的经历理解Jon安排。",
58:"**Wall passage：** Castle Black没有普通open gate；通道以多道iron bars和chains控制，Lord Steward掌keys。",
59:"**wildlings：** Wall以北不受Seven Kingdoms统治的人群；Sam把未知危险首先投射为他们。",
65:"**weirwood：** 白干、红叶、刻face的神圣树；heart tree通常是godswood宗教中心，九棵成圈极罕见。",
69:"**Night’s Watch vow：** 誓言明确终身服役、无婚姻土地后代与冠冕，并把brother定义为抵挡dark/cold的守护工具。",
73:"**当前事实边界：** Ghost带回黑色物体，随后确认是hand；其主人、是否来自失踪rangers及死因均尚未由本段证明。",
}

EXTRA_VOCAB = [
("break one’s fast","/breɪk wʌnz fæst/","phr.","吃早饭；结束夜间禁食","较古风的breakfast表达"),
("plop","/plɑːp/","v.","扑通坐下","plopped himself down"),
("summon","/ˈsʌmən/","v.","召唤；传唤","summoned to the sept"),
("weed-strewn","/ˈwiːd struːn/","adj.","杂草遍布的","courtyard"),
("rivulet","/ˈrɪvjələt/","n.","小溪流；细流","meltwater"),
("censer","/ˈsensər/","n.","香炉","swing a censer"),
("incense","/ˈɪnsens/","n.","熏香","fragrant incense"),
("resplendent","/rɪˈsplendənt/","adj.","华丽耀眼的","formal dress"),
("bearclaw","/ˈberklɔː/","n.","熊爪形饰件","Mormont fastening"),
("poacher","/ˈpoʊtʃər/","n.","偷猎者","outlaw recruit"),
("raper","/ˈreɪpər/","n.","强奸犯（旧式用词）","criminal category"),
("evenfall","/ˈiːvənfɔːl/","n.","黄昏","archaic/literary"),
("grudge","/ɡrʌdʒ/","n.","积怨","put aside grudges"),
("take the black","/teɪk ðə blæk/","phr.","加入Night’s Watch并终身服役","institutional idiom"),
("forsake","/fərˈseɪk/","v.","抛弃；背离","gods of your House"),
("aurochs","/ˈɔːrɑːks/","n.","原牛；大型野牛","herd of aurochs"),
("trample","/ˈtræmpəl/","v.","踩踏","into the snow"),
("league","/liːɡ/","n.","旧距离单位","half a league"),
("mayhap","/meɪˈhæp/","adv.","也许","古风用语"),
("sag","/sæɡ/","v.","身体垮下；下沉","with relief"),
("scrap","/skræp/","n.","小片；碎料","scrap of silk"),
("obsidian","/əbˈsɪdiən/","n.","黑曜石","eyes like flakes"),
("lantern-jawed","/ˈlæntərn dʒɔːd/","adj.","下颌突出瘦长的","facial description"),
("rookery","/ˈrʊkəri/","n.","鸟舍；此处为raven饲养处","messages"),
("palate","/ˈpælət/","n.","味觉；鉴别食物的能力","judge provisions"),
("galley","/ˈɡæli/","n.","桨帆船；商船","merchant galleys"),
("smallclothes","/ˈsmɔːlkloʊðz/","n.","内衣裤（古风）","washing clothes"),
("squire","/skwaɪər/","v.","作为侍从服侍","in battle"),
("wager","/ˈweɪdʒər/","v.","打赌；断定","I’ll wager"),
("groom for","/ɡruːm fɔːr/","v.","培养以备某职位","command"),
("green boy","/ɡriːn bɔɪ/","n.","缺乏经验的少年","green=unseasoned"),
("garron","/ˈɡærən/","n.","矮壮小马","northern pony"),
("whicker","/ˈwɪkər/","v.","马轻声嘶鸣","fear response"),
("lope","/loʊp/","v.","大步轻快奔跑","Ghost movement"),
("ominous","/ˈɑːmɪnəs/","adj.","不祥的","forest mood"),
("crust","/krʌst/","n.","硬薄层","thin snow crust"),
("grove","/ɡroʊv/","n.","小树林；圣林","weirwood circle"),
("defile","/dɪˈfaɪl/","v.","亵渎；玷污","sacred place"),
("twilit","/ˈtwaɪlɪt/","adj.","暮光中的","grove"),
("bear witness","/ber ˈwɪtnəs/","phr.","作证；见证","vow formula"),
("pledge","/pledʒ/","v.","郑重献出；保证","life and honor"),
("intone","/ɪnˈtoʊn/","v.","庄重而单调地说","ceremonial voice"),
("gnarled","/nɑːrld/","adj.","粗糙扭曲的；饱经风霜的","old forester"),
("mislike","/mɪsˈlaɪk/","v.","不喜欢；觉得不祥（古风）","night smell"),
("stalk","/stɔːk/","v.","悄无声息地逼近","Ghost movement"),
("disquieted","/dɪsˈkwaɪətɪd/","adj.","感到不安的","Jon reaction"),
("intake of breath","/ˈɪnteɪk əv breθ/","n.","猛吸一口气","shock"),
]
VOCAB = BASE_VOCAB + EXTRA_VOCAB

def extract_blocks():
    blocks = extract_range(472, 479, "JON", "CH48")
    # p.478 ends with “asked”; p.479 begins with the addressee and dialogue tag.
    blocks[72]["text"] = str(blocks[72]["text"]) + " " + str(blocks[73]["text"])
    blocks[72]["end_page"] = blocks[73]["end_page"]
    del blocks[73]
    for order, block in enumerate(blocks, 1):
        block["order"] = order
        block["id"] = f"CH48-P{int(block['page']):03d}-{order:03d}"
    return blocks

def main():
    blocks = extract_blocks()
    write_chapter(
        out=OUT, chapter=48, pov="JON", page_start=472, page_end=479,
        blocks=blocks, summaries=SUMMARIES, key_notes=KEY_NOTES, stages=STAGES,
        backgrounds=BACKGROUNDS,
        default_background="本段没有新增必须补充的世界观事实；重点是Night’s Watch的组织身份、Jon的主观判断与Wall以北逐步增强的危险感。",
        vocab=VOCAB,
        guide="Sam获准与Jon等人一起结束training，Mormont在sept说明Night’s Watch如何把outlaws、children、nobles与nameless men重塑为同一House。真正的冲突来自order分配：擅长剑术的Jon没有进入rangers，而被Mormont点名做personal steward。他先把care work理解成Alliser设计的阶级与性别羞辱；Sam则根据贵族heir旁听court的经验，提出这是让Jon贴身学习command的培养。文本只把后者写成证据充分的推断，并未让Mormont亲自确认。Jon接受纠正后与Sam越过Wall，在九棵weirwoods前宣誓；但身份成年礼刚结束，Dywen便嗅到异常，Ghost从黑暗中带回一只hand。institutional promise与北方未知危险在同一夜直接接合。",
        people=[
            ("Jon Snow","本章视角；被分到stewards、修正自己的荣誉观，并在old gods前宣誓"),
            ("Samwell Tarly","获准成为brother并协助Aemon；主动选择old gods，也帮助Jon重新理解assignment"),
            ("Jeor Mormont","Lord Commander；主持仪式并亲自点Jon为personal steward"),
            ("Maester Aemon","安排Sam进入library/rookery，并以man of the Watch提醒Jon服从共同需要"),
            ("Alliser Thorne","master-at-arms；其笑容令Jon相信steward分配是蓄意羞辱"),
            ("Bowen Marsh","Lord Steward；公布具体steward duties并带队到weirwood grove"),
            ("Dareon","singer出身的新steward，将派往Eastwatch负责贸易采购支持"),
            ("Dywen","经验丰富的老forester，首先从夜间气味察觉异常"),
            ("Ghost","Jon的direwolf；越过Wall后失踪片刻，最终衔回一只hand"),
        ],
        terms=[
            ("the three orders","rangers、builders、stewards；分别负责远征战斗、工程维护和组织后勤"),
            ("the Seven","Andal传统的七面一体信仰，仪式常在sept由septon主持"),
            ("old gods","与First Men、weirwoods、heart trees相连的古老信仰"),
            ("haunted forest","Wall以北紧邻Castle Black的广阔古林"),
            ("weirwood grove","九棵带carved faces的weirwoods围成、供Jon与Sam宣誓的圣地"),
            ("Eastwatch-by-the-Sea","Wall东端港口与Watch三座仍有人驻守的castle之一"),
        ],
        synthesis="Chapter 48写了两次‘重新命名’。在sept里，Mormont宣布罪犯、贵族、bastard与nameless men的旧身份都必须洗去，由Night’s Watch这个new House取代；在yard里，Jon却仍用旧世界的等级和男性荣誉判断岗位，把ranger等同价值、steward等同servant。Sam没有否认端酒、换床单这些实际劳动，而是指出贴身服务同时意味着information、access、squire experience与观察command。Jon的成长并非得到理想职位，而是学会承认自己的解释可能由pride塑造。第二次转换发生在weirwood grove：vow把boy宣布为man，把个人变成sword、fire与shield。然而小说不让仪式停留在庄严象征。Ghost带回hand，提醒他们誓言中的dark与cold并非修辞装饰；成为brother的当晚，未知威胁便要求誓言兑现。",
        contrasts=[
            "**sept rainbow／weirwood darkness：** Seven的折射光与old gods的血红、骨白、黑腐形成两种宗教空间。",
            "**one House／旧身份偏见：** Mormont宣布人人平等，Jon却仍以lordly、gendered标准排序劳动。",
            "**ranger skill／steward access：** visible combat ability与贴身学习command代表两种不同的能力路径。",
            "**Alliser’s hand／Ghost’s hand：** Jon先把assignment归因于Alliser操纵之‘手’，结尾出现真正断手，把私人怨气压到生存危机之下。",
            "**boys rise as men／unknown corpse：** ceremonial adulthood刚成立，死亡证据便立即检验其含义。",
            "**warm melting Wall／cold ominous forest：** 白昼安全表象逐步转入夜色、骨裂声与不祥气味。",
        ],
        questions=[
            "Mormont点Jon为personal steward，是否确如Sam推测是在培养未来command？",
            "Alliser是否实际影响了order分配，还是Jon因敌意把结果全部归咎于他？",
            "Ghost为何在进入haunted forest后立刻离队，它嗅到了什么？",
            "这只hand属于谁，附近是否还有尸体或活着的人？",
            "Dywen所说night smell异常与hand之间是什么关系？",
        ],
        extraction_notes="PDF pp.472–479校勘后共76段。自动提取把p.478末尾asked与p.479开头Bowen Marsh, frowning.误切，已合并；校勘后共3处跨页续段：pp.474–475、477–478、478–479。页面图像确认源页本身含with,a、master-at-arms took quite so happy、Darcon及frightful, Present等异常，为忠实原文均保留并在对应段落说明。",
    )
    print(f"Wrote Chapter 48 with {len(blocks)} paragraphs")

if __name__ == "__main__":
    main()
