#!/usr/bin/env python3
"""Build Chapter 44 (SANSA) close-reading Markdown."""
from pathlib import Path
from agot_extract import extract_range
from agot_reader_common import write_chapter
from build_agot_chapter43_reader import VOCAB as BASE_VOCAB

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/"outputs"/"AGOT_逐章精读"

S={
1:"冷晚餐时Sansa告诉Jeyne，Eddard不派Loras大概因为伤腿疼痛。",
2:"Eddard在bedchamber与guards、steward吃饭休腿，Mordane也脚痛，Arya仍在dancing lesson未归。",
3:"Jeyne误以为受伤的是Loras。",
4:"Sansa边优雅吃chicken leg边解释是Father腿痛使其易怒，否则必会选Loras。",
5:"Eddard拒绝Loras使Sansa困惑失望，因为她已把Gregor与Loras分别看成Old Nan故事里的monster与hero。",
6:"回忆中Littlefinger说Eddard有些决定值得question，并向Sansa深鞠躬，使她不确定被赞还是被嘲。",
7:"Mordane发现对话被听见很不安，急忙把Sansa意见贬成无意义闲聊。",
8:"Littlefinger追问Sansa为何会派Loras。",
9:"Sansa只得解释heroes与monsters；Littlefinger说life is not a song并触摸她cheek，预言她会悲伤学会。",
10:"这段回忆令Sansa不安，所以不告诉Jeyne。",
11:"Jeyne认为King’s Justice Ilyn才应受命。",
12:"Sansa看Ilyn就如有dead thing爬过裸肤，觉得他几乎是second monster，庆幸未选。",
13:"Jeyne说Beric同样勇敢有hero气质。",
14:"Sansa嫌二十二岁的Beric太老，更偏爱Loras，并以阶级和年龄判断steward daughter Jeyne的爱慕无望。",
15:"她不说破以免伤人，转而把希望Joffrey猎得white hart包装成prophetic dream，并认为他胜过醉酒father。",
16:"Jeyne问梦中Joffrey是否像songs那样徒手温柔触碰magic hart。",
17:"Sansa说Joffrey会以golden arrow杀鹿送她；她承认他爱killing，却坚信只杀animals、与Jory等死亡无关。",
18:"Jeyne突然说看见Arya在stables倒立行走。",
19:"Sansa厌恶stables与Arya行为，催Jeyne继续听court故事。",
20:"Jeyne表示想听。",
21:"Sansa讲old、smelly、crookbacked的Yoren来Wall征人，现实Night’s Watch破坏她对Benjen式black knights想象；无人自愿后Eddard给他挑dungeons prisoners。",
22:"Jeyne打哈欠，问有没有lemon cakes。",
23:"Sansa不喜欢被打断，却承认cakes比多数court事务有趣，提议去找。",
24:"两人没找到lemon cakes，却分吃cold strawberry pie、说笑秘密，Sansa觉得自己像Arya般小小越规。",
25:"次日黎明Sansa看Beric队伍在king、Stark、Beric三旗前出发，把武器、torch、banner和horse看成song成真。",
26:"Alyn执Stark banner与Beric交谈使她骄傲；她认为比Jory英俊且将成为knight。",
27:"men离开后Tower空荡，Sansa早餐时甚至高兴见Arya；Arya问是否去追Jaime。",
28:"Sansa说队伍去斩Gregor，问Mordane会把head挂其gate还是带回king。",
29:"Mordane震惊，训诫lady不应在porridge前谈处刑，并说Sansa近来快像Arya。",
30:"Arya问Gregor做了什么。",
31:"Sansa说他烧holdfast并杀了许多妇女儿童。",
32:"Arya指出Jaime杀Jory等、Hound杀Mycah，他们也应被斩首。",
33:"Sansa坚持不同，重复Hound是Joffrey sworn shield且Mycah袭击prince的官方说法。",
34:"Arya骂她liar，用力捏blood orange至红汁流出。",
35:"Sansa用未来queen身份威胁Arya必须bow；Arya把orange砸中她额头与衣裙。",
36:"Arya以Your Grace反讽她脸上沾juice。",
37:"Sansa发现ivory silk dress染红，愤怒说应该杀Arya而非Lady。",
38:"Mordane起身宣布会报告Eddard，命姐妹立刻回房。",
39:"Sansa含泪问自己是否也被罚，认为不公平。",
40:"Mordane拒绝讨论，命她走。",
41:"Sansa昂首离开、坚持queen不当众哭，回房却因红渍透到underskirt而失控脱衣哭睡。",
42:"中午Mordane敲门，通知Eddard召见。",
43:"Sansa从与Lady奔跑的dream醒来，只剩模糊rain般抓不住的记忆，重新意识direwolf已死。",
44:"Mordane再次急敲门确认她听见。",
45:"Sansa礼貌请求时间穿衣，并努力把哭红的自己整理得beautiful。",
46:"Eddard带cast坐在solar读huge leather-bound book，温和让Sansa坐身边并合书。",
47:"Mordane抓着挣扎Arya回来；Sansa换green damask和remorse表情，Arya仍穿旧leathers。",
48:"Eddard感谢Mordane并要求单独同daughters谈。",
49:"Sansa抢先控诉Arya叫她liar、扔orange、毁Cersei所赠订婚dress，并说Arya嫉妒一切beauty。",
50:"Eddard不耐烦地叫Sansa够了。",
51:"Arya主动认错并请求sweet sister原谅。",
52:"Sansa惊讶到失语，恢复后首先问dress怎么办。",
53:"Arya犹豫提出帮她洗。",
54:"Sansa说silk无论怎样scrub都无法恢复。",
55:"Arya又提出做new dress。",
56:"Sansa蔑视Arya针线，说她连清pigsties的dress都缝不好。",
57:"Eddard打断dress争论，宣布两人都回Winterfell。",
58:"Sansa第二次震惊无言，眼睛又湿。",
59:"Arya说Eddard不能这样。",
60:"Sansa终于请求Father不要送走。",
61:"Eddard疲惫笑说姐妹总算有一致意见。",
62:"Sansa以自己没做错为由求留下，列举court服饰、city、tourney、feasts、balls和shows，并许诺像queen般高贵。",
63:"Eddard解释不是惩罚争吵，而是为安全：三名men近处被杀，Robert却去hunt。",
64:"Arya咬唇问能否带Syrio回去。",
65:"Sansa斥Syrio无关，拿与Joffrey婚约阻止离开，并用Naerys–Aemon、Jonquil–Florian故事宣称爱情和生子愿望。",
66:"Eddard温和承诺将来给她找worthy high lord，直说Joffrey婚约是错误、他不是Prince Aemon。",
67:"Sansa拒绝替代，坚信songs式幸福和golden-haired son将成为wolf般勇、lion般傲的great king。",
68:"Arya说Joffrey是liar、craven，而且父系纹章应是stag而非lion。",
69:"Sansa哭喊Joffrey一点也不像old drunken king，无意说出更尖锐的父子差异。",
70:"Eddard因姐妹童言突然领悟某事，立即安排秘密乘trading galley回家，可带Mordane、guards及愿受雇的Syrio。",
71:"下楼时Sansa哭，觉得court、tournaments与prince全被夺走，Winterfell是永远囚禁。",
72:"Mordane叫她停止哭，信任Father知道什么最好。",
73:"Arya安慰航海会是adventure，回家还能见Bran、Robb、Old Nan、Hodor，并触碰她手臂。",
74:"Sansa以Hodor羞辱Arya，挣脱后冲回bedchamber锁门。",
}
SUMMARIES=[S[i] for i in range(1,75)]

KEY_NOTES={
1:"Sansa用Eddard leg pain解释不合hero story的决定，把复杂司法判断归因于情绪；这保护了她对Loras应被选中的信念。",
4:"chicken leg与Father’s leg形成轻微文字呼应；她优雅nibble时讨论父亲剧痛，显示经验距离。",
5:"monster/true hero二分来自stories，不包含Beric队伍规模、Loras vengeance动机或Gregor拒捕可能性。",
6:"Littlefinger深bow同时像courtly compliment和讽刺，Sansa无法判读正是其语言优势。",
7:"Mordane急称foolish chatter是保护Sansa免court后果，也教她贵族女孩观点必须被迅速收回。",
9:"Life is not a song可能是准确警告，却由成年councillor在未经邀请触碰十一岁女孩时说出；权力与身体边界令场景不安。",
10:"Sansa选择不讲不是忘记，而是回忆本身令她uneasy；她的感知已发出警报，即使尚不能命名原因。",
12:"slithering dead thing是强烈身体直觉；她对Ilyn危险感比对Littlefinger暧昧话术更容易识别。",
14:"Sansa看得出Jeyne婚配阶级障碍，却看不出自身婚约也受政治利益而非song love控制。",
15:"wish改称dream再用everyone knew证明prophetic，是motivated reasoning的小链条：先要结论，再升级证据地位。",
17:"她调整song规则以容纳Joffrey真实爱杀戮：magic beast仍可被golden arrow杀，只要结局是献给自己。",
21:"Yoren外貌击碎black knight想象；Sansa短暂同情Jon，却仍主要用审美判断institution。",
23:"她承认lemon cakes更有趣，显示上一章重大petitions在儿童court体验中也会被食物迅速替代。",
24:"almost as wicked as Arya说明Sansa渴望小幅越规，却只在安全、甜食和同龄秘密范围内接受。",
25:"她只看见banners与mail的exciting form，看不见队伍可能面对Gregor及Tywin的死亡风险。",
26:"Alyn比刚死的Jory更handsome成为评价焦点；悲伤被新hero image快速覆盖，不等于她无情，而是叙事模板在组织注意。",
28:"head去向已变成姐妹昨夜argument，真实处刑被courtly curiosity游戏化。",
29:"Mordane训的是餐桌courtesy，不是处刑伦理；这会教孩子隐藏暴力话题，而非理解暴力。",
32:"Arya用熟人具体死亡测试法律一致性：若Gregor该死，为何Jaime与Hound不受同样justice。",
33:"Sansa重复Mycah attacked prince的权威叙事，尽管她亲历river事件；维护Joffrey需要继续压制自己知道的细节。",
34:"blood orange把争论视觉化为血：握得越紧，红汁越像被压出的证词。",
35:"Sansa用future institutional power结束事实争论；Arya的orange以滑稽方式把imagined queen拉回早餐桌。",
37:"They should have killed you instead of Lady把积压哀伤武器化，攻击Arya最深责任伤口，也暴露Sansa仍未处理Lady之死。",
41:"queen不哭的表演只能维持到关门；public composure与private collapse构成她全部情绪教育。",
43:"Lady dream恢复两者共同奔跑的自由，醒来后trying to catch rain表现记忆与bond无法被意志留住。",
45:"make herself beautiful是Sansa面对冲突的armor；她修复可见外表，无法修复悲伤与安全。",
47:"green damask + look of remorse与ratty leathers形成姐妹不同的presentation politics；衣服不等于实际悔意。",
49:"Sansa抢first word不是只求事实，而是抢占story frame：dress由queen赠送，把财物损害升级为婚约与beauty受攻击。",
51:"Arya突然道歉显示她可能读出Father疲惫或更大危机；也使Sansa准备好的攻防脚本失效。",
52:"What about my dress?表明Sansa把apology理解为需要material repair，而非关系结束争执。",
56:"Arya连续提repair，Sansa连续否定并羞辱技能；此时她要的已不只是dress，而是确认受害与优越位置。",
57:"离城announcement让早餐事件瞬间失去尺度，Eddard召见真正目的不是discipline而是security evacuation。",
61:"幽默短暂标出姐妹深层一致：两人都不想被成年人无协商改变生活。",
62:"源页印作Mng’s Landing；按原文保留。Sansa列举的是spectacle与未来活动，不包括上一章villagers所经历的city政治代价。",
63:"Robert goes hunting再次成为治理缺席证据；Eddard不向孩子透露全部调查，只给足以解释危险的近处死亡。",
64:"Arya第一反应是能否带mentor，说明她衡量迁移时关心relationship continuity，而非city spectacle。",
65:"Sansa用历史romance为自己的感觉提供script；want babies把婚约想象成完整成人身份，却尚未理解政治与Joffrey行为风险。",
66:"Eddard不只是取消trip，而正式撤回royal match；terrible mistake是对Robert alliance最严重的私人转向。",
67:"golden hair、wolf、lion把child、Stark、Lannister symbols拼成理想继承人，却遗漏Baratheon stag。",
68:"Arya用heraldry常识纠错：作为Robert legal son，Joffrey应首先是stag；这句话与Eddard调查的genealogy产生意外连接。",
69:"Sansa说not like king本想赞Joffrey，却进一步强调父子不相似；信息价值来自她未意识到自己在提供clue。",
70:"out of mouth of babes表示儿童无意说出成人忽略的真相。Eddard反应表明得到线索，但本段尚未说明完整结论。",
71:"Sansa把回Winterfell理解为lock forever，安全措施在其视角中成为identity death；情感真实不等于风险判断准确。",
73:"Arya努力把共同失去改写成adventure与reunion，并主动touch；这是争吵后明确和解尝试。",
74:"Sansa以Hodor的认知、外貌作侮辱，既伤Arya也贬低Hodor；锁门重复她以封闭空间控制无法控制的离开。",
}

STAGES=[
(1,17,"Sansa与Jeyne讨论Eddard为何不派Loras，并把court judgment、white hart与Joffrey重新写进hero song逻辑。"),
(18,26,"她讲述Yoren等court琐事、偷吃pie，并在黎明把Beric队伍出发观看成song come to life。"),
(27,41,"早餐时姐妹用Gregor、Jaime、Hound和Mycah争论justice；blood orange引爆Lady创伤、queen权力和dress冲突。"),
(42,61,"Lady梦后两人被Eddard召见；Arya道歉仍未修复dress争执，Eddard突然宣布为安全送她们回Winterfell。"),
(62,74,"Sansa以King’s Landing spectacle和Joffrey婚约抗拒；姐妹关于stag/lion及父子相似的话触发Eddard洞见，秘密撤离计划确定。"),
]

BACKGROUNDS={
1:"**上一章判决：** Eddard拒绝主动请命的Loras，改派Beric率约百人执行对Gregor的王室判决。",
6:"**Littlefinger位置：** king councillor、Master of Coin与Catelyn childhood acquaintance；Sansa约十一岁，双方年龄与court authority极不对等。",
9:"**边界说明：** 文本只写Littlefinger触摸Sansa cheek并说警告；可确认她uneasy，不能由此段单独确定其全部意图。",
11:"**King’s Justice：** Ser Ilyn是正式royal executioner；Eddard因其House Payne向Lannister fealty而绕过他。",
15:"**white hart：** 稀有白鹿，在songs中常具magic与纯洁意义；Robert、Joffrey等正随court hunt。",
21:"**Yoren：** Night’s Watch recruiter，可从king’s dungeons挑愿take the black的囚犯补充Wall人手。",
25:"**三面旗：** crowned stag表示Robert authority，direwolf表示Eddard/Stark guards，forked lightning是Beric personal sigil。",
32:"**未受审案件：** Jaime已离城，Hound杀Mycah曾由Robert以Lady之死结束争端；Arya认为两者均未获得同等justice。",
33:"**river事实：** Sansa当时目击Mycah没有攻击Joffrey，却在公开场合说记不得；如今仍使用Joffrey版本。",
37:"**Lady：** Sansa direwolf因Nymeria逃走而被Robert命Eddard处死；姐妹都以不同方式承受责任与哀伤。",
43:"**direwolf dream：** 本段只确认Sansa梦见与Lady奔跑并感到sad knowing gaze，不解释dream是否超自然。",
46:"**huge book：** Eddard此前借grand tome查阅great houses婚配与children外貌记录；本段未显示当前具体页。",
57:"**撤离决定：** Eddard认为King’s Landing已无法保护daughters，计划让两人及household护送回Winterfell。",
65:"**romance pairs：** Naerys–Aemon与Jonquil–Florian是Sansa用来理解理想爱情的historical/legendary models。",
68:"**heraldry：** Robert属House Baratheon，sigil为crowned stag；Cersei属Lannister，sigil为lion。",
70:"**保密路线：** Eddard寻fast trading galley，因当前kingsroad更危险；离城计划不得外泄。",
}

EXTRA_VOCAB=[
("bewilder","/bɪˈwɪldər/","v.","使困惑不解","Eddard decision"),("tumble","/ˈtʌmbəl/","v.","垂落；翻滚","hair"),("sweeping bow","/ˈswiːpɪŋ baʊ/","n.","夸张而优雅的鞠躬","Littlefinger"),("sweetling","/ˈswiːtlɪŋ/","n.","小甜心；亲昵称呼","adult to child"),("slither","/ˈslɪðər/","v.","蜿蜒滑行","dead thing"),("moon after","/muːn ˈæftər/","v.","痴痴爱慕","Jeyne"),("prophetic","/prəˈfetɪk/","adj.","预言性的","dream"),("hart","/hɑːrt/","n.","成年雄鹿（古风）","white hart"),("crookbacked","/ˈkrʊkbækt/","adj.","驼背的","Yoren"),("lice","/laɪs/","n.","虱子，louse复数","appearance"),("yield","/jiːld/","v.","提供；产出","kitchen"),("form up","/fɔːrm ʌp/","v.","列队集结","Beric men"),("clatter","/ˈklætər/","n.","铿锵碰撞声","swords"),("portcullis","/pɔːrtˈkʌlɪs/","n.","城门铁闸","departure"),("rein in","/reɪn ɪn/","v.","勒马停下","Alyn"),("break one’s fast","/breɪk wʌnz fæst/","v.","吃早餐（古风）","morning"),("porridge","/ˈpɔːrɪdʒ/","n.","麦片粥","breakfast"),("horror-struck","/ˈhɔːrər strʌk/","adj.","惊骇万分的","Mordane"),("ooze","/uːz/","v.","缓慢渗出","orange juice"),("airily","/ˈerli/","adv.","故作轻松地","Sansa"),("plop","/plɑːp/","v.","扑通落下","orange"),("lurch","/lɜːrtʃ/","v.","猛然踉跄起身","Mordane"),("blotchy","/ˈblɑːtʃi/","adj.","斑驳成块的","stain"),("hearth","/hɑːrθ/","n.","壁炉炉床","cold ashes"),("rap","/ræp/","n.","急促敲门声","Mordane"),("damask","/ˈdæməsk/","n./adj.","锦缎；锦缎制的","green gown"),("roughspun","/ˈrʌfspʌn/","n./adj.","粗纺布；粗布制的","Arya clothes"),("remorse","/rɪˈmɔːrs/","n.","悔意","look"),("scrub","/skrʌb/","v.","用力刷洗","silk"),("pigsty","/ˈpɪɡstaɪ/","n.","猪圈","insult"),("squabble","/ˈskwɑːbəl/","v.","为小事争吵","sisters"),("pageantry","/ˈpædʒəntri/","n.","华丽仪式与排场","court"),("mummer show","/ˈmʌmər ʃoʊ/","n.","巡回艺人表演","future event"),("craven","/ˈkreɪvən/","n./adj.","懦夫；怯懦的（古风）","Joffrey"),("complement","/ˈkɑːmpləmənt/","n.","规定配备的一组人员","guards"),("galley","/ˈɡæli/","n.","桨帆船","sea route"),("motivated reasoning","/ˈmoʊtəveɪtɪd ˈriːzənɪŋ/","n.","动机性推理","interpretive term"),
]
VOCAB=BASE_VOCAB+EXTRA_VOCAB

def main():
    blocks=extract_range(433,440,"SANSA","CH44")
    write_chapter(
        out=OUT,chapter=44,pov="SANSA",page_start=433,page_end=440,
        blocks=blocks,summaries=SUMMARIES,key_notes=KEY_NOTES,stages=STAGES,
        backgrounds=BACKGROUNDS,
        default_background="本段没有新增必须补充的世界观事实；重点在Sansa视角过滤、song逻辑、姐妹创伤与Eddard秘密撤离决定。",
        vocab=VOCAB,
        guide="Sansa把Eddard拒绝Loras解释为伤腿带来的cross mood，因为这比承认justice不按hero–monster故事运作更容易。Littlefinger告诉她life is not a song，却以含混赞美和越界触碰令她不安；她随后继续把white hart、Joffrey、Beric队伍与court排场改写成song。早餐争论则让两个视角正面碰撞：Arya用Jory、Mycah等具体死者质问法律不一致，Sansa维护Joffrey版本并以future queen权力压制事实，blood orange最终引爆Lady之死。Eddard宣布秘密送女儿回Winterfell、撤回Joffrey婚约时，Sansa把安全撤离体验为人生被夺走。讽刺的是，她与Arya关于stag、lion及Joffrey不像Robert的童言，反而使Eddard从桌上的genealogy问题中突然获得新线索。",
        people=[
            ("Sansa Stark","本章视角；以songs、beauty和future queen身份理解court、Joffrey与离城危机"),
            ("Arya Stark","Sansa sister；以Jory、Mycah等具体经验挑战官方叙事，并试图在离城消息后和解"),
            ("Eddard Stark","两人father；撤回Joffrey婚约、秘密安排海路回Winterfell，并因童言得到线索"),
            ("Jeyne Poole","Sansa同龄friend与聊天对象，分享court gossip和食物"),
            ("Septa Mordane","girls governess，强调courtesy、服从与公开情绪控制"),
            ("Petyr Baelish","king councillor；赞美、追问并触碰Sansa，留下含混警告"),
            ("Joffrey Baratheon","Sansa betrothed；被她套入ideal prince故事，却被Arya称liar与craven"),
            ("Beric Dondarrion / Loras Tyrell","现实受命执行者与Sansa偏爱的song hero"),
            ("Lady","Sansa已死direwolf，在梦中与她再次奔跑"),
        ],
        terms=[
            ("white hart","稀有雄白鹿，在court hunt与songs中被赋予magic意义"),
            ("King’s Justice","王室正式executioner office，由Ser Ilyn Payne担任"),
            ("take the black","加入Night’s Watch并终身服役"),
            ("trading galley","Eddard准备秘密雇用、带girls海路北返的商用桨帆船"),
            ("stag and lion","Baratheon与Lannister家族纹章，也是童言触发genealogy线索的关键对照"),
        ],
        synthesis="Chapter 44不是简单证明Sansa‘天真’，而是展示一个孩子如何主动修补世界观。每当现实违背song，她就找到补丁：Father因腿痛才不选Loras；Joffrey虽爱killing但只伤animals；Mycah一定袭击过prince；回Winterfell一定是早餐争吵惩罚。这样的解释保护她的婚约、身份与未来想象，也迫使她压下自己在river亲眼看见的内容。Arya同样冲动，却不断把抽象justice拉回具体死者。两人最残酷的话都来自共同创伤：Lady、Mycah、Jory和被改变的家。Eddard试图以秘密撤离保护她们，却没有时间帮助Sansa重建失去的未来故事，因此安全在她感受中只像囚禁。最后，正因Sansa仍忠于beauty与lineage语言，她无意说出的父子不相似反而成为成人调查所需的clue。",
        contrasts=[
            "**hero–monster song／state enforcement：** Sansa想看Loras单人屠龙式出征，Eddard派王旗百人执行判决。",
            "**public queen composure／private sobbing：** 礼仪教她隐藏泪水，却不教她处理悲伤。",
            "**blood orange／Lady blood memory：** 早餐闹剧的红渍触发姐妹未解决的死亡责任。",
            "**green damask／ratty leathers：** 姐妹用截然不同外观进入同一父权谈话。",
            "**court pageantry／nearby murder：** Sansa留恋排场，Eddard看到三名men在不到一league处被杀。",
            "**lion child fantasy／stag heredity：** 她理想化的golden-haired son无意暴露自己对Joffrey外貌归属的真实直觉。",
        ],
        questions=[
            "Eddard从Sansa与Arya的stag/lion争论中究竟得出了什么结论？",
            "秘密trading galley能否在计划泄露前带girls安全离城？",
            "Sansa会否接受Joffrey婚约已被Eddard撤回？",
            "Littlefinger为何对Sansa说life is not a song，他的触碰与警告意图何在？",
            "姐妹能否在共同返乡前修复围绕Lady、Mycah和Joffrey的裂痕？",
        ],
        extraction_notes="PDF pp.433–440校勘后共74段；共3处跨页续段：pp.437–438、438–439与439–440，无额外人工合并。页面图像确认p.433章首原本缺开引号，p.434印作Jcyne，p.438印作Mng’s Landing，均按源页保留并在精读中注明；段落顺序与说话人已复核。",
    )
    print(f"Wrote Chapter 44 with {len(blocks)} paragraphs")

if __name__=="__main__":
    main()
