#!/usr/bin/env python3
"""Build Chapter 13 (TYRION) close-reading Markdown."""

from pathlib import Path

from agot_extract import extract_range
from agot_reader_common import write_chapter
from build_agot_chapter12_reader import VOCAB as BASE_VOCAB

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs" / "AGOT_逐章精读"

SUMMARIES = [
    "北方仿佛永远没有尽头。",
    "Tyrion熟悉地图，却在荒野kingsroad上骑行两周后切身体会到地图与真实土地完全不同。",
    "他们与国王同日离开Winterfell；南行王室车队带走旗帜、马车和喧闹，Tyrion则与Benjen及Jon转向北方。",
    "从分道开始，天气变得更冷，周围也安静得多。",
    "道路西侧是燧石丘与瞭望塔，东侧是平原、河流和围绕holdfasts的农场；起初交通繁忙，夜间仍有简陋旅店。",
    "三天后农田让位给密林，道路渐趋孤寂；第五天燧石丘已变成肩披积雪、向北风扬起冰晶的群山。",
    "道路沿山墙穿入古老黑暗的wolfswood；夜间狼群嚎叫，Ghost只竖耳倾听而从不回应，令Tyrion不安。",
    "队伍如今有八人及Ghost；Yoren带着两名因强奸罪被送往Wall的农家少年加入，Wall对他们而言比阉割更可取。",
    "五名成人、三名少年、一只direwolf、二十匹马和一笼ravens组成一支奇特旅伴。",
    "Tyrion发现Jon看着邋遢、有虱子、气味难闻的Yoren及两个粗暴愚笨的新兵，脸上露出近似失望的神情。",
    "Tyrion推测Jon误以为Night’s Watch都由Benjen那样的人组成，而Yoren等人是粗暴的现实提醒；他同情Jon选择了、或被选择了一种艰苦人生。",
    "Tyrion对Benjen较少同情，因为Benjen同样厌恶Lannisters，也不欢迎他同行，曾警告Wall没有旅店。",
    "Tyrion以自己的身材开玩笑，说Benjen总能找到一处小地方安置他。",
    "Benjen无法公开拒绝queen的兄弟，只得接受，但一路努力兑现“你不会喜欢这段旅程”的警告。",
    "第一周末Tyrion大腿磨破、腿部抽筋并冷入骨髓，却拒绝抱怨，不肯让Benjen获得满足。",
    "Tyrion接受Benjen原以为他会礼貌谢绝的破旧熊皮作为小小报复；他发现最暖衣服仍不够，宣称Lannisters从不谢绝，他们拿走别人提供的东西。",
    "随着队伍深入wolfswood，农场和holdfasts愈发稀少，最后完全没有屋顶可借宿，只能依靠自身资源。",
    "Tyrion因身材与行动限制无法有效搭营，便在他人建棚、照料马匹和生火时带着毛皮、酒袋独自阅读。",
    "旅程第十八夜，他带着Summer Isles甜酒，阅读从Winterfell图书馆借来的dragon历史与性质研究。",
    "Tyrion在冰冷溪流和古老橡树旁阅读dragonbone：它因含铁而黑，像钢般强却更轻、更柔韧且不怕火，制成的Dothraki弓射程胜过木弓。",
    "Tyrion对dragons有近乎阴郁的迷恋；初到King’s Landing参加Cersei婚礼时，他坚持寻找被Robert从throne room撤下、存入潮湿地窖的龙骨。",
    "他原以为龙骨会威严或可怕，却发现它们极美：黑如onyx、表面光滑，在火把下闪烁；他甚至感觉空眼窝注视自己离开。",
    "地窖共有十九具龙骨，最古老超过三千年；最后两只Dragonstone幼龙的头骨只有mastiff大小且畸形，它们死得很早。",
    "头骨逐渐增大到Aegon及姐妹征服Seven Kingdoms时的Balerion、Meraxes和Vhaghar；其巨口足以容纳马匹、aurochs甚至mammoth。",
    "Tyrion一直凝视Balerion巨大空洞的头骨，直到火把将熄，努力想象它活着展开黑翼、喷火飞过天空的样子。",
    "Tyrion的远祖King Loren与King Mern曾联合抵抗Targaryen征服，集结远超Aegon的军队；当时Seven Kingdoms仍是独立王国而非统一王国的行省。",
    "两王军在Reach麦田发动冲锋，Targaryen军队一度崩溃，征服似乎即将结束，直到Aegon和姐妹亲自加入战斗。",
    "那是Vhaghar、Meraxes和Balerion唯一一次同时投入战斗，歌者称之为Field of Fire。",
    "近四千人被烧死，包括King Mern；King Loren逃过火焰、投降效忠并留下后代，Tyrion对此心怀感激。",
    "Jon突然询问Tyrion为什么读这么多书。",
    "Tyrion抬头，让Jon观察自己并说出看见了什么。",
    "Jon怀疑这是圈套，只谨慎回答他看见Tyrion Lannister。",
    "Tyrion说Jon作为bastard过于礼貌，并主动指出真正显眼的是自己是dwarf，随后询问Jon年龄。",
    "Jon回答自己十四岁。",
    "Tyrion解释自己的短腿、特殊马鞍、无法成为剑士以及出身对命运的影响；Lannister身份要求他为家族做贡献，所以他把mind当作weapon，而books像whetstone一样保持它的锋利。",
    "Jon沉默消化长篇回答；Tyrion观察他拥有Stark式的严肃、戒备面容，随后Jon追问他在读什么。",
    "Tyrion回答自己正在读dragons。",
    "Jon以少年特有的确信问这有什么用，因为dragons已经不存在。",
    "Tyrion说人们确实如此声称，又遗憾地回忆自己在Jon这个年龄曾梦想拥有一条dragon。",
    "Jon怀疑地追问，因为担心Tyrion正在取笑自己。",
    "Tyrion承认曾幻想骑dragon俯视世界，还在Casterly Rock地下生火想象dragonfire，有时幻想火烧父亲或姐姐；他笑着断言Jon也做过类似报复梦。",
    "Jon惊恐否认，声称自己不会这样想。",
    "Tyrion用反讽逐一攻击Jon的家庭处境：Catelyn是否真把他当亲子、Robb继承Winterfell而他得到Wall、Eddard为何把他送走。",
    "Jon愤怒命令他停止，并坚持Night’s Watch是一项高贵召唤。",
    "Tyrion笑称Jon太聪明，不该相信这种美化；他把Night’s Watch描述为收纳农民、欠债者、偷猎者、强奸犯、盗贼与bastards的垃圾堆，并用粗俗笑话拆解怪物与独身誓言。",
    "Jon尖叫着让他住口，握紧拳头向前一步，几乎哭出来。",
    "Tyrion突然感到愧疚，向前走想拍拍Jon肩膀或低声道歉。",
    "Tyrion没看见Ghost如何冲来，下一刻已被扑倒在石地，书本飞开、口中尽是泥土与血；背部痉挛后他艰难坐起并向Jon伸手求助。",
    "Ghost无声地挡在二人之间，只以红眼和牙齿阻止Tyrion靠近；Tyrion只得放弃求助，说会坐到它离开。",
    "Jon抚摸Ghost并露出笑容，要求Tyrion礼貌地请求帮助。",
    "Tyrion压下盘旋的愤怒，承认自己也许活该，并温和正式地请求Jon相助。",
    "Jon让Ghost坐下，从背后轻松扶起Tyrion，又捡回书交给他；Ghost的红眼始终没有移开。",
    "Tyrion擦去口边血土，斜看direwolf，询问它为何攻击自己。",
    "Jon说Ghost也许把Tyrion当成了grumkin。",
    "Tyrion先锐利地看他，随即无法控制地大笑，承认自己确实有些像grumkin，又问Ghost如何对付snarks。",
    "Jon说Tyrion不会想知道，并把酒袋捡起交给他。",
    "Tyrion饮下像清凉火焰般温暖腹部的酒，再把酒袋递给Jon。",
    "Jon小心喝了一口，随后问Tyrion对Night’s Watch的描述是否真实。",
    "Tyrion点头确认。",
    "Jon绷紧嘴角说，如果现实就是这样，他就接受它。",
    "Tyrion称赞他，说大多数人宁愿否认艰难真相，也不愿面对。",
    "Jon回答大多数人会那样，但Tyrion不会。",
    "Tyrion承认自己很少再梦见dragons，并说dragons确实已不存在，随后提议在Benjen召集军队找人前回营。",
    "返程虽短却崎岖，Tyrion再次腿部抽筋；Jon伸手扶他跨过树根，他拒绝并坚持像一生那样自己前行，回营后立刻品尝炖汤并要求加胡椒。",
    "Benjen从与Jon共用的棚屋出来，责骂Jon独自离开，声称以为Others把他抓走了。",
    "Tyrion笑称其实是grumkins，Jon也微笑；Benjen和Yoren无法理解他们新形成的共同笑话。",
    "众人围火吃加入松鼠肉的炖菜、黑面包和硬奶酪，Tyrion分享酒，直到Yoren也变温和；Jon承担第一班夜哨。",
    "Tyrion最后入睡，走进棚屋前回头看Jon，少年站在火旁，表情坚硬沉静，深深凝视火焰。",
    "Tyrion带着悲伤微笑，随后去睡觉。",
]

KEY_NOTES = {
    1: "五词首句把辽阔感写成时间和心理体验；“forever”不是地图事实，而是连续骑行后的身体判断。",
    2: "地图／土地对照建立本章认识论：抽象知识有用，却无法替代身体经过；这也预示Jon对Night’s Watch想象与现实的差距。",
    3: "分岔处南行车队带走“tumult”，北行者进入安静；道路方向同时成为社会中心与边缘的分离。",
    4: "极短段落用cold和quiet两个感官词完成世界收缩，北行从旅行转为隔离。",
    6: "山峰被人格化为披雪巨人，冰晶像旗帜；自然景观借用军队语言，显得庄严又潜藏威胁。",
    7: "Ghost听见狼群却从不回应，无声比嚎叫更令Tyrion不安；动物没有按他熟悉的群体信号行动。",
    8: "Yoren一句“Rapers”冷冷压缩两名少年的过去；Wall在这里不是荣誉选择，而是对刑罚的替代。",
    10: "Jon的“dismay”来自外在细节：气味、虱子、补丁与愚钝；崇高机构首先以身体和阶级现实击中他。",
    11: "Tyrion先说Jon“选择”艰苦生活，随即修正为生活“被替他选择”；被动语态承认bastard身份限制了自由。",
    13: "Tyrion把身材污名转成空间笑话，用抢先自嘲抵消Benjen居高临下的拒绝。",
    15: "不抱怨不是没有痛苦，而是不肯给Benjen“满足”；Tyrion常把忍耐理解为人际对抗中的胜利。",
    16: "接受熊皮既是生存理性也是小报复；“Lannisters took what was offered”把个人厚脸皮扩大成家族格言。",
    18: "“too small, too hobbled, too in-the-way”模仿他人可能给Tyrion的评价，他则把无法做营地劳动转成独处阅读的习惯。",
    19: "Summer Isles甜酒与dragon学术书把南方奢侈、个人享受和知识兴趣带入寒冷边境。",
    20: "dragonbone条目展示阅读不是纯幻想，它提供材料学、武器性能与Dothraki用途等具体知识。",
    21: "“morbid fascination”既指dragons已经灭绝，也指Tyrion主动走进潮湿地窖凝视死亡遗骨。",
    22: "龙骨从“可怕”转成“美丽”，空眼窝又似乎回望；Tyrion面对遗骸时把知识观察和想象投射混在一起。",
    23: "越晚近的dragons反而越小、越畸形、越短命，头骨序列在空间中可视化一个物种的衰退。",
    24: "巨口尺寸以马、aurochs和mammoth递增类比，将歌谣中的传奇重新换算成可想象的身体尺度。",
    27: "两王军一度令Targaryen军“shivered and shattered”，连续音强化崩溃感；胜利幻觉只持续到三条dragon入场。",
    28: "一句话独立命名Field of Fire，历史在极简句中从军队规模转为单次技术性压倒优势。",
    29: "Tyrion对King Loren活下来并生子“心怀感激”是干燥幽默：宏大战史最终与叙述者自身存在相连。",
    31: "Tyrion不直接回答阅读问题，而让Jon先看他的身体；解释从他人最先看见的限制开始。",
    33: "“remarkably polite for a bastard”同时是挑衅和测试；Tyrion主动说出dwarf，拒绝Jon用礼貌绕开显眼事实。",
    35: "整段论证从身体限制、阶级命运和家族义务走向mind/weapon比喻；books/whetstone把阅读定义为持续训练，不是逃避现实。",
    36: "Jon有Stark的脸却没有Stark的姓，外貌归属与法律排除同时存在。",
    38: "Jon的“easy certainty of youth”不是无知嘲笑，而是少年容易把社会共识当成已终结事实。",
    41: "dragon幻想让矮小孩子获得绝对高度；烧父亲或姐姐的想象暴露Tyrion的伤害经验，也故意逼Jon承认自己的怨恨。",
    43: "Tyrion的反讽逐项击中Jon最敏感的事实，目的像拆幻想，手段却是利用私人伤口。",
    45: "Night’s Watch被称为“midden heap”，把Jon的贵族传奇翻成刑罚、贫困和边缘人口的社会制度；Tyrion又以怪物笑话过度简化真实风险。",
    47: "Tyrion的愧疚来得突然且“absurdly”，说明他习惯把尖锐当诚实，却仍能在看见眼泪时意识到自己越界。",
    48: "Ghost的攻击把Tyrion准备的道歉打断；叙事也模拟他的感知空白，从走近直接跳到倒地。",
    49: "Ghost完全不吼，只用红眼和牙齿建立界线；无声使它的保护更精确、更难预测。",
    51: "Tyrion不是消除愤怒而是凭意志“crushed it out”；他将过去被羞辱的经验转成控制当下反应的能力。",
    52: "Jon扶起Tyrion并归还书，关系在Ghost坐下后立即恢复；保护与合作并非互相排斥。",
    55: "Tyrion先感到被冒犯，随后能笑着接受grumkin玩笑；共同幽默把刚才的羞辱争夺转成较平等互动。",
    58: "Jon在分享酒后才问Night’s Watch真相，物品交换和笑声先恢复信任，严肃问题才可能出现。",
    60: "“如果就是这样，那就是这样”不是乐观，而是决定把失望后的现实作为新起点。",
    61: "Tyrion称赞面对hard truth，但他刚才用残酷手段传递真相；内容正确不自动证明方法正当。",
    63: "Tyrion说自己很少再梦dragon，与前面承认少年幻想呼应；成长在他口中意味着减少幻想而不是完全失去想象。",
    64: "拒绝Jon伸手是Tyrion的自尊与长期生存习惯；回营后评汤加胡椒则迅速恢复他熟悉的判断者角色。",
    66: "grumkins成为只有Tyrion和Jon懂的共同笑话；Benjen的困惑标记二人已在一次冲突中形成私人语言。",
    68: "Jon凝视火焰与Tyrion早年凝视dragonfire平行；Tyrion因此看见少年正在消化被迫放弃的幻想。",
    69: "悲伤微笑既包含同情也包含自知：Tyrion成功教会Jon现实，却知道这种知识会带来损失。",
}

STAGES = [
    (1, 17, "本段从地理分岔与北方景观写到队伍构成，Yoren及罪犯新兵开始拆解Jon对Night’s Watch的贵族化想象。"),
    (18, 29, "本段以Tyrion的阅读习惯进入dragonbone、龙骨地窖与Field of Fire历史，展示知识、幻想和家族生存如何连接。"),
    (30, 47, "本段由Jon询问阅读展开，Tyrion解释mind为何是自己的武器，又用过分尖锐的反讽强迫Jon面对Night’s Watch现实。"),
    (48, 58, "本段让Ghost保护Jon并迫使Tyrion礼貌求助；冲突经共同笑话和分享酒缓和，Jon终于直接询问真相。"),
    (59, 69, "本段让Jon选择接受hard truth，Tyrion则在返回营地后看见他凝视火焰，理解这种成长同时意味着幻想破裂。"),
]

BACKGROUNDS = {
    5: "**地理：** 离开Winterfell初段仍有农场、holdfasts、桥梁和旅店；越往北，定居密度越低。",
    8: "**制度：** Night’s Watch会接收以服役替代刑罚的人；Yoren带来的两名少年因强奸罪在Wall服役，以避免阉割。",
    9: "**通信：** Maester Luwin交给Benjen一笼ravens，用于Wall与南方据点之间传递消息。",
    16: "**文本事实：** Benjen提供自己的旧熊皮；Tyrion接受并实际需要它，因为北方温度远低于原有衣物承受范围。",
    20: "**材料设定：** dragonbone因含铁而黑，强度似钢却更轻、更柔韧且耐火；制弓可获得更远射程。",
    23: "**历史事实：** King’s Landing地窖保存十九具Targaryen龙骨；最后两只Dragonstone幼龙体型小且畸形，寿命很短。",
    24: "**专名：** Balerion、Meraxes和Vhaghar是Aegon及其姐妹征服Seven Kingdoms时使用的三条dragon。",
    26: "**历史背景：** 约三百年前King Loren与King Mern联合抵抗Targaryen征服，当时各地仍是独立王国。",
    28: "**历史背景：** 三条征服dragons唯一一次同时参战被称为Field of Fire，改变了兵力数量明显占优的战局。",
    35: "**文本事实：** Tyrion因身体需要使用自己设计的特殊马鞍；贵族出身保护他免于被遗弃或出售，也要求他履行家族职责。",
    45: "**文本事实与偏见：** Night’s Watch确实接收贫民、债务人、偷猎者和罪犯；Tyrion关于grumkins、snarks和危险程度的说法带有嘲弄与简化。",
    49: "**文本事实：** Ghost以无声扑倒和挡路保护Jon，没有咬伤Tyrion；它在Jon命令后坐下。",
    67: "**值勤：** Jon承担当夜第一班watch，说明他在抵达Wall前已参与队伍夜间警戒。",
}

EXTRA_VOCAB = [
    ("commotion", "/kəˈmoʊʃən/", "n.", "骚动；喧闹", "大队出发的混乱声响"),
    ("flurry", "/ˈflɜːri/", "v./n.", "小阵飘落；一阵忙乱", "此处指小雪飞扬"),
    ("flint", "/flɪnt/", "n.", "燧石", "坚硬灰色岩石"),
    ("holdfast", "/ˈhoʊldfæst/", "n.", "小型堡垒或设防据点", "奇幻封建地理用语"),
    ("promontory", "/ˈprɑːməntɔːri/", "n.", "岬角；突出高地", "山脊突起"),
    ("brier", "/ˈbraɪər/", "n.", "荆棘灌木", "black brier"),
    ("albino", "/ælˈbaɪnoʊ/", "adj./n.", "白化的；白化个体", "形容Ghost"),
    ("stooped", "/stuːpt/", "adj.", "弯腰驼背的", "Yoren体态"),
    ("sullen", "/ˈsʌlən/", "adj.", "阴沉不悦的", "新兵神情"),
    ("castration", "/kæˈstreɪʃən/", "n.", "阉割", "刑罚语境"),
    ("matted", "/ˈmætɪd/", "adj.", "纠结成团的", "肮脏头发"),
    ("rude awakening", "/ruːd əˈweɪkənɪŋ/", "idiom", "突然而残酷的醒悟", "幻想遭现实击破"),
    ("curtly", "/ˈkɜːrtli/", "adv.", "简短生硬地", "带不悦的回答"),
    ("musty", "/ˈmʌsti/", "adj.", "有霉味的；陈旧气味的", "旧熊皮"),
    ("chivalrous", "/ˈʃɪvəlrəs/", "adj.", "有骑士风度的", "此处带反讽"),
    ("hobbled", "/ˈhɑːbəld/", "adj.", "行动受限制的；跛行的", "Tyrion自述"),
    ("rumination", "/ˌruːməˈneɪʃən/", "n.", "沉思性论述", "学术书籍"),
    ("impervious", "/ɪmˈpɜːrviəs/", "adj.", "不受影响的；不能穿透的", "impervious to fire"),
    ("morbid", "/ˈmɔːrbɪd/", "adj.", "病态关注死亡的；阴郁的", "对灭绝dragons的迷恋"),
    ("dank", "/dæŋk/", "adj.", "阴湿寒冷的", "地窖环境"),
    ("onyx", "/ˈɑːnɪks/", "n.", "缟玛瑙；黑玛瑙", "龙骨颜色比喻"),
    ("hatchling", "/ˈhætʃlɪŋ/", "n.", "刚孵化的幼兽", "幼龙"),
    ("gullet", "/ˈɡʌlət/", "n.", "咽喉；食道", "巨龙喉咙"),
    ("aurochs", "/ˈaʊrɑːks/", "n.", "原牛", "大型已灭绝野牛"),
    ("conscription", "/kənˈskrɪpʃən/", "n.", "征兵；强制服役", "战史语境"),
    ("whetstone", "/ˈwetstoʊn/", "n.", "磨刀石", "books/mind比喻"),
    ("midden heap", "/ˈmɪdən hiːp/", "n.", "垃圾堆；粪堆", "贬低Night’s Watch"),
    ("wet nurse", "/wet nɜːrs/", "n.", "乳母", "儿童怪物故事来源"),
    ("spasm", "/ˈspæzəm/", "v./n.", "痉挛；抽搐", "背部疼痛"),
    ("haunches", "/ˈhɔːntʃɪz/", "n.", "动物后腿与臀部", "sit on its haunches"),
    ("stopper", "/ˈstɑːpər/", "n.", "瓶塞；酒袋塞", "打开酒袋"),
    ("tumbledown", "/ˈtʌmbəldaʊn/", "adj.", "摇摇欲坠的", "废弃holdfast墙"),
    ("ladle", "/ˈleɪdəl/", "n.", "长柄汤勺", "品尝炖汤"),
    ("mellow", "/ˈmeloʊ/", "adj.", "温和放松的", "酒后情绪"),
]
VOCAB = BASE_VOCAB + EXTRA_VOCAB

def main():
    blocks = extract_range(114, 121, "TYRION", "CH13")
    write_chapter(
        out=OUT, chapter=13, pov="TYRION", page_start=114, page_end=121,
        blocks=blocks, summaries=SUMMARIES, key_notes=KEY_NOTES, stages=STAGES,
        backgrounds=BACKGROUNDS,
        default_background="本段没有新增必须补充的世界观设定；重点在北方地理、Tyrion的身体与知识策略、Jon对Night’s Watch的幻想或二人逐步建立的信任。",
        vocab=VOCAB,
        guide="向北骑行两周后，Tyrion发现地图无法传达土地的辽阔与寒冷，也发现Jon对Night’s Watch的认识同样来自抽象传奇。Yoren及罪犯新兵首先令Jon失望；随后Tyrion借dragon历史解释自己为何把mind当作weapon，又以极其尖锐的方式拆解Jon对Wall和家庭位置的幻想。Ghost扑倒Tyrion，迫使他压下愤怒并礼貌求助，反而使二人关系重新变得平等。分享酒后，Jon不再追问安慰，而是确认hard truth并决定接受。",
        people=[
            ("Tyrion Lannister", "本章视角人物；以阅读和自我认识补偿身体限制，也会用尖锐言辞伤人"),
            ("Jon Snow", "十四岁，正随Benjen前往Wall；开始面对Night’s Watch的现实构成"),
            ("Benjen Stark", "Night’s Watch ranger，带领北行队伍，对Tyrion保持戒备"),
            ("Yoren", "年长Night’s Watch成员，带两名以服役替代刑罚的少年北上"),
            ("Ghost", "Jon的albino direwolf，在Tyrion逼近时无声保护Jon"),
            ("Morrec", "Tyrion的随从，负责营地炖汤"),
        ],
        terms=[
            ("wolfswood", "Winterfell以北广阔而古老的森林"),
            ("dragonbone", "黑色、轻而强韧且耐火的龙骨材料"),
            ("Field of Fire", "Aegon、Visenya与Rhaenys同时投入三条dragon的著名战役"),
            ("grumkins and snarks", "乳母故事中的怪物名称，被Tyrion拿来嘲弄Wall的守望任务"),
            ("hard truth", "令人痛苦却必须正视的事实，本章对Jon成长的核心表述"),
        ],
        synthesis="Chapter 13把两种知识放在一起比较。Tyrion相信书本能磨利mind，却也承认地图不等于土地；Jon相信Night’s Watch是noble calling，却必须看见Yoren、罪犯新兵与制度的边缘人口来源。Tyrion所讲的现实有重要真相，但他的教育方式利用了Jon最痛的家庭伤口，所以“说真话”并不自动等于善意。Ghost的介入迫使Tyrion亲身经历无力、羞辱和求助，也让他重新控制愤怒。二人最终靠grumkin笑话、酒和坦率问答形成一种不平等但真实的理解：幻想已经破裂，Jon仍可以决定如何面对现实。",
        contrasts=[
            "**地图／土地：** 抽象知识描述方向，身体旅程才显出距离、寒冷和资源稀薄。",
            "**Benjen形象／Yoren现实：** Jon以贵族亲属想象整个组织，实际成员来自不同阶级与刑罚路径。",
            "**sword／mind：** Jaime以剑、Robert以warhammer、Tyrion以阅读训练过的思维作为武器。",
            "**dragon幻想／hard truth：** 少年幻想提供高度与报复，成长则意味着接受世界没有按幻想组织。",
            "**尖锐诚实／愧疚道歉：** Tyrion相信拆穿幻觉，却在看见Jon眼泪时意识到手段造成伤害。",
            "**Ghost的威胁／Jon的帮助：** direwolf划定保护界线，Jon随后扶起Tyrion并归还书。",
        ],
        questions=[
            "Jon抵达Wall后会如何适应由不同阶级和罪犯组成的Night’s Watch？",
            "Tyrion对dragons的研究是否只是个人兴趣？",
            "Ghost为何能够如此准确地感知Jon受到的威胁？",
            "Jon接受hard truth后，是否仍会把Night’s Watch视为自己的选择？",
        ],
        extraction_notes="提取器正确保留PDF pp.116–117和120–121的2个跨页段落",
    )
    print(f"Wrote Chapter 13 with {len(blocks)} paragraphs")

if __name__ == "__main__":
    main()

