#!/usr/bin/env python3
"""Build Chapter 63 (CATELYN) close-reading Markdown."""
from pathlib import Path
from agot_extract import extract_range
from agot_reader_common import write_chapter
from build_agot_chapter62_reader import VOCAB as BASE_VOCAB

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/"outputs"/"AGOT_逐章精读"
SUMMARIES=[
"whispers一句把森林环境、伏兵低语和即将发生的隐秘行动叠合。","月光、溪流、战马与压低的玩笑构成极静的临战声景，金属声也被树林吸收。","Hallis预计很快接战；Robb与Catelyn就她的护卫人数从五十和十折中到三十。","Catelyn承认battle意味着任何人都可能死，因此暂时安于等待并感受自然。","她想起童年在Riverrun等待Hoster归来，守望成为贯穿一生的女性经验。","Brandon也让她等婚礼，却再未回来，最终站在sept旁的是Eddard。","Eddard新婚不久也赴war，但留下Robb；Catelyn在不知丈夫能否归来的情况下独自生产。","如今她等待Robb和从不耐等待的Jaime；计划把生命押在Blackfish对Jaime性格的判断上。","Robb在士兵间安抚人马、说笑，外表镇静；Catelyn惊觉十五岁的儿子已近自己高。","她祈求Robb活到成年、为父，眼中披甲青年仍是Riverrun的婴儿。","Riverrun令她发冷；她回忆Blackfish封锁raven、消灭scouts并断言Jaime不知伏军。","Robb询问Jaime军力。","Blackfish说十二千foot分散在三处river-separated camps，另有两三千horse，围城结构将成为弱点。","Galbart指出敌军仍三倍于己。","Blackfish承认数量劣势，却说Jaime缺少一样东西。","Robb追问是什么。","答案是patience。","Mallister和溃军幸存者使Robb兵力增加；他们急行以在消息抵达Jaime前到达埋伏地。","Olyvar为Robb披挂；helm落下后Catelyn熟悉的儿子视觉上变成无脸knight，Robb说Ned教过临战巡线。","Catelyn让他去给men看见。","Robb说这会给他们courage。","Catelyn暗问谁给自己勇气，却微笑放行；她坚持Robb也有三十名精锐battle guard，包括Dacey。","她仍怀疑三十护卫或六千军队是否足够。","远处北方snow shrikes依次鸣叫，跨页句合并后像冰手触颈，是预定接敌信号。","Catelyn立即明白Jaime军来了。","Hallis也低声确认并祈神。","森林突然静止，远方horse、armor和人声逐渐靠近。","等待仿佛跨过eons；Catelyn从枝间短暂认出无helm的Jaime。","Jaime再被树遮住，身后三分之二以上Lannister horse进入valley。","Blackfish曾判断Jaime不会坐守siege camp，已三次亲自追击raiders。","Robb据地图设计Tully小队在指定位置诱袭，主军移到另一位置等待。","‘here’被具体化为月影、枯叶、密林ridge和streambed的伏击地形。","‘here’也是Robb回望母亲、举剑作最后salute的瞬间。","Maege horn长鸣，确认最后一批Jaime riders已进入trap。","Grey Wind随即howl。","恐怖howl使Catelyn战栗，却也听见音乐，并短暂怜悯即将死亡的Lannisters。","Greatjon、Mallister、Frey、Karstark号角从四面回应，valley中的敌军开始混乱。","hidden bowmen齐射、埋在土叶下的lances显露；Robb高喊Winterfell带队下坡。","Catelyn仍被护卫包围在ridge上，像过去等Brandon、Eddard、Hoster一样等Robb；军队消失进树林。","对面Greatjon长线骑兵冲出，lance points在月光下像银焰will-o’-wisps。","她一眨眼，浪漫幻象还原为冲去杀或被杀的men。","Catelyn事后承认没真正看见battle，只通过回声、weapon、horse与求饶声重建；偶尔仿佛听见Robb和可能不止一只wolf。","声响逐渐消失，red dawn时只剩Grey Wind再次howl。","Robb换马归来，shield严重破损、衣袖染血；Catelyn以为他受伤。","Robb活动手指说血不是自己的，却也不知属于Torrhen还是谁。","Theon与Greatjon等拖着被俘Jaime上坡，扔到Catelyn马前。","Jaime跪地仍以失剑玩笑维持讥诮和尊严。","Catelyn说自己要的是Hoster、Edmure、女儿和Eddard。","Jaime说这些人也被自己mislaid。","Catelyn冷淡回答可惜。","Theon催Robb斩首Jaime。","Robb拒绝：活俘更有价值，且Eddard不允许战后杀prisoner。","Jaime称Eddard wise and honorable，语气也含自保。","Catelyn命令给Jaime上chains带走。","Robb命人听母亲，并加强guard，因为Karstark会要Jaime首级。","Greatjon同意，Jaime被带去包扎和锁押。","Catelyn询问Karstark为何仇恨Jaime。","Robb避开目光，像Eddard般阴郁，艰难说Jaime杀了他们。","Galbart说明死者是Karstark sons。","Robb说Torrhen、Eddard Karstark与Daryn Hornwood都死了。","Galbart承认Jaime败局中仍集结retainers，试图突进斩杀Robb，几乎成功。","Robb描述Jaime杀死三名护卫并不断呼喊挑战自己，哽在‘若无人阻止’。","Catelyn指出若无护卫牺牲，自己会代Karstark哀悼；她要求Robb稍后再grieve，因为只赢battle，Riverrun仍被围。","Theon兴奋夸大战果、十比一伤亡与大量贵族俘虏，类比Field of Fire。","Catelyn打断，问是否俘获Tywin。","Theon承认没有，胜利兴奋被压住。","Catelyn说Tywin未被拿下，war远未结束。","Robb接受母亲判断，提醒仍要解救Riverrun。",
]
KEY_NOTES={1:"极短opening把whispers同时赋给人、树叶、溪水与埋伏消息，树林仿佛主动保守秘密。",3:"三十是mother/commander双重角色的折中：她不愿夺走battle swords，Robb又不能无视其安全。",4:"等待自然细节不是平静无忧，而是接受不确定性后暂时停止控制。",5:"watch/wait在Catelyn一生反复出现，显示贵族women常在战争叙事边缘承担不知道结果的时间。",6:"Brandon promise与Eddard replacement把waiting连接死亡、婚姻和政治命运突变。",7:"Robb出生记忆使当前commander重新成为她在war absence中独自守护的child。",8:"Jaime impatience是整个ambush的行为假设；战术依赖对手按性格行动。",9:"touch/jest/gentle horse是leadership performance，也可能真实安抚；文本不把二者分开。",10:"十五、十六、二十、五十的年龄递进把母亲愿望拉长到battle之外的完整人生。",13:"三个camps由rivers隔开是siege necessity，也是各部分难以即时互援的operational weakness。",17:"单词Patience既回答数量劣势，也回扣Catelyn的waiting主题。",19:"helm把face变成black void，视觉化mother看着son进入公共lord identity。",22:"And who will give me courage不出口，说明她把own fear隐藏成Robb所需支持。Dacey身份也显示本章不把combat guard限定为男性。",24:"snow shrikes既是自然合理鸟声，也是侦察signal；northern birds让North军仿佛借环境说话。",28:"Jaime不戴helm强化其bold impatience，也让Catelyn能在瞬间确定目标。",31:"raid诱饵规模必须足够可信又不能损失过大；Tully banners引导Jaime做出特定识别。",32:"三次Here把抽象map点转为实际地形、亲子告别和trap闭合时刻。",34:"horn不是冲锋本身，而是最后敌骑进入kill zone的确认。",36:"death sounds like music呈现Catelyn对战术成功的恐惧与不可避免欣赏并存。",38:"土叶掩住lance points说明伏击不只靠位置，还靠visual concealment。",40:"will-o’-wisps银焰把骑兵短暂超自然化，下一段立即剥除浪漫。",42:"她没see battle却以sound构建极具身体感的叙事，符合被安排在ridge保护区的限制视角。",44:"Robb无伤却沾他人blood，胜利从一开始就以护卫代价写在身上。",47:"Jaime用mislaid sword把被俘改写成轻巧失物，语言是其最后保有的control。",48:"Catelyn列亲人而非领土，明确Jaime作为hostage的交换价值。",52:"more use alive同时是战略判断和对Eddard prisoner ethic的遵守。",55:"Karstark revenge预示prisoner security不只要防escape，还要防己方报仇。",61:"Jaime最后突击既证明courage，也说明Blackfish对其不肯接受等待/失败的判断准确。",63:"Catelyn允许grief但规定not now，将母亲经验转成commander discipline。",64:"Theon以名单和比例把惨烈转为triumph rhetoric，容易遮蔽Torrhen等具体死亡。",65:"问Tywin一句就测试victory scope：战果巨大，却未终止敌方最高command。",68:"Riverrun把Robb注意力从庆祝拉回最初战略目的。"}
STAGES=[(1,17,"Catelyn在whispering wood等待，以童年、Brandon、Eddard与Robb出生记忆理解当前不确定；trap依赖Jaime缺乏patience。"),(18,34,"Robb军增援后藏于valley ridges，以Tully raiders引Jaime三分之二以上骑兵进入伏击区。"),(35,43,"horns、Grey Wind与hidden archers发动合围；Catelyn看不见全局，只从月光和声音感受battle。"),(44,57,"Robb无伤归来并俘获Jaime；North军拒绝处决，准备把他作为高价值prisoner。"),(58,68,"Jaime突击造成Karstark与Hornwood死亡；Catelyn压住哀痛和庆祝，提醒Tywin与Riverrun仍在。")]
BACKGROUNDS={5:"**Riverrun childhood：** Hoster常离家处理court、fair或battle，Catelyn从城墙守望其沿河归来。",6:"**Brandon Stark：** Catelyn原订婚对象，赴King’s Landing后死亡，最终由弟弟Eddard与她成婚。",7:"**Robb birth：** rebellion期间Eddard在south作战，Robb在Riverrun出生，父子当时未见。",11:"**Blackfish screen：** 三百picked men封锁raven与out­riders，确保Jaime不知道Robb骑兵已到。",13:"**Riverrun siege geography：** 河流把围城foot分成三camp；Jaime的horse可被诱离，而foot难即时合流。",18:"**Robb force：** 过Twins的horse又获Mallister和Edmure败军幸存者加入，总数约六千。",22:"**Young Wolf guard：** 三十名贵族子弟和资深warriors组成Robb贴身battle guard；Dacey是Bear Island heir。",24:"**snow shrikes：** North冬季可见的鸟；本段被scouts模仿/利用作接敌signal。",31:"**ambush design：** 小股Tully banners制造raid，利用Jaime惯于亲率horse追击，将其带入wooded valley。",42:"**limited POV：** Catelyn在ridge受保护，正文明确她不能声称看见battle，声音重建必须视作主观感知。",47:"**Jaime captive：** Kingslayer兼Tywin长子，活着可交换Stark/Tully prisoners并限制敌方选择。",55:"**Karstark grievance：** Jaime亲手杀Torrhen、Eddard Karstark与Daryn，造成己方内部处置俘虏的压力。",63:"**battle versus war：** Jaime horse遭重创、本人被俘，但三处siege camps大部foot仍围Riverrun，Tywin主军也未败。",64:"**Field of Fire：** Aegon conquest中以dragons造成的著名压倒性胜利；Theon用它夸张本次战果。"}
EXTRA_VOCAB=[("whicker","/ˈwɪkər/","v.","马轻嘶","warhorse"),("chink","/tʃɪŋk/","n.","金属轻碰声","spears"),("slither","/ˈslɪðər/","n.","滑动的细响","mail"),("vigil","/ˈvɪdʒəl/","n.","守候；守夜","waiting"),("ofttimes","/ˈɔːfttaɪmz/","adv.","时常（古风）","days pass"),("wax and wane","/wæks ən weɪn/","v.","月亮盈亏；时间推移","nine moons"),("stake","/steɪk/","v.","以…作赌注","life"),("craggy","/ˈkræɡi/","adj.","棱角分明的","smile"),("undoing","/ʌnˈduːɪŋ/","n.","失败根源","siege camps"),("clamor","/ˈklæmər/","v.","争相强烈要求","guard honor"),("lanky","/ˈlæŋki/","adj.","瘦高的","Dacey"),("trill","/trɪl/","n.","颤鸣声","bird call"),("eon","/ˈiːən/","n.","极漫长时期","waiting perception"),("obscure","/əbˈskjʊr/","v.","遮蔽","trees"),("underbrush","/ˈʌndərbrʌʃ/","n.","林下灌木","terrain"),("williwisp","/ˌwɪl ə ˈwɪsp/","n.","鬼火","lance image"),("piebald","/ˈpaɪbɔːld/","adj.","黑白/杂色斑的","horse"),("mislay","/ˌmɪsˈleɪ/","v.","放错；遗失","Jaime irony"),("condone","/kənˈdoʊn/","v.","纵容；认可","prisoner murder"),("brooding","/ˈbruːdɪŋ/","adj.","阴郁沉思的","Robb"),("liege lord","/liːdʒ lɔːrd/","n.","宣誓效忠的领主","guard duty"),("perchance","/pərˈtʃæns/","adv.","或许（古风）","question")]
VOCAB=BASE_VOCAB+EXTRA_VOCAB

def extract_blocks():
 b=extract_range(631,638,"CATELYN","CH63")
 b[23]["text"] += " " + b[24]["text"]; b[23]["end_page"]=b[24]["end_page"]; del b[24]
 for i,x in enumerate(b,1): x["order"]=i; x["id"]=f"CH63-P{x['page']:03d}-{i:03d}"
 return b
def main():
 b=extract_blocks(); write_chapter(out=OUT,chapter=63,pov="CATELYN",page_start=631,page_end=638,blocks=b,summaries=SUMMARIES,key_notes=KEY_NOTES,stages=STAGES,backgrounds=BACKGROUNDS,default_background="本段没有新增必须补充的设定；重点在ambush对patience的利用、Catelyn受限的听觉视角与battle胜利后的未竟目标。",vocab=VOCAB,
 guide="Catelyn在树林伏兵中等待Jaime，战前静默触发她一生等待父亲、Brandon、Eddard与Robb的记忆。Blackfish已用三百scouts截断ravens和enemy outriders；整个计划押在Jaime缺乏patience、会亲率horse追逐Tully raiders上。Robb以约六千horse藏在wooded valley四周，snow shrikes与warhorn逐层确认敌骑进入kill zone。Catelyn被留在ridge，不能真正看见battle；文本因此以月光lance幻象、回声、horses惨叫和Grey Wind howls重建受限经验。黎明Robb无伤归来并俘获Jaime，却失去Torrhen、Eddard Karstark和Daryn Hornwood。Theon把它称为Field of Fire以来最大victory，Catelyn却立刻问Tywin是否被俘，并提醒Riverrun仍被围：这是battle victory，不是war结束。",
 people=[("Catelyn Stark","本章视角；在ridge等待，以母亲经验约束战后庆祝与哀痛"),("Robb Stark","设计并指挥Whispering Wood ambush，俘获Jaime但失去battle guard成员"),("Brynden Tully","以scouts封锁消息，并准确判断Jaime会因impatience追击"),("Jaime Lannister","率大部分horse进入trap；被俘前试图强突斩杀Robb"),("Hallis Mollen","率三十人保护Catelyn并在败局时负责送她回Winterfell"),("Dacey Mormont","Bear Island heir，持morningstar加入Robb battle guard"),("Theon Greyjoy","参与俘获并夸大战果，主张处决Jaime"),("Torrhen / Eddard Karstark / Daryn Hornwood","为阻止Jaime接近Robb而战死")],
 terms=[("Whispering Wood","Riverrun附近wooded valley伏击地；本章以声音与隐蔽性命名"),("snow shrike signal","利用North bird call传递enemy approaching的隐蔽侦察信号"),("battle guard","围绕Robb的三十名精锐护卫，承担替liege lord挡击的高风险"),("kill zone","四面ridge包围、最后敌骑进入后由horn确认的伏击区域"),("battle not war","Jaime被俘和horse败亡虽重大，Tywin主军与Riverrun siege仍未解决")],
 synthesis="Chapter 63把‘等待’从被动状态改写成Robb胜利的核心武器。Catelyn过去等待Hoster、Brandon、Eddard归来，常常无法影响远方战斗；本章这种经验让她比任何人都明白patience的痛苦。Jaime恰恰缺少它。Blackfish切断communication，Robb以Tully banners提供可见诱饵，再让密林、ridge、stream与bird calls隐藏真实兵力。胜负因此不只来自六千对两三千，而来自一方能等待、另一方必须行动。叙事形式也服从这一主题：Catelyn被保护在ridge，承认自己没有看见battle，只能等待并听。月光lances像will-o’-wisps的瞬间美感立即被‘only men, rushing to kill or die’击碎，拒绝把伏击浪漫化。黎明的政治判断同样克制。Jaime活着比死去有用，既可交换亲人也符合Eddard prisoner ethic；但Torrhen等人的死亡使Karstark revenge成为内部风险。Theon用ten-to-one、hundred knights与Field of Fire制造终局语气，Catelyn只问Tywin。她的作用不是否定Robb胜利，而是保护胜利不被自满浪费。章末Robb接受‘we still have Riverrun’，表明他学会把情感、战果和战略目的分层。",
 contrasts=["**whispers／warhorns：** 隐蔽等待最终爆发成包围声浪。","**Catelyn lifetime waiting／Jaime impatience：** 同一心理品质在家庭与战术层面相反运作。","**son’s face／black visor：** 私人孩子被公共commander身份遮蔽。","**silver will-o’-wisps／men killing or dying：** 战争美感被现实立即纠正。","**cannot see／battle alive in sound：** 受限视角反而放大感官不确定。","**Jaime courage／Jaime capture：** 个人勇猛不能挽救错误位置和战略。","**great victory／war far from done：** 战果规模与终局判断必须分开。"],
 questions=["Jaime能否换回Eddard、Sansa、Arya或Edmure？","Lord Karstark会否接受保留Jaime性命的战略决定？","Robb将如何处理仍围绕Riverrun的Lannister foot camps？","Tywin得知Jaime被俘后会怎样回应？","Catelyn在battle后能否获得Eddard与女儿们的可靠消息？"],
 extraction_notes="PDF pp.631–638校勘后共68段。4处跨页续段：pp.631–632、631–632（snow-shrike段由自动提取误拆后合并）、634–635、635–636；按段计实际跨页段为4，其中两段跨同一页界。p.631‘bent to bug her’疑为源页排印错误，p.632–633数处opening quote形态异常，均按源文保留并标注。")
 print(f"Wrote Chapter 63 with {len(b)} paragraphs")
if __name__=="__main__": main()
