#!/usr/bin/env python3
"""Build Chapter 39 (EDDARD) close-reading Markdown."""
from pathlib import Path
from agot_extract import extract_range
from agot_reader_common import write_chapter
from build_agot_chapter38_reader import VOCAB as BASE_VOCAB

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs" / "AGOT_逐章精读"

S = {
1:"Eddard梦见三名white-cloaked knights、已倒塌的tower与血床上的Lyanna。",
2:"梦中六名旧友与他同行；岁月模糊他们的脸，使其成为雾马上的灰色幽灵。",
3:"七人面对三名非凡Kingsguard：Arthur Dayne、Oswell Whent和Lord Commander Gerold Hightower。",
4:"Eddard说自己曾在Trident战场寻找他们。",5:"Gerold说他们不在那里。",
6:"Oswell称若他们在场，Usurper必有灾祸。",7:"Eddard又问King’s Landing陷落、Jaime杀Aerys时他们在哪里。",
8:"Gerold说若他们在场，Aerys仍会在位，Jaime会受地狱惩罚。",
9:"Eddard回忆解除Storm’s End围困、Tyrell与Redwyne投降时，也以为会见到他们。",
10:"Arthur说Kingsguard的膝盖不轻易弯曲。",11:"Eddard提到Willem Darry带queen与Viserys逃往Dragonstone，猜他们可能同行。",
12:"Oswell承认Willem忠诚可靠。",13:"Gerold强调Willem并非Kingsguard，而Kingsguard不会逃。",
14:"Arthur戴上helmet，说无论过去现在皆如此。",15:"Gerold以他们发过vow解释坚守。",
16:"Eddard的六名幽灵同伴执shadow swords靠拢，恢复七对三阵势。",
17:"Arthur拔出发光的Dawn，说战斗现在开始。",18:"Eddard悲伤地说现在是结束；钢铁交击时听见Lyanna尖叫呼唤他。",
19:"Lyanna的呼唤在梦与现实间再次响起。",20:"Eddard低声重复自己给Lyanna的promise。",
21:"黑暗里一个男人的声音接过Lord Eddard的呼唤。",22:"Eddard醒来，发现自己在Tower of the Hand。",
23:"床边的shadow再次确认他是否清醒。",24:"Eddard问过了多久，同时感到固定腿部的钝痛。",
25:"Vayon Poole说他昏睡六天七夜并喂水。",26:"Eddard迷糊地询问杯中是什么。",
27:"Poole说只是water，Pycelle预料他会口渴。",28:"嘴唇干裂的Eddard觉得水甜如honey。",
29:"Poole转告king命令醒后立刻见面。",30:"Eddard因梦后虚弱，想推迟到明天。",
31:"Poole说明Robert明确命令他一醒就通报，随后点灯。",
32:"Eddard让Robert若要谈就亲自来，还差点按习惯召Jory，想起死亡后改叫guard captain。",
33:"Alyn很快进入bedchamber听命。",34:"Eddard要他汇报昏迷六天间局势。",
35:"Alyn报告Jaime逃离城市、Catelyn捕Tyrion已传遍，并主动增加guards。",
36:"Eddard认可并立刻问daughters。",37:"Alyn说Sansa每日祈祷，Arya则愤怒沉默。",
38:"Eddard要求无论发生什么都保护daughters，认为冲突才刚开始。",39:"Alyn以生命担保她们安全。",
40:"Eddard转问Jory等死者。",41:"Alyn已交给silent sisters送回Winterfell，让Jory葬在grandfather旁。",
42:"Eddard想到Jory之父Martyn死在Tower of Joy；当年七对三仅Eddard与Howland Reed生还，他觉得旧梦重现不是吉兆。",
43:"Eddard刚肯定Alyn，Poole便报告Robert与Cersei已到门外。",
44:"Cersei同行使Eddard警觉；他命其他人离开，让谈话不外传。",
45:"Robert盛装、带wine且已脸红，Cersei戴tiara随后进入。",
46:"Eddard向king致礼并为无法起身致歉。",47:"Robert不介意并递上Arbor wine。",
48:"Eddard只要少量，说明milk of the poppy仍令头脑沉重。",
49:"Cersei讽刺他应庆幸脑袋还在肩上。",50:"Robert粗暴让Cersei安静，亲自问Eddard腿伤。",
51:"Eddard不愿在queen前示弱，只承认有些疼。",52:"Robert说Pycelle保证会痊愈，转问他是否知道Catelyn行为。",
53:"Eddard承认知情，并把Catelyn拘捕Tyrion的责任全部揽到自己命令上。",
54:"Robert直言自己不高兴。",55:"Cersei质问Eddard凭何动她的blood。",
56:"Eddard以Hand身份和维护king’s peace、执行king’s justice的职责回答。",
57:"Cersei想说他已经不再是Hand。",58:"Robert制止她，却也指责Eddard所谓维持和平已导致七人死亡。",
59:"Cersei补充被Eddard击伤的Tregar今晨死亡，数字为八。",
60:"Robert把kingsroad拘捕与街头械斗都视为自己不能容忍的秩序崩坏。",
61:"Eddard试图解释Catelyn有充分理由。",62:"Robert拒绝听理由，命他释放Tyrion并与Jaime和解。",
63:"Eddard反问自己是否应忘记Jaime为惩戒他而当面杀死三名手下。",
64:"Cersei反转叙事，称Eddard醉离brothel后主动袭击Jaime，Catelyn也先袭Tyrion。",
65:"Eddard请Robert去问现场的Littlefinger。",66:"Robert说Littlefinger只承认他们从whorehouse回来，称自己战前已离开找gold cloaks。",
67:"Eddard愤怒揭示自己去看Robert的女儿Barra，并观察Cersei对私生女消息毫无表情。",
68:"Robert只抱怨Barra之母缺乏判断，不因女儿消息喜悦。",
69:"Eddard指出母亲才约十五岁且处境脆弱，却爱上Robert。",
70:"Robert看向Cersei，说这话题不适合queen听。",71:"Eddard说Cersei也不会喜欢接下来的要求：授权抓Jaime归案。",
72:"Robert喝酒沉思后拒绝，按双方死亡人数宣布冲突到此结束。",
73:"Eddard质疑这种算术是否算justice，并说庆幸自己不再是Hand。",
74:"Cersei用Targaryen kings不会容忍这种言辞来刺激Robert。",75:"Robert反问她是否把自己当Aerys。",
76:"Cersei称自己只把他当king，并说Starks攻击其姻亲、Eddard持续羞辱王权，而Robert却软弱关怀他。",
77:"Robert愤怒再次命Cersei闭嘴。",78:"Cersei嘲讽两人性别角色倒置：Robert该穿裙、她该披甲。",
79:"Robert反手打倒Cersei；她不哭喊，称脸上将形成的bruise是badge of honor。",
80:"Robert威胁再打，叫Ser Meryn护送Cersei回房。",
81:"Cersei离开后Robert把暴力归咎于她的挑衅，随后承认不该动手，并流露自己虽杀Rhaegar却仍失去Lyanna的挫败。",
82:"Eddard试图把谈话拉回必须处理的事情。",83:"Robert厌倦谈话，决定次日去kingswood狩猎，要求余事等回来。",
84:"Eddard提醒Robert曾命他返回Winterfell，希望届时已离开。",
85:"Robert归还silver Hand clasp，禁止Eddard离开并强令他继续任职。",
86:"Eddard因伤感到无力，只能拿起徽章，并再次提Targaryen girl。",
87:"Robert拒绝再谈，称此事已经决定。",88:"Eddard反问若不听counsel，为何还要自己做Hand。",
89:"Robert说总得有人治理王国，并以把徽章给Jaime作威胁，逼Eddard接受。",
}
SUMMARIES=[S[i] for i in range(1,90)]

KEY_NOTES={
1:"old dream说明这不是新信息的普通回忆，而是多年反复回返、仍未被整合的创伤场景；开篇只给意象，不给因果。",
2:"朋友的脸被years leech成shadows，敌方三人的脸反而清晰，说明创伤记忆并不按情感亲疏保存。",
3:"seven against three在数量上占优，叙述却用非凡称号、武器和静定动作让三人更具压迫感。",
4:"对话像仪式化问答，Eddard逐一列出Kingsguard本应出现的历史节点，实际在逼近‘为何守在这里’。",
6:"Usurper是Targaryen loyalist对Robert的称呼；梦保留对手的价值语言，没有把胜者叙事强加给他们。",
8:"false brother把Jaime定义为违誓者；这是Gerold立场，不等于文本已裁定所有历史复杂性。",
10:"knees do not bend既指不投降，也把Kingsguard vow写成身体姿态。",
13:"短句把‘不逃’绝对化；其光荣感与对局势变化的拒绝适应同时存在。",
16:"Eddard同伴只剩wraiths和shadow swords，预先暗示这场胜利将伴随巨大死亡代价。",
17:"Dawn alive with light与其余shadow形成视觉对立，让Arthur在梦中近似不可战胜的传说人物。",
18:"Now it ends把Robert’s Rebellion的军事胜利与Eddard私人灾难叠在一起；rose petals、blood sky和blue eyes把美、死亡与Lyanna相连。",
19:"称呼从Eddard到Lord Eddard悄然变化，梦中Lyanna的声音被现实男性声音接管。",
20:"promise被重复却不说明内容，是本章最明确的悬而未决信息；只能确认它长期支配Eddard的记忆。",
22:"Tower of the Hand与梦中fallen tower形成地点回声：他从一个权力与死亡之塔醒在另一个权力之塔。",
24:"tangled sheets、splint与throb把传奇梦境突然压回脆弱身体。",
28:"water sweet as honey以极端口渴改变最普通事物的价值，展示昏迷后的身体尺度。",
30:"他回避Robert不只是伤势；梦把旧友、Lyanna与promise重新带到当前政治冲突中。",
32:"about to say Jory是丧失习惯的瞬间：语言比意识更慢接受长期依赖者已死。",
35:"三条消息同时显示冲突扩散：Jaime军事移动传闻、Tyrion被捕成为公共故事、Stark household进入防御。",
37:"Sansa以内向祈祷、Arya以沉默愤怒回应同一创伤，避免把child grief写成单一模板。",
39:"stake my life既是守卫誓言，也因Jory刚死亡而带有真实风险，不是空洞套语。",
42:"Jory遗体将靠近grandfather，却不能靠近father，使当下死亡与Tower of Joy旧死亡形成家族闭环。",
44:"Eddard要求密谈表明他仍想维护王室内部体面，但Cersei到场意味着谈话已是阵营对抗。",
45:"Robert精心穿戴王权标志，却又带酒、脸红；外部regalia与内部失控并置。",
49:"Cersei第一句话把探病改成审讯威胁，迅速确定谈话基调。",
51:"不承认weakness是策略，却也使重伤、药物和愤怒影响下的决定不易被他自己纳入评估。",
53:"Eddard揽责是在保护Catelyn，也把她行动转化为Hand的正式行为，从而让Robert必须直接处理制度冲突。",
56:"icy courtesy以礼貌形式拒绝服从羞辱；他引用的不是私人报复，而是Robert亲授的official mandate。",
58:"Robert关心结果性秩序：死了多少人、街道是否乱；Eddard关心原因性justice：谁先犯罪、如何问责。",
59:"Cersei精准更新死亡数字，既强化Stark责任，也表明她持续掌握Lannister伤亡。",
62:"to hell with her reasons公开切断事实调查；Robert追求快速停战，而非判断谁的指控成立。",
63:"chasten把杀人表述为对Eddard的惩戒，强调Jaime在用私兵替自己执行未经审判的权力。",
64:"Cersei把前因删去，只留下brothel、drunk与双方主动攻击，展示政治叙事如何靠选择性事实重排责任。",
66:"Littlefinger的证词只覆盖自己离开前所见，既不能证明Jaime后续行为，也留下他为何恰好缺席的空白。",
67:"your daughter既纠正brothel暗示，也故意在Cersei面前投放Robert私生子女信息；mask说明她不愿提供可读反应。",
68:"Robert把怀孕与爱恋责任推给十五岁女孩的sense，回避自己年龄、权力与承诺位置。",
69:"Eddard的incredulous突出道德尺度差异：Robert视为麻烦的女人，在他眼中是易受伤害的child。",
72:"三对五的死亡算术把justice缩成账面平衡，却忽略谁发动、谁逃逸以及死者个体。",
73:"Eddard以不再任职保护道德一致性；但这也让他失去在制度内部继续调查与阻止伤害的工具。",
74:"Cersei引用Targaryen专制不是赞美，而是以‘你不像真正的king’触发Robert身份焦虑。",
76:"marriage bonds把Jaime、Tyrion称为Robert brothers，使Lannister利益包装成王室honor。",
78:"skirts/mail羞辱依赖性别角色规范，把克制称作女性化、把攻击性称作统治资格。",
79:"叙事清楚记录Robert主动施暴与严重后果；Cersei的挑衅不构成正当化，badge of honor则把伤痕转成控诉证据。",
80:"Robert一面命令沉默一面借Kingsguard执行隔离，王室制度在此保护施暴者免于继续面对受害者。",
81:"You see what she does to me是责任转移，随后I should not have hit her又短暂承认主体责任；两种说法在同一段摇摆。",
82:"Eddard没有安慰性认可Robert的自怜，而想转向治理问题，显示私人友情与Hand duty的冲突。",
83:"hunt是Robert一贯的逃避出口：面对无法用身体击败的问题，他离开talk与rule。",
85:"归还badge看似恢复信任，实际以king command取消Eddard选择；职位成为强制责任而非荣誉奖赏。",
86:"helpless as a child把Hand的银徽与splinted leg并置：形式权力恢复，身体和政治自主却都受限。",
88:"这句抓住全章治理悖论：Robert要Eddard承担rule，却保留不听counsel的最终权力。",
89:"Someone has to rule承认Robert本人不愿治理；用Jaime威胁则把国家职位降格为逼迫朋友的工具。",
}

STAGES=[
(1,20,"Eddard重做Tower of Joy旧梦：七名同伴面对三名Kingsguard，战斗与Lyanna呼喊、blood、rose petals和promise相连。"),
(21,42,"现实声音唤醒昏迷六天的Eddard；他得知Jaime离城、女儿悲痛、死者送北，并把Jory之死与旧日tower伤亡连接。"),
(43,62,"Robert与Cersei来访，围绕Catelyn拘捕Tyrion和街头死亡争执；Eddard揽责，Robert只求立即释放与和解。"),
(63,80,"双方争夺街头冲突叙事并牵出Barra；Eddard要求抓Jaime，Cersei刺激Robert，最终Robert当场殴打她。"),
(81,89,"Robert在悔意、自怜与逃避间摇摆，拒谈Targaryen girl，却强迫Eddard重新担任Hand治理王国。"),
]

BACKGROUNDS={
1:"**Tower of Joy：** 位于Dorne红色山地的一座塔，Rhaegar曾如此命名；本段只确认Lyanna、三名Kingsguard与Eddard旧日战斗在此相连。",
2:"**Eddard同行者：** Martyn Cassel、Theo Wull、Ethan Glover、Mark Ryswell、Howland Reed、Lord Dustin；梦中与Eddard合为七人。",
3:"**三名Kingsguard：** Arthur Dayne号Sword of the Morning并持Dawn；Oswell Whent属black bat家族；Gerold Hightower是Lord Commander。",
7:"**历史节点：** Trident战役后Rhaegar死；King’s Landing陷落时Jaime杀Aerys。梦中三名Kingsguard均未出现在这些地点。",
9:"**Storm’s End：** Rebellion末期受Tyrell、Redwyne围困，Eddard南下解除围城并接受其投降。",
11:"**Dragonstone撤离：** Willem Darry曾带Aerys遗孀与年幼Viserys撤往Dragonstone；三名Kingsguard并未同行。",
20:"**文本事实／未知：** Eddard确实向Lyanna作过promise；本章尚未说明承诺内容、起因或持续后果。",
25:"**伤势：** Jaime伏击后Eddard腿部骨折，服用milk of the poppy并昏睡六天七夜。",
35:"**当前局势：** Catelyn带Tyrion前往Vale；Jaime在King’s Landing袭击Eddard后离城，去向只是流言。",
41:"**silent sisters：** 负责处理与运送遗体的宗教女性群体；Alyn安排Jory等返回Winterfell安葬。",
42:"**已知幸存者：** Tower of Joy七名北方人中只有Eddard与Howland Reed活着离开；塔后被拆，石头建成八座cairns。",
48:"**milk of the poppy：** 强效止痛镇静药，会使意识沉重；Eddard此时并非完全恢复状态。",
53:"**责任声明：** Catelyn实际根据dagger线索临场拘捕Tyrion；Eddard在此对Robert声称她依自己命令行动。",
56:"**Hand authority：** Hand受king委任执行政务与justice；Eddard先前因反对刺杀Daenerys辞职，Robert尚未接受永久离任。",
59:"**死亡计数：** Stark一方Jory、Wyl、Heward三死；Lannister一方在街战后已有五死，包括Tregar。",
67:"**Barra：** Robert与一名约十五岁女孩所生的婴儿；Eddard此前调查Robert私生子女特征时见过她。",
71:"**Jaime状态：** 他已离开King’s Landing；Eddard要求正式授权追捕，Robert拒绝。",
79:"**安全与责任：** 本段描写成人伴侣间的家庭暴力。Robert的行为由他本人实施；后文自责或指责Cersei均不改变这一事实。",
85:"**Hand badge：** 银制手形别针象征Hand office；Eddard辞职时交还，Robert现在以王命归还并禁止其离城。",
86:"**Targaryen girl：** Daenerys在Dothraki sea怀孕；Robert已批准刺杀计划，Eddard正因反对此事辞职。",
}

EXTRA_VOCAB=[
("wraith","/reɪθ/","n.","幽灵；鬼影","dream companions"),("crannogman","/ˈkrænəɡmæn/","n.","泽地居民","Howland Reed"),("leech","/liːtʃ/","v.","像水蛭般慢慢吸走","years and memory"),("whetstone","/ˈwetstoʊn/","n.","磨刀石","Oswell"),("hilt","/hɪlt/","n.","剑柄","Dawn"),("enamel","/ɪˈnæməl/","v./n.","以珐琅覆盖；珐琅","white helm"),("woe","/woʊ/","n.","灾祸；悲痛","woe to"),("usurper","/juːˈsɜːrpər/","n.","篡位者","Robert in loyalist speech"),("fealty","/ˈfiːəlti/","n.","效忠誓言","bend the knee"),("don","/dɑːn/","v.","穿上；戴上（古风）","helmet"),("unsheathe","/ʌnˈʃiːð/","v.","拔出刀剑","Dawn"),("milkglass","/ˈmɪlkɡlæs/","n.","乳白玻璃","blade simile"),("splint","/splɪnt/","v./n.","用夹板固定；夹板","broken leg"),("parched","/pɑːrtʃt/","adj.","干渴皲裂的","lips"),("omen","/ˈoʊmən/","v.","预示；成为征兆","dream"),("cairn","/kern/","n.","石冢；石堆墓标","tower dead"),("ridge","/rɪdʒ/","n.","山脊","eight cairns"),("bode","/boʊd/","v.","预示","not bode well"),("doublet","/ˈdʌblət/","n.","男式紧身上衣","Robert’s dress"),("mantle","/ˈmæntəl/","n.","披肩；斗篷","golden mantle"),("tiara","/tiˈɑːrə/","n.","宝石冠饰","Cersei"),("vintage","/ˈvɪntɪdʒ/","n.","特定年份的酒；佳酿","Arbor wine"),("subside","/səbˈsaɪd/","v.","平息；退让安静","Cersei"),("chasten","/ˈtʃeɪsən/","v.","惩戒；使收敛","Jaime’s purpose"),("swirl","/swɜːrl/","v.","旋动杯中液体","wine"),("incredulous","/ɪnˈkredʒələs/","adj.","难以置信的","Eddard"),("brood","/bruːd/","v.","阴沉思索","Robert"),("notion","/ˈnoʊʃən/","n.","观念；想法","justice"),("meekly","/ˈmiːkli/","adv.","温顺软弱地","Cersei’s accusation"),("mail","/meɪl/","n.","锁子甲","me in mail"),("lash out","/læʃ aʊt/","v.","猛然攻击","Robert"),("backhand","/ˈbækhænd/","n./adj.","反手击打","blow"),("cradle","/ˈkreɪdəl/","v.","捧住；托住","wine cup"),("regalia","/rɪˈɡeɪliə/","n.","王权服饰与标志","interpretive term"),("sick unto death","/sɪk ˌʌntuː ˈdeθ/","phr.","厌烦至极","talk"),("bedpost","/ˈbedpoʊst/","n.","床柱","steady himself"),("clasp","/klæsp/","n.","别针；扣饰","Hand badge"),
]
VOCAB=BASE_VOCAB+EXTRA_VOCAB

def main():
    blocks=extract_range(388,395,"EDDARD","CH39")
    write_chapter(
        out=OUT, chapter=39, pov="EDDARD", page_start=388, page_end=395,
        blocks=blocks, summaries=SUMMARIES, key_notes=KEY_NOTES, stages=STAGES,
        backgrounds=BACKGROUNDS,
        default_background="本段没有新增必须补充的世界观事实；重点在Tower of Joy创伤记忆、王室内部权力、street violence问责与Hand责任。",
        vocab=VOCAB,
        guide="昏迷中的Eddard重做一个多年未散的旧梦：Tower of Joy前，七名北方同伴面对Arthur Dayne等三名Kingsguard。梦以历史问答逼近谜面，却只留下Lyanna的呼喊、血床与未说明内容的promise。醒来后，他得知自己已昏睡六天、Jaime离城、女儿悲痛、Jory等将送回Winterfell。Robert与Cersei随即来到病床边，争论Catelyn拘捕Tyrion及Jaime街头杀人。Robert追求立即恢复表面秩序，Eddard坚持原因、证据和问责；Cersei则重排事实并刺激Robert的king身份，最终遭Robert当场殴打。Robert短暂自责却把责任外推，又以狩猎逃避治理；他拒绝重谈刺杀Daenerys，却强迫Eddard重新戴上Hand badge。",
        people=[
            ("Eddard Stark","本章视角；从Tower of Joy旧梦醒来，在重伤与药物影响下重返王权争论"),
            ("Lyanna Stark","Eddard已故sister；梦中在bed of blood呼唤他并与一项promise相连"),
            ("Arthur Dayne / Oswell Whent / Gerold Hightower","Tower of Joy前坚守的三名Kingsguard"),
            ("Howland Reed","Tower of Joy七名北方人中除Eddard外唯一生还者"),
            ("Robert Baratheon","king与Eddard旧友；拒绝继续冲突，却逃避具体治理并恢复Eddard的Hand职位"),
            ("Cersei Lannister","queen；为Jaime、Tyrion辩护并挑战Robert权威，遭Robert家庭暴力"),
            ("Alyn","新任Stark guard captain，汇报局势并安排北送Jory等遗体"),
            ("Vayon Poole","Stark steward，照料刚苏醒的Eddard并传达king命令"),
            ("Jory Cassel / Martyn Cassel","刚死去的guard captain及其死于Tower of Joy的father，连接两代损失"),
        ],
        terms=[
            ("Tower of Joy","Dorne红山中的旧塔；Eddard、六名同伴与三名Kingsguard曾在此战斗"),
            ("Dawn","Arthur Dayne的著名乳白色greatsword，与Sword of the Morning称号相连"),
            ("Kingsguard vow","white-cloaked knights守护王室的终身誓言；梦中三人以不逃、不屈膝定义它"),
            ("silent sisters","处理、净身并运送遗体的宗教女性群体"),
            ("Hand badge","代表Hand of the King职权的银色手形别针"),
        ],
        synthesis="Chapter 39把两个‘tower’叠在一起：Tower of Joy储存Eddard不能公开整理的旧承诺，Tower of the Hand则把他重新拉回当前治理责任。过去七对三的胜利只留下两名生还者；现在Robert试图用三死对五死的算术宣布事情结束。Eddard拒绝这种结果平衡，因为对他而言justice必须询问原因、授权与责任。可他自己的处境同样矛盾：辞去Hand能保持道德纯度，却可能把rule交给更不负责任的人；重新戴徽章能保留行动能力，却意味着继续服务一个拒绝听counsel、以暴力和狩猎逃避问题的king。梦境谜团和现实政治因此共同追问：一个vow在权力更替、私人爱与公共责任冲突时，究竟要求人坚持什么。",
        contrasts=[
            "**朋友如shadows／敌手脸清晰：** 创伤记忆保存威胁与关键人物，却侵蚀亲近同伴的细节。",
            "**Tower of Joy／Tower of the Hand：** 一个装载旧日血与promise，一个装载当下职位与命令。",
            "**seven against three／three dead against five：** 两组数字都不能说明道德真相或胜利代价。",
            "**king’s peace／king’s justice：** Robert优先停止冲突，Eddard优先查清罪责。",
            "**royal dress／private失控：** Robert穿完整regalia进入，却饮酒、施暴并逃避治理。",
            "**badge of honor／Hand badge：** Cersei把伤痕变成控诉徽章；Eddard接回象征责任却限制自由的银徽。",
        ],
        questions=[
            "三名Kingsguard为何没有出现在Trident、King’s Landing、Storm’s End或Dragonstone，而守在Tower of Joy？",
            "Eddard向Lyanna许下了什么promise，为何多年后仍不能忘记？",
            "Cersei听到Barra存在时毫无表情，mask之下实际在想什么？",
            "Eddard重新担任Hand后，能否同时阻止Daenerys刺杀计划并追究Jaime责任？",
            "Robert为何认为自己虽杀死Rhaegar，却仍由Rhaegar‘赢了’？",
        ],
        extraction_notes="PDF pp.388–395校勘后共89段；共5处跨页续段：pp.390–391、391–392、392–393、393–394与394–395。PDF p.395仅承接最后一段结句，Chapter 40从p.396开始；段落顺序、引号与专名均已复核。",
    )
    print(f"Wrote Chapter 39 with {len(blocks)} paragraphs")

if __name__=="__main__":
    main()
