#!/usr/bin/env python3
"""Build Chapter 47 (EDDARD) close-reading Markdown."""
from pathlib import Path
from agot_extract import extract_range
from agot_reader_common import write_chapter
from build_agot_chapter46_reader import VOCAB as BASE_VOCAB

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/"outputs"/"AGOT_逐章精读"

S={
1:"Eddard梦行Winterfell crypts，冰眼kings与stone direwolves注视，Lyanna血泪statue再次要求promise。",
2:"猛烈敲门使他惊醒，黑暗中有人呼Lord Eddard。",3:"他昏沉裸身开门，见Tomard、Cayn与royal steward。",
4:"steward毫无表情地传Robert命令，要求Hand立即到场。",
5:"Eddard以为Robert终于hunt归来，匆忙穿适合cast的衣服、Hand badge，并佩Valyrian dagger。",
6:"Cayn、Tomard护送他穿过月下寂静Red Keep，rampart有gold cloak巡逻。",
7:"他经过Maegor’s Holdfast厚墙、spiked moat与三名Kingsguard，想起梦中three white cloaks，并从Barristan脸色知出大事。",
8:"Robert以异常黏重声音叫人带Eddard靠近。",
9:"bedchamber双火炽热压抑，Pycelle、Renly、servants、Cersei围着bed，Eddard感觉仍在梦中慢移。",
10:"Robert boots仍沾mud、grass，割开的green doublet带血，房间充满smoke、blood、death气味。",
11:"Robert见Eddard便虚弱叫他靠近。",12:"Eddard扶bedpost，一眼知伤势严重，几乎问不出话。",
13:"Renly只答是boar。",14:"Robert承认酒喝太多、刺偏，是自己过错。",
15:"Eddard怒问Renly、Barristan与Kingsguard当时在哪里。",
16:"Renly说Robert命所有人退开，让他单独猎boar。",
17:"Eddard掀开blanket查看伤口。",
18:"boar tusks从groin撕到chest，bandages已黑血、伤口恶臭，Eddard恶心放回blanket。",
19:"Robert闻到死亡，却自豪说自己用knife刺穿boar eye报复。",
20:"Renly确认带回boar carcass。",21:"Robert要用于funeral feast，并命所有人离开与Eddard私谈。",
22:"Cersei试图以sweet lord开口。",23:"Robert恢复一丝凶狠命她离开。",
24:"Cersei带头退场；Pycelle留下递milk of poppy止痛。",
25:"Robert打翻杯子，说很快会永睡，命Pycelle滚。",
26:"Pycelle给Eddard一个受创眼神后离开。",
27:"独处后Eddard痛骂Robert为何总如此headstrong，腿痛与grief让视线模糊。",
28:"Robert仍以杀boar自辩，随后因Daenerys只是child而悔恨，认为boar是gods punishment，并承认只有Eddard敢说no。",
29:"Eddard铺纸执quill，准备按king命令记录。",
30:"Robert口授will：死后任Eddard为Lord Regent、Protector，代治到son Joffrey成年。",
31:"Eddard不忍临终揭穿Joffrey，私自把my son Joffrey改成my heir，因love之lie感到污秽。",
32:"Robert让他补足protect、defend等正式措辞，自己会签并命死后交council。",
33:"Eddard悲痛求Robert别死，称realm需要他。",
34:"Robert看穿bad lie，自认是wretched king、近似Aerys。",
35:"Eddard安慰他远没有Aerys那么坏。",
36:"Robert希望最后任命Eddard算一件做对的事，相信他虽厌rule却能做好，催问写完没有。",
37:"Robert盲签并留下blood smear；Eddard提醒seal需witness。",
38:"Robert命funeral feast把boar烤熟吃掉，要求Eddardpromise。",
39:"Eddard答promise，脑中回响Lyanna相同请求。",
40:"Robert撤销Daenerys暗杀愿望，求Eddard救她并帮son变得比自己好。",
41:"Eddard安慰gods会mercy。",
42:"Robert闭眼放松，自嘲被pig杀却痛得笑不出。",
43:"Eddard问是否叫众人回来。",44:"Robert点头并忽然觉得房间cold。",
45:"servants添火，Cersei已离开；Eddard希望她有理智就带children黎明前逃走。",
46:"Renly与Pycelle回来见证Robert把seal压进will，随后king要求止痛并等待死亡。",
47:"Pycelle调新milk of poppy，Robert这次喝尽，问是否会dream。",
48:"Eddard回答会。",
49:"Robert笑说会向Lyanna转达Eddard爱，并托他照顾自己的children。",
50:"Eddard不能对paternity撒谎，转而想到Barra、Mya、Gendry等Robert真实children，承诺像自己children般guard。",
51:"Robert接受后睡去，poppy洗掉脸上痛苦。",
52:"Pycelle说伤口已mortified、两日运回延误治疗，只能减痛，医治只能靠gods。",
53:"Eddard问还有多久。",54:"Pycelle说按理早该死，Robert求生意志异常强。",
55:"Renly说brother从不wise但始终strong，肠子外露仍杀boar令他惊叹。",
56:"Eddard说Robert从不在敌人还站着时离开battlefield。",
57:"房外Eddard命Barristan未经许可不得打扰服药的Robert。",
58:"Barristan自责辜负sacred trust。",
59:"Eddard说最true knight也无法保护king免于自己，Robert千次猎boar，没人知这次会死。",
60:"Barristan感谢其宽慰。",61:"Eddard说Robert也归咎wine。",
62:"Barristan承认Robert遇boar前已醉得在saddle摇晃，却仍命众人退下。",
63:"Varys悄声问是谁给king wine。",
64:"Eddard没听见Varys靠近，回头见其黑袍、fresh powder。",
65:"Barristan说wine来自king自己skin。",66:"Varys追问是否只有一skin。",
67:"Barristan不记数，只知squire按需不断拿fresh skin。",
68:"Varys讽刺称这squire真dutiful，确保king不断refresh。",
69:"Eddard想起宴会上被Robert捉弄的两名fair-haired squires，问是哪一个。",
70:"Barristan答年长的Lancel。",
71:"Varys强调Lancel是Kevan son、Tywin nephew、queen cousin，又讽刺child innocence与vulnerability。",
72:"Eddard不信Varys曾innocent，随即命他撤回Daenerys暗杀安排。",
73:"Varys说birds可能已飞、或许太迟，但会尽力取消后离开。",
74:"Eddard过bridge时Renly追出来请求私谈。",
75:"Eddard停下同意。",
76:"Renly命支开guards，两人在spiked moat上桥中央密谈。",
77:"Renly猜will任Eddard Protector，提出一小时内集百把swords。",
78:"Eddard问百剑要做什么。",
79:"Renly主张趁castle睡着先夺Joffrey、Myrcella、Tommen，以children控制Cersei并让council确认regency。",
80:"Eddard拒在Robert未死时流blood、从bed拖走恐惧children，打算等death后正式召council议succession。",
81:"Renly警告每延迟一刻都给Cersei准备时间，Robert死时两人或都来不及。",
82:"Eddard说应祈祷Robert不死。",83:"Renly说机会很小。",
84:"Eddard说gods有时merciful。",85:"Renly回Lannisters不会mercy，转身回tower。",
86:"Eddard回房疲惫心碎，想起win-or-die，怀疑拒Renly是否正确；他厌children threats却可能需要百剑。",
87:"他命Cayn黎明前从winesink、whorehouse找到Littlefinger，并问Tomard Wind Witch escort。",
88:"Tomard说Porther带十人。",
89:"Eddard增至二十并改由更稳重Tomard统领。",
90:"Tomard接受，也期待离开city见wife。",
91:"Eddard说北航会过Dragonstone，另有letter要送。",
92:"Tomard因Dragonstone sinister reputation不安。",
93:"Eddard命ship近岛升Stark banner，并把letter只亲交Stannis本人，不给任何代理。",
94:"Tomard接受。",
95:"独处后Eddard grief压倒，想去heart tree为如brother的Robert祈祷，又担心后人误说自己背叛并剥夺其sons。",
96:"他看Robert final letter：白parchment、gold wax、短词与blood smear，感叹胜败生死差异之小。",
97:"Eddard起草给Stannis信，称Robert将死于boar。",
98:"文字仿佛扭曲；他想到Tywin、Jaime必战，催Stannis在Lannisters行军前率全部力量赴King’s Landing。",
99:"Eddard谨慎完成、签Protector title并以wax封信。",
100:"他以为regency会很短，新king将另选Hand，自己可回Winterfell与Catelyn、children团聚。",
101:"Cayn、Desmond带Littlefinger回来；Eddard谢退guards。",
102:"Littlefinger盛装坐下，说似乎该congratulate。",
103:"Eddard怒说king重伤将死。",104:"Littlefinger说也知道Robert任Eddard Protector。",
105:"Eddard看未拆seal，追问他如何知道。",
106:"Littlefinger说Varys暗示，而Eddard刚才反应已确认。",
107:"Eddard咒Varys little birds像black art，不信任他。",
108:"Littlefinger称赞他正在学习，并指出深夜叫自己不是谈Varys。",
109:"Eddard坦白Jon秘密：Robert无trueborn son，Joffrey、Tommen为Jaime与Cersei incest所生。",
110:"Littlefinger假装震惊又问girl是否也一样，语气显示早有心理准备。",
111:"Eddard说king死后throne依法归Robert elder brother Stannis。",
112:"Littlefinger说看似如此，除非另有选择。",
113:"Eddard坚持Stannis就是heir，没有可变余地。",
114:"Littlefinger却建议帮助Joffrey succeed，因为Stannis需Eddard协助才可登位。",
115:"Eddard冷问他是否毫无honor。",
116:"Littlefinger称有一点，随后说Stannis刚硬不宽恕、会清洗council并杀Cersei children，引发Tywin、Tyrell、Redwyne等全面war。",
117:"他提出另一面：让十二岁Joffrey继位、Eddard摄政，与Lannisters和解、三重婚姻结盟，日后可除Stannis甚至再换Renly。",
118:"Eddard抓住Littlefinger说we。",
119:"Littlefinger说Eddard需要分担者，自己价格不高。",
120:"Eddard称price暴露建议是treason。",
121:"Littlefinger答只有失败才叫treason。",
122:"Eddard拿出Valyrian dagger，提醒Jon Arryn、Jory与Bran遭刺，right/wrong不容交易。",
123:"Littlefinger讽刺自己忘了在同Stark说话，确认选择Stannis便意味着war。",
124:"Eddard说这不是choice，Stannis是heir。",
125:"Littlefinger退让，问Eddard需要什么，显然不是自己的wisdom。",
126:"Eddard请求履行对Catelyn承诺：Cersei有百余armed men，自己guard不足，Jaime或正率host返城。",
127:"Littlefinger指出Eddard无army，并列Renly、Royce、Swann、Loras等court retinues。",
128:"Eddard说这些仍不足且忠诚不确定，必须获得两千gold cloaks City Watch。",
129:"Littlefinger问queen与Hand各立king时Watch护谁；转动dagger后说他们跟payer，并指Eddard把honor当沉重armor。",
130:"Eddard因被说中而怒到不敢开口。",
131:"Littlefinger代他说出请求，称为爱Catelyn会花六千gold买通Janos、officers、men，并把dagger柄朝前递回。",
}
SUMMARIES=[S[i] for i in range(1,132)]

KEY_NOTES={
1:"源页确实印作as he he had walked，按原文保留。crypt dream把promise、blue roses与blood tears叠加，预示旧责任再次逼近。",
7:"三名现实white cloaks触发Tower of Joy三Kingsguard记忆；相同数字和颜色让Robert危机与Lyanna创伤相连。",
9:"sullen red glare、suffocating heat与Eddard dreamlike movement把bedchamber写成醒着的噩梦。",
10:"mud、grass、cut cloth、blood smell用hunt残留替代解释性旁白，先让环境宣布death。",
14:"Robert承认wine与missed thrust，起初把灾难放在个人失误，不怀疑他人安排。",
16:"stand aside命令使Kingsguard守护职责与obey king职责冲突；他们无法同时完成。",
18:"groin to nipple的伤势与mortification决定医学结局；此处不是一般猎伤，而是大范围开放创口。",
19:"Robert在死亡前仍需证明自己杀回boar，warrior identity比恐惧更容易表达。",
23:"旧fierceness只用于赶走Cersei，显示濒死Robert仍以命令和性别羞辱维持控制。",
27:"Eddard腿痛与grief无法区分，身体和友情同时使他视野fogged。",
28:"Robert把boar解释为gods punishment是临终道德叙事；他撤回Daenerys命令，却把其他councillors一并称worthless。",
30:"will口授默认Joffrey合法，正与Eddard刚确认的truth冲突；法律文件从诞生即有继承歧义。",
31:"my heir替换my son Joffrey保持文字可指向Stannis，却违背speaker明确用词；Eddard以love实施自己厌恶的deceit。",
34:"Robert能承认bad king，却把自己近比Aerys；Eddard的安慰既真实也回避更具体责任。",
37:"blind signature与blood smear使will兼具authority和身体濒死痕迹；witness seal才完成公开真实性。",
39:"两个Promise me重叠，让Eddard对Robert承诺无法与Lyanna旧promise分开。",
40:"Robert把Daenerys与Joffrey并列托付：一边撤销杀child，一边请求改造自己以为的son。",
50:"Eddard用your children的语义弹性指向Robert bastards，既不直接撒谎也不回答Robert真正所指。",
52:"p.463–464原为同一Pycelle话段，已合并。two-day delay与mortified wound说明治疗窗口早已错过。",
55:"Renly的not wise but strong是最简Robert epitaph，也揭示strength曾掩盖governance缺陷。",
59:"protect king against himself解除Barristan个人罪责，却也暴露绝对obedience结构无法阻止自毁command。",
63:"Varys不直接指控poison，只问wine来源，让Barristan自己逐步说出squire供应链。",
68:"dutiful boy是反讽；持续refresh可把Robert常见饮酒放大成致命风险，而无需在wine中加入未知物。",
71:"Varys用完整kinship chain标出Lancel与Cersei/Tywin关系；innocent child措辞故意与其可疑角色冲突。",
73:"birds have flown同时是暗杀命令已发与Varys informant motif；取消命令的latency成为Daenerys生命风险。",
77:"Renly先问regency再报百剑，说明他已在按Robert death后的power map行动。",
79:"the man who holds king holds kingdom是hostage/regency现实主义；children被称take in hand掩饰强制拘押。",
80:"Eddard拒绝的不是所有force，而是Robert未死时流血、夜夺children；他的程序时间表给对手同样时间。",
81:"Renly把delay量化为Cersei preparation time，指出moral restraint在对抗性博弈中并非中性。",
86:"Eddard事后怀疑显示他并非不知风险，而是在两种可能伤害中选择并承担不确定。",
89:"把escort从十增二十同时削弱Eddard本地guard；保护daughters与守住capital存在资源竞争。",
93:"只交Stannis本人体现信息安全，也让letter delivery依赖其在岛、愿接见和ship可安全靠岸。",
95:"Eddard预见世人会说betrayed/disinherited，说明legal truth与public narrative可能完全相反。",
96:"短will却决定realm，blood smear让胜败生死的small difference成为物质可见。",
97:"他在Robert尚活时写will be dead，必须为政治速度预先把friend写成过去。",
98:"letters writhe是grief与责任造成的视觉心理感受，不表示paper真的变化。",
100:"Eddard把Stannis succession想成短regency与homecoming，可能低估war、new king politics和capital resistance。",
104:"Littlefinger先知道secret appointment，显示information network已穿透sealed deathbed room。",
106:"Varys hint只提供半信息，Eddard眼神补全；Littlefinger通过elicitation而非magic确认。",
109:"Eddard向最不信任又最需要的人交核心secret，说明military dependence迫使information risk扩大。",
110:"not shocked暗示Littlefinger至少已有怀疑；不等于证明他早知全部或参与Jon death。",
111:"在排除Robert legal children后，继承顺位转向elder brother Stannis；这是Eddard的法律结论。",
116:"Littlefinger论证不是否认Stannis合法，而是比较outcome：council purge、revenge chains、multi-house war。",
117:"他把四年regency视作捕获state的窗口，婚姻、secret与succession全成为可随时重排的工具。",
121:"Only if we lose把treason定义为victor’s label，彻底拒绝Eddard行为本身有正误的尺度。",
122:"dagger as sharp as right/wrong将道德二分物质化；但dagger ownership真相仍未完全解决。",
123:"a Stark既赞原则也讽僵硬；Littlefinger准确预测Stannis路线意味着war，却不证明替代路线正当。",
128:"City Watch是唯一可在castle/city尺度压过Cersei household的现成force，关键不在名义 oath而在command loyalty。",
129:"spinning dagger先wobble后指向Littlefinger，偶然被他包装成answer；honor-as-armor指出原则提高行动成本，但也忽略原则的保护功能。",
131:"六千gold明确把state force忠诚定价；hilt-first归还dagger表面安全礼貌，却让危险证物掌握在broker手中过。",
}

STAGES=[
(1,28,"crypt dream后Eddard被召入Maegor’s Holdfast，发现Robert被boar重创；Robert承认自身过失并临终撤回Daenerys暗杀。"),
(29,52,"Robert口授任Eddard Regent/Protector的will；Eddard改Joffrey为heir，作多重promise并以Robert真实bastards回应children托付。"),
(53,73,"Pycelle确认伤口必死；Barristan供出Lancel持续递wine，Varys暗示人为因素；Eddard命撤回Daenerys暗杀但可能已迟。"),
(74,100,"Renly提百剑夜夺royal children遭拒；Eddard加强daughters escort、写信Stannis并准备按合法继承移交throne。"),
(101,131,"Littlefinger主张以Joffrey regency换和平与权力，Eddard坚持Stannis；兵力不足迫他请求Littlefinger用gold买City Watch。"),
]

BACKGROUNDS={
1:"**crypt dream：** Winterfell crypts埋Stark ancestors；Lyanna的promise内容仍未说明，pale blue roses反复与她相连。",
7:"**Maegor’s Holdfast：** Red Keep内厚墙、dry moat与iron spikes保护的castle-within-castle，royal apartments所在。",
18:"**医疗事实：** 大范围boar wound经两日运送已感染坏死；Pycelle判断无法治愈，只能palliative pain relief。",
28:"**Daenerys order：** Robert此前批准雇毒杀pregnant fourteen-year-old Daenerys；临终明确要求撤销。",
30:"**regency：** monarch未成年时Regent/Protector代行rule；Robert以为Joffrey合法，Eddard知道其并非Robert son。",
31:"**文本改写：** Robert口述my son Joffrey，Eddard写my heir；这一差异使will可支持不同succession解释。",
50:"**Robert bastards：** Barra、Mya、Gendry等是Eddard已确认的Robert biological children，但不属婚生继承人。",
52:"**mortified：** 旧医学用语，指tissue死亡、腐败感染；并非情绪上的羞愧。",
63:"**wine suspicion：** Robert自愿大量饮酒且命guards退下；Lancel反复供wine可能受指使，但本章尚无直接confession。",
71:"**Lancel kinship：** Kevan son、Tywin nephew、Cersei cousin；亲缘造成潜在利益冲突，不自动证明有罪。",
73:"**暗杀时差：** Varys已把order送往远方，撤销需比原命令更快到达相同agents。",
79:"**Renly plan：** 先控制三名royal children，以Joffrey ward身份确保regency；法律审议将在既成武力之后。",
93:"**Stannis：** Robert elder surviving brother、Dragonstone lord；若royal children非Robert blood，按Eddard判断他是legal heir。",
97:"**secret letter：** Eddard通知Stannis paternity与succession危机，要求其率power迅速到capital。",
109:"**incest finding：** Cersei已向Eddard确认Joffrey、Myrcella、Tommen均由Jaime所生。",
116:"**Stannis coalition risk：** Tyrell/Redwyne曾围Storm’s End、Greyjoy曾rebellion；Littlefinger认为Stannis不宽恕会使多家恐惧。",
117:"**Littlefinger alternative：** 保留Joffrey表面合法、Eddard摄政，以多重婚姻绑定Stark–Lannister，并保留未来废立选项。",
128:"**City Watch：** King’s Landing约两千gold cloaks，名义守castle、city、king’s peace，实际command取决于officers与pay。",
131:"**Janos Slynt：** City Watch commander；Littlefinger估价六千gold分给commander、officers、men购买支持。",
}

EXTRA_VOCAB=[
("crypt","/krɪpt/","n.","地下墓室","Winterfell"),("garland","/ˈɡɑːrlənd/","n.","花环","blue roses"),("taper","/ˈteɪpər/","n.","细蜡烛","Cayn"),("intoned","/ɪnˈtoʊnd/","v.","以庄重单调语气说","steward"),("rampart","/ˈræmpɑːrt/","n.","城墙防御工事","gold cloak"),("nestle","/ˈnesəl/","v.","安置于；依偎","holdfast"),("canopied","/ˈkænəpid/","adj.","有华盖的","bed"),("tousled","/ˈtaʊzəld/","adj.","头发蓬乱的","Cersei"),("husk","/hʌsk/","v.","沙哑低声说","Robert"),("tusk","/tʌsk/","n.","獠牙","boar"),("carcass","/ˈkɑːrkəs/","n.","动物尸体","boar"),("headstrong","/ˈhedstrɔːŋ/","adj.","刚愎冲动的","Robert"),("regent","/ˈriːdʒənt/","n.","摄政者","minor king"),("stead","/sted/","n.","代替位置","in my stead"),("scrawl","/skrɔːl/","v.","潦草书写","signature"),("draught","/dræft/","n.","一剂饮液","poppy"),("mortify","/ˈmɔːrtɪfaɪ/","v.","组织坏死（旧医学）","wound"),("entrails","/ˈentreɪlz/","n.","内脏","boar wound"),("flinch","/flɪntʃ/","v.","畏缩","boar charge"),("flush","/flʌʃ/","v.","把猎物赶出藏处","boar"),("lair","/ler/","n.","兽穴","boar"),("stalwart","/ˈstɔːlwərt/","adj.","可靠强壮的","Varys irony"),("vulnerable","/ˈvʌlnərəbəl/","adj.","易受伤害的","child"),("span","/spæn/","n.","桥跨；桥面","bridge"),("taut","/tɔːt/","adj.","绷紧的","bowstring"),("convene","/kənˈviːn/","v.","召集会议","council"),("winesink","/ˈwaɪnsɪŋk/","n.","低档酒馆","search"),("repute","/rɪˈpjuːt/","n.","名声","sinister"),("hoist","/hɔɪst/","v.","升起","banner"),("imperative","/ɪmˈperətɪv/","adj.","极其必要的","Stannis sails"),("blot","/blɑːt/","v.","吸干墨迹","letter"),("puffed sleeve","/pʌft sliːv/","n.","泡泡袖","Littlefinger"),("wager","/ˈweɪdʒər/","v.","打赌","learning"),("incestuous","/ɪnˈsestʃuəs/","adj.","近亲性关系的","union"),("ascent","/əˈsent/","n.","登位；上升","Stannis"),("sit idly","/sɪt ˈaɪdli/","v.","坐视不理","Tywin"),("negligently","/ˈneɡlɪdʒəntli/","adv.","漫不经心地","honor shred"),("dispose of","/dɪˈspoʊz əv/","v.","除掉；处理","Stannis"),("shred","/ʃred/","n.","一丝；碎片","honor"),("retinue","/ˈretɪnuː/","n.","随从队伍","court lord"),("allegiance","/əˈliːdʒəns/","n.","效忠","swords"),("wobble","/ˈwɑːbəl/","v.","摇摆不稳","spinning dagger"),("elicitation","/ɪˌlɪsɪˈteɪʃən/","n.","诱导获取信息","interpretive term"),
]
VOCAB=BASE_VOCAB+EXTRA_VOCAB

def extract_blocks():
    blocks=extract_range(459,471,"EDDARD","CH47")
    blocks[51]["text"]=str(blocks[51]["text"])+" "+str(blocks[52]["text"])
    blocks[51]["end_page"]=blocks[52]["end_page"]
    del blocks[52]
    for order,block in enumerate(blocks,1):
        block["order"]=order
        block["id"]=f"CH47-P{int(block['page']):03d}-{order:03d}"
    return blocks

def main():
    blocks=extract_blocks()
    write_chapter(
        out=OUT,chapter=47,pov="EDDARD",page_start=459,page_end=471,
        blocks=blocks,summaries=SUMMARIES,key_notes=KEY_NOTES,stages=STAGES,
        backgrounds=BACKGROUNDS,
        default_background="本段没有新增必须补充的世界观事实；重点在Robert临终、will歧义、succession合法性、children protection与capital force。",
        vocab=VOCAB,
        guide="Lyanna的promise梦把Eddard从crypts惊醒，现实中Robert已被boar开膛。临终king撤销Daenerys暗杀，任Eddard为Regent/Protector，并托付‘son’与children；Eddard既不忍当面揭穿，又把will中的my son Joffrey改成my heir，为Stannis继承留下文字空间。随后Varys从wine供应链暗示Lancel可能扩大Robert醉态，Renly则提议趁夜以百剑控制royal children。Eddard拒绝先手强夺，却立即加强daughters escort、密信Stannis。Littlefinger提出另一套现实主义方案：保留Joffrey、利用四年regency和婚姻维持peace，日后再废立。Eddard坚持Stannis legal right，但兵力不足迫他请求用gold买City Watch；honor没有消失，却已必须通过自己厌恶的手段寻找执行力。",
        people=[
            ("Eddard Stark","本章视角；记录Robert will、筹划Stannis succession并寻求City Watch支持"),
            ("Robert Baratheon","被boar致命重伤的king，临终悔杀Daenerys、任Eddard摄政并服poppy睡去"),
            ("Renly Baratheon","Robert younger brother，提议先夺Cersei children控制capital"),
            ("Stannis Baratheon","Robert elder surviving brother；Eddard认定的legal heir与密信收件人"),
            ("Cersei Lannister","queen；Eddard仍希望她带children逃离，Renly认为她会先准备夺权"),
            ("Petyr Baelish","提出Joffrey regency替代方案，并承诺用gold确保City Watch支持Eddard"),
            ("Varys","通过wine问题暗示Lancel，也警告Daenerys暗杀撤回可能太迟"),
            ("Barristan Selmy","Kingsguard，因服从Robert退开命令而自责"),
            ("Lancel Lannister","Robert squire与Cersei cousin，负责不断递wine"),
            ("Tomard","临时guard commander，获命护送girls并亲交Stannis密信"),
        ],
        terms=[
            ("Lord Regent / Protector","Robert死后在minor heir成年前代行治理与保卫realm的职位"),
            ("my son Joffrey / my heir","Robert口述与Eddard实际书写的关键will差异"),
            ("Wind Witch","当晚潮汐启航、带Sansa与Arya离城的Braavosi ship"),
            ("City Watch / gold cloaks","King’s Landing约两千人的治安与守城force"),
            ("Janos Slynt","City Watch commander，Littlefinger准备以gold争取其支持"),
        ],
        synthesis="Chapter 47连续把Eddard置于没有纯净选项的decision point。说出paternity会加重朋友临终痛苦，不说又让will建立在错误上；他用my heir制造歧义。接受Renly可抢占兵力，却需在Robert未死时惊吓children；拒绝则给Cersei时间。拥立Stannis合法，却很可能引发Littlefinger预见的war；保留Joffrey或许暂缓战争，却将truth、Bran、Jory和justice变成可交易筹码。最后，Eddard坚持合法继承，却用bribery获取执行力量。文本没有把honor写成毫无价值，也没有让它自动带来安全：honor决定他不做什么，现实政治则逼他回答由谁、用多少gold、在什么时候做剩下必须做的事。",
        contrasts=[
            "**Lyanna promise／Robert promise：** 旧日与临终承诺叠加，Eddard无法把public duty与private grief分开。",
            "**my son Joffrey／my heir：** 一个被口授的具体继承人，被改写成可重新解释的法律类别。",
            "**king against himself／Kingsguard obedience：** 绝对服从使最忠诚guards无法阻止Robert自毁。",
            "**Renly百剑／Eddard council：** 先造既成事实与先走程序分别承担不同children与时间风险。",
            "**Stannis right／Joffrey peace：** 合法性与短期outcome预测形成Littlefinger辩论核心。",
            "**honor armor／gold cloaks payment：** 原则提供边界，却仍需金钱和force才能成为state action。",
        ],
        questions=[
            "Robert伤势纯属醉猎事故，还是Lancel受人指使持续供wine造成？",
            "Daenerys暗杀撤销命令能否赶在原命令之前到达？",
            "Cersei会逃离还是利用Eddard拒绝Renly的时间准备反击？",
            "Tomard能否把密信只交给Stannis本人并及时带girls离城？",
            "Littlefinger买下的City Watch究竟忠于Eddard、payer还是更复杂利益？",
        ],
        extraction_notes="PDF pp.459–471校勘后共131段。自动提取曾把p.463末尾It took them two days to get him back.与p.464开头By the time I saw him…误切，已合并。校勘后共8处跨页续段：pp.459–460、460–461、461–462、463–464、465–466、467–468、468–469与470–471。页面图像确认p.459源页印作as he he had walked，按原文保留；段落、will措辞与说话人均已复核。",
    )
    print(f"Wrote Chapter 47 with {len(blocks)} paragraphs")

if __name__=="__main__":
    main()
