#!/usr/bin/env python3
"""Build Chapter 45 (EDDARD) close-reading Markdown."""
from pathlib import Path
from agot_extract import extract_range
from agot_reader_common import write_chapter
from build_agot_chapter44_reader import VOCAB as BASE_VOCAB

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/"outputs"/"AGOT_逐章精读"

S={
1:"Pycelle把Eddard的pain称作gods gift，表示bone与flesh正在愈合。",
2:"Eddard说只有腿不再throb时才会感恩。",
3:"Pycelle留下stoppered flask，建议痛得难忍时用milk of the poppy。",
4:"Eddard拒绝，因为自己已经睡太多。",5:"Pycelle称sleep是great healer。",
6:"Eddard讽刺自己原以为healer是Pycelle。",
7:"Pycelle勉强微笑后低声透露Tywin给Cersei来信，认为Eddard最好知道。",
8:"Eddard以dark wings, dark words回应，问内容。",
9:"Pycelle说Tywin对派人追Gregor极为愤怒，并提醒自己早已在council警告。",
10:"Eddard让Tywin尽管生气，强调Beric持king banner，若阻碍justice便要面对好战的Robert。",
11:"Pycelle匆忙离开；Eddard判断他会向Cersei汇报，自己对Robert支持其实远没有表演得自信。",
12:"Eddard改喝较轻微影响思考的honeyed wine，反复想Jon Arryn若活着会如何行动，或是否已行动而死。",
13:"他意识Sansa无意说出Joffrey不像Robert，使全部线索清晰；这truth杀了Jon，也将以背叛毒害Robert。",
14:"Littlefinger盛装来访，拿Tanda daughter体形开恶毒玩笑后问腿伤。",
15:"Eddard说伤处发炎疼痛且itch难忍。",
16:"Littlefinger玩笑别再让horse压腿，随后报告west ominous：freeriders、sellswords正在Casterly Rock聚集。",
17:"Eddard急问Robert还要hunt多久。",
18:"Littlefinger说wolves先吃了white hart，Robert改追monstrous boar；Joffrey等部分队伍已返城。",
19:"Eddard最关心Hound是否回来，因为Jaime离开后他是城内Lannister一方最危险人物。",
20:"Littlefinger说Hound随Joffrey直奔queen，并想偷听他得知Beric去杀Gregor时的反应。",
21:"Eddard指出Hound本就厌恶brother。",
22:"Littlefinger说Gregor只可由Sandor恨，不可由别人杀；Gregor死后land、income将归Sandor，却别期待感谢。",
23:"Littlefinger临走看见Malleon genealogical tome，念出长title并嘲为sleeping potion。",
24:"Eddard短暂想全盘告诉他，却因其过度聪明和japes不信任，只试探说Jon Arryn病前在读此书。",
25:"Littlefinger用死亡终于解脱的quip回避，鞠躬离开。",
26:"Eddard咒骂city无人可信：Littlefinger会自保，Varys知而不做，Pycelle愈像Cersei的人，Barristan又僵守duty。",
27:"时间紧迫；Robert将返、honor要求报告，而Sansa、Arya三日后乘Wind Witch离开，Eddard不能再以安全为拖延理由。",
28:"但他梦见Tywin曾把Rhaegar两名child bodies裹Lannister red cloaks放在Iron Throne下。",
29:"Eddard不能让children massacre重演，也不能让realm再陷mad king与blood vengeance。",
30:"他回顾Robert曾宽恕Barristan、Pycelle、Varys、Balon等valiant former enemies，试图寻找mercy可能。",
31:"但秘密背叛像poison与刺入soul的knife，Robert绝不会像宽恕公开敌人般宽恕，必杀children。",
32:"Eddard仍不能沉默，他对Robert、realm、Jon Arryn与Bran均有duty；Bran遇害动机也与truth有关。",
33:"下午Eddard召Fat Tom；Jory死、Alyn离后由其领household guard，使Eddard因兵少与能力有限而不安。",
34:"Eddard说需要Tomard帮助，命带自己去godswood。",
35:"Tomard怀疑伤腿外出是否明智。",36:"Eddard承认或许不明智但necessary。",
37:"Tomard与Varly架Eddard下楼过bailey；Eddard命Tower guard加倍，出入需许可。",
38:"Tomard说Alyn等走后人手已经紧张。",39:"Eddard命延长watch，称只需短时间。",
40:"Tomard服从但想问原因。",41:"Eddard简短阻止其知道更多。",
42:"南方godswood空无一人；Eddard在faceless oak旁坐下，交Tomard一封Stark-sealed paper立即送出。",
43:"Tomard看到收件人后焦虑舔唇。",44:"Eddard命他照办。",
45:"Eddard在隔绝castle噪声的godswood等待，听birds、crickets、leaves；虽heart tree为oak，仍感到gods与疼痛减轻。",
46:"Cersei sunset时按要求独自到来，穿简朴hunting greens，脸上仍有Robert打出的yellow bruise。",
47:"Cersei站在Eddard上方问为何选这里。",48:"Eddard说为了让gods看见。",
49:"Cersei坐草地仍优雅美丽；Eddard直说自己知道Jon Arryn因何而死。",
50:"Cersei警惕观察，问这是riddle还是要像Catelyn抓Tyrion般抓她。",
51:"Eddard判断若真怕被捕她不会来，轻触bruise问Robert是否曾多次施暴。",
52:"Cersei躲开，说此前一两次但从未打脸，并宣称Jaime会为此杀Robert，远胜Eddard friend。",
53:"Eddard直接问Jaime是brother还是lover。",
54:"本段中Cersei确认Jaime同时是brother与lover，称关系源自childhood，并以Targaryen婚配与双生一体为辩护；露骨句不复录。",
55:"Eddard提起son Bran。",
56:"Cersei不回避，说Bran看见了，并反问Eddard是否爱children。",
57:"Eddard像Robert此前问他时一样回答全心爱。",
58:"Cersei说自己同样爱children。",
59:"Eddard设想若陌生child与自己五个children冲突，甚至Jon与Catelyn亲生孩子冲突，自己也不知会如何选。",
60:"Eddard断言Cersei三个children全由Jaime所生。",
61:"Cersei回答thank the gods，确认而非否认。",
62:"Eddard串起seed is strong：Robert bastards与历代stag–lion children均黑发，记录中gold总向coal屈服。",
63:"Eddard问十二年婚姻为何没有Robert children。",
64:"Cersei说曾怀Robert child但秘密终止，此后通过避免性交与利用其醉酒维持表象。",
65:"Eddard震惊众人长久未见children脸上的truth，又追问Robert当年像king，究竟如何令她憎恨。",
66:"Cersei说婚礼夜第一次同床，醉酒Robert在亲密时叫她Lyanna。",
67:"Eddard想到pale blue roses，悲伤说不知更该怜悯夫妻哪一个。",
68:"Cersei拒绝pity，叫他留给自己。",
69:"Eddard说她知道自己必须做什么。",
70:"Cersei以will高于must诱惑Eddard结盟，触摸其腿、脸与头发，承诺强Hand可避免war且令他不后悔。",
71:"Eddard问她是否也向Jon Arryn作过同样offer。",
72:"Cersei扇他一耳光。",
73:"Eddard借Cersei曾说的badge of honor干讽回应。",
74:"Cersei攻击Eddard私生子与Ashara等传闻，质问他凭何以noble lord自居、与Robert三人何异。",
75:"Eddard首先区分自己不杀children，宣布Robert返城即告知truth，给Cersei与三名children时间逃到远方Free Cities。",
76:"Cersei称exile是bitter cup。",
77:"Eddard说仍比Tywin给Rhaegar children的结局甜，建议Tywin、Jaime等同逃，并警告Robert wrath会追到极远。",
78:"Cersei起身反问自己的wrath，称Eddard在King’s Landing陷落时本可从Jaime手中取Iron Throne，却错失掌权时刻。",
79:"Eddard承认犯过许多错，但不夺throne不是其中之一。",
80:"Cersei给出game of thrones规则：只能win或die，没有middle ground。",
81:"她戴hood遮住肿脸离去，把Eddard独留blue-black夜色、oak与初升stars下。",
}
SUMMARIES=[S[i] for i in range(1,82)]

KEY_NOTES={
1:"Pain is a gift把病人无法拒绝的痛苦重新命名为benefit；Pycelle说得医学上有部分道理，却忽略Eddard实际承受。",
6:"I had hoped that was you把great healer从sleep转回maester，讽刺Pycelle以格言替代有效止痛选择。",
7:"Pycelle先提供medicine再提供political message，两种‘照护’都可能服务Cersei influence。",
10:"Eddard以Robert好战威慑Tywin，却因下一段承认并不自信，显示这是strategic bluff而非稳定依靠。",
11:"他同时读出message与meta-message：Pycelle不是单纯告知，而在传递Cersei/Tywin的threat并收集回应。",
12:"honeyed wine也cloud mind但较轻，表明Eddard在pain management与cognitive clarity间做风险权衡。",
13:"Sansa愤怒童言绕过成人假设；sword that killed Jon是metaphor，真正致命者仍可能是为保守truth采取行动的人。",
14:"Littlefinger拿Lollys身体作笑料，展示其wit经常依赖羞辱更弱势者；这也提醒读者不要把聪明自动等同可靠。",
16:"freeriders/sellswords flocking是war mobilization indicator，但Varys whispers和Littlefinger转述均非正式军令证据。",
18:"white hart magic quest被wolves先行终结，Robert立刻用boar替换目标；hunt欲望永远能找到新对象。",
22:"his to loathe指出家庭仇恨也被Sandor体验为private possession；外人杀Gregor可能剥夺其想象中的清算权。",
23:"书名本身就是证据目录：lineages、lords、ladies、children把政治秘密藏在tedious genealogy中。源页末引号方向异常按原文保留。",
24:"Eddard用Jon读过此书测试Littlefinger反应，却只得到joke；无反应既不证明无知，也不证明掩饰。",
26:"对四人的评估暴露Eddard困境：他需要帮助，却用忠诚、行动、rigidity标准逐个找到不能完全信任的理由。",
27:"Wind Witch和three days hence给道德选择设倒计时；daughters安全不再是无限延期理由。",
28:"red cloaks掩blood的图像把Tywin cleverness写成美化证据，而非减少罪行。",
29:"save the children来自旧日失败记忆；Eddard把当前三个child与Rhaegar children放进同一保护伦理。",
30:"Robert能尊重公开勇敌，因为战争身份清楚；这并不能直接推出他会宽恕家庭与继承背叛。",
31:"poison in dark回扣Jon疑似poison与secret parentage；Robert把private betrayal体验为比battle更不可原谅。",
32:"Eddard把Bran attempted murder纳入motive chain：发现秘密可解释灭口企图，但尚未直接证明谁执行push或dagger attack。",
33:"先前把best swords派给Beric如今反噬本地安全；正确执行一项justice也可能削弱另一项保护任务。",
36:"Perhaps not. But necessary压缩Eddard moral style：承认手段危险，不因此放弃认为必须的行动。",
37:"double guard与controlled access说明他知道对质后风险上升，却仍因人手不足只能lengthen watches。",
41:"need-to-know保护Tomard免受秘密牵连，也剥夺guard commander理解威胁、主动调整的能力。",
45:"无weirwood face的oak仍让Eddard感到gods，说明faith不完全依赖正统物质标志；环境平静也降低pain salience。",
46:"yellow bruise把上一场bedchamber violence带入本次秘密会面；simple clothes不消除queen power。",
48:"让gods see表明Eddard把对质当truth oath场，而非纯政治交易。",
49:"他重新看见beauty却仍提出指控，避免把moral judgment写成对外貌厌恶。",
51:"Eddard未经明确同意触碰Cersei伤处附近，Cersei随即shy away；关怀意图不取消身体边界。",
52:"Cersei用Jaime willingness to kill证明价值，把保护与致命暴力紧密绑定。",
53:"brother or lover以二选一逼出秘密，Cersei用both拒绝社会分类边界。",
54:"本段含露骨incest表达并追溯到childhood，不逐字复录。核心是Cersei把禁忌关系解释为Targaryen precedent与twin wholeness。",
56:"He saw us确认Bran发现incest，为坠塔提供motive；Cersei没有在此直接说谁推他。",
59:"Eddard不轻易以自己道德优越否认parental dilemma；这种同理使他随后给Cersei children逃生机会。",
60:"not a question表明genealogy已让Eddard形成结论，本次对话是confirmation与安排后果，不是开放调查。",
61:"Thank the gods不仅承认paternity，也公开表达她不愿Robert成为children father。",
62:"gold yielding before coal是书中多代observational pattern，在in-world推理中强；现代遗传上不能把发色当绝对法则，但Cersei confession补足事实。",
64:"本段涉及成人生育终止与婚内性安排；以reproductive control与长期婚姻欺骗分析，不道德化医疗选择本身。",
65:"Eddard怀念年轻Robert every inch a king，说明他仍用过去潜力衡量现在person，追问hate原因也寻找道德对称。",
66:"Robert说Lyanna的名字把Cersei在婚姻开端降为替代者；酒味与错名形成持久羞辱，但不为后续伤害无条件免责。",
67:"pale blue roses连接Lyanna记忆；pity both承认婚姻双方被一个亡者形象困住。",
70:"Cersei从法律truth转向body、power与war avoidance交易；真正offer是共同隐瞒以换political partnership。",
71:"问题暗含怀疑：若Jon也收到offer却死亡，Cersei是否与其死有关；文本在此仍未得到直接回答。",
72:"slap终止seduction frame并恢复敌对；身体动作比言辞更快回应Jon暗示。",
73:"badge of honor回用Cersei被Robert打后说过的话，机智却也把两次性质不同的掌掴并列。",
74:"Cersei用Jon Snow攻击Eddard hypocrisy，并引Ashara rumors；这些都是指控与传闻，本段不证明mother身份或事件真相。",
75:"Eddard先说不杀children，揭示他认为最关键差别不是sexual purity而是对无辜者的暴力底线。",
77:"他给出的不是legal acquittal而是forewarning；若Cersei不走，Eddard仍会告诉Robert并触发追杀。",
78:"Cersei把不夺throne定义为mistake，暴露其政治尺度：未取得power即浪费机会，合法与否居次。",
80:"win or die是Cersei worldview，不是中立宇宙定律；它会使任何middle-ground mercy看起来像致命软弱。",
81:"hood同时遮bruise与身份脆弱，Eddard留在faceless oak下；双方都离开对质却没有共同可执行协议。",
}

STAGES=[
(1,13,"Pycelle以Tywin来信试探Eddard，Eddard用Robert authority bluff回应；随后由Sansa童言完成Jon Arryn genealogy线索。"),
(14,27,"Littlefinger带来west mobilization与hunt消息，试探genealogy book后离开；Eddard意识daughters三日后启程，必须尽快行动。"),
(28,45,"Rhaegar children梦令Eddard决心避免新屠杀；他加强Tower守卫、秘密送信，并带伤到godswood等待Cersei。"),
(46,63,"两人在oak下对质：Cersei承认Jaime关系、Bran看见秘密、三名children paternity；Eddard陈述black-hair genealogy证据。"),
(64,81,"Cersei解释与Robert婚姻、试图诱Eddard结盟；遭拒后攻击其honor，Eddard给她带children逃亡窗口，双方以game of thrones分歧结束。"),
]

BACKGROUNDS={
1:"**伤势：** Jaime伏击中horse压断Eddard leg；骨头正愈合但持续疼痛，milk of the poppy会镇痛并使意识昏沉。",
9:"**Tywin reaction：** Eddard已褫夺Gregor并派Beric持king banner执行；Tywin通过给Cersei来信表达愤怒。",
13:"**Sansa clue：** 上章Sansa说Joffrey不像Robert，Arya指出他法律上应是stag而非lion；Eddard将此与genealogy book连接。",
16:"**west mobilization：** Casterly Rock招集freeriders、sellswords通常意味着扩军，但消息来自Varys whispers经Littlefinger转述。",
18:"**hunt状态：** white hart已被wolves吃，Robert转追boar；Joffrey、Hound等部分人已返King’s Landing。",
22:"**Clegane inheritance：** 若Gregor依法死亡且无其他继承障碍，其lands、income可能转给brother Sandor。",
23:"**Malleon tome：** 记录great houses婚配、children与外貌；Jon Arryn、Eddard均用它检查Baratheon–Lannister血统规律。",
27:"**Wind Witch：** 从Braavos来的ship，Poole安排三日后载Sansa、Arya秘密北返，预计harvest前到Winterfell。",
28:"**Rhaegar children：** Rebellion末期Tywin forces杀死年幼princess与prince，并以red Lannister cloaks包裹尸体献给Robert。",
30:"**Robert pardons：** Barristan等原敌在宣誓fealty后获保留honor或office，说明Robert对公开战场敌人可宽容。",
32:"**Bran link：** Bran fall后另有assassin持dagger灭口；Eddard现推断Bran可能先发现royal children秘密。",
42:"**godswood地点：** Red Keep godswood无weirwood，heart tree为faceless oak；隐蔽安静，适合不被court听见的对质。",
46:"**bruise：** Robert此前在Eddard bedchamber争吵中反手打倒Cersei；伤痕仍清晰可辨。",
54:"**安全说明：** 本段含露骨incest表达并将关系追溯至childhood；保留承认、辩护逻辑和定位，不逐字复录。",
56:"**证据边界：** Cersei承认Bran看见两人；这确立灭口motive，不等于她在此承认亲手推落或派dagger assassin。",
62:"**genealogy chain：** Robert多个bastards黑发；书中多次stag–lion marriage children也黑发；Joffrey、Myrcella、Tommen均gold hair；Cersei随后确认Jaime paternity。",
64:"**成人生育叙事：** Cersei描述曾终止Robert pregnancy并长期控制性接触；本段所有当事人为成年人。",
66:"**Lyanna shadow：** Robert仍执着Eddard sister Lyanna；婚礼夜错名使其旧爱直接进入Cersei婚姻。",
74:"**Ashara rumor：** Cersei列举Dornish peasant、whore、Ashara等Jon mother传闻；本章没有确认任何版本。",
75:"**escape window：** Eddard不先逮捕，而打算Robert返前让Cersei携children远逃，以避免children被处死。",
80:"**game of thrones：** Cersei用来概括高位权力斗争的生死零和观；Eddard仍试图创造exile middle ground。",
}

EXTRA_VOCAB=[
("knit","/nɪt/","v.","骨头愈合长合","bone"),("stoppered","/ˈstɑːpərd/","adj.","用塞子封口的","flask"),("onerous","/ˈɑːnərəs/","adj.","难以忍受或负担沉重的","pain"),("wanly","/ˈwɑːnli/","adv.","苍白勉强地","smile"),("wroth","/rɔːθ/","adj.","盛怒的（古风）","Tywin"),("confide","/kənˈfaɪd/","v.","低声透露；吐露","Pycelle"),("jangle","/ˈdʒæŋɡəl/","v.","发出刺耳金属声","chain"),("rattle","/ˈrætəl/","v.","使惊慌不安","teeth metaphor"),("queer","/kwɪr/","adj.","奇怪的（旧义）","child insight"),("fester","/ˈfestər/","v.","化脓恶化；积怨腐蚀","betrayal"),("fatted calf","/ˌfætɪd ˈkæf/","n.","肥育小牛；盛宴佳肴","Littlefinger joke"),("rupture","/ˈrʌptʃər/","v.","破裂；撑破","cruel joke"),("restive","/ˈrestɪv/","adj.","躁动不安、难控制的","realm"),("ominous","/ˈɑːmɪnəs/","adj.","不祥的","whispers"),("flock","/flɑːk/","v.","成群聚集","sellswords"),("roach","/roʊtʃ/","n.","蟑螂","eavesdropping fantasy"),("rushes","/ˈrʌʃɪz/","n.","铺地灯芯草","court floor"),("lope","/loʊp/","v.","砍掉；大步跑（此处lops）","head"),("summit","/ˈsʌmɪt/","n.","山顶；此处双关头","Mountain"),("tome","/toʊm/","n.","大部头书","genealogy"),("irk","/ɜːrk/","v.","使厌烦恼火","japes"),("quip","/kwɪp/","n.","俏皮讥讽话","Littlefinger"),("rankle","/ˈræŋkəl/","v.","持续令人愤恨","self-preservation"),("protestation","/ˌprɑːtəˈsteɪʃən/","n.","郑重声明","loyalty"),("perilously","/ˈperələsli/","adv.","危险地；极其","short time"),("fealty","/ˈfiːəlti/","n.","效忠誓言","pardoned enemies"),("valiant","/ˈvæliənt/","adj.","英勇的","enemy"),("affable","/ˈæfəbəl/","adj.","和蔼可亲的","Tomard"),("apprehensive","/ˌæprɪˈhensɪv/","adj.","忧虑不安的","Tomard"),("hobble","/ˈhɑːbəl/","v.","跛行","bailey"),("hard-pressed","/ˌhɑːrd ˈprest/","adj.","处境困难、人手吃紧的","guard"),("clamor","/ˈklæmər/","n.","喧嚣声","castle"),("wary","/ˈweri/","adj.","警惕的","Cersei"),("flit","/flɪt/","v.","轻快掠过","ghost smile"),("lusty","/ˈlʌsti/","adj.","健壮有活力的（旧义）","infant"),("brittle","/ˈbrɪtəl/","adj.","脆硬易碎的","pages"),("yield","/jiːld/","v.","屈服；让位","gold before coal"),("cleanse","/klenz/","v.","此处委婉指终止妊娠","pregnancy"),("scarcely","/ˈskersli/","adv.","几乎不","bear touch"),("badge of honor","/bædʒ əv ˈɑːnər/","n.","荣誉徽记；此处讽刺伤痕","slap"),("exile","/ˈeksaɪl/","n.","流亡","escape"),("back of beyond","/bæk əv bɪˈjɑːnd/","n.","极偏远之地","Robert wrath"),("middle ground","/ˈmɪdəl ɡraʊnd/","n.","折中余地","game rule"),
]
VOCAB=BASE_VOCAB+EXTRA_VOCAB

def extract_blocks():
    blocks=extract_range(441,448,"EDDARD","CH45")
    blocks[53]["text"]="[原文中Cersei确认Jaime同时是brother与lover，将关系追溯至childhood，并以Targaryen近亲婚配及双生一体为辩护；因含露骨性表达，此处不逐字复录。请参见源 PDF p.446 对应段落。]"
    return blocks

def main():
    blocks=extract_blocks()
    write_chapter(
        out=OUT,chapter=45,pov="EDDARD",page_start=441,page_end=448,
        blocks=blocks,summaries=SUMMARIES,key_notes=KEY_NOTES,stages=STAGES,
        backgrounds=BACKGROUNDS,
        default_background="本段没有新增必须补充的世界观事实；重点在genealogy证据、Cersei confession、Eddard duty与children safety的冲突。",
        vocab=VOCAB,
        guide="伤腿使Eddard必须在止痛与清醒之间取舍，Tywin来信、Casterly Rock募兵和Robert迟迟不归又压缩行动时间。Sansa无意说出Joffrey不像Robert后，Malleon genealogy终于有了意义：Robert bastards与历代stag–lion children皆黑发，royal children却全是gold hair。Eddard在Rhaegar children尸体的旧梦驱使下，没有立即逮捕Cersei，而在faceless oak旁要求她独自对质。Cersei确认Jaime既是brother也是lover、Bran看见秘密、三个children均由Jaime所生；她又解释与Robert婚姻并试图以身体、权力和避免war拉拢Eddard。Eddard拒绝，却给她在Robert返城前携children流亡的窗口。两人的根本差异最终由Cersei说破：Eddard相信仍有honor与mercy的中间地带，她相信game of thrones只能win或die。",
        people=[
            ("Eddard Stark","本章视角；完成royal paternity推理、对质Cersei并给children逃生机会"),
            ("Cersei Lannister","queen；确认Jaime关系与children paternity，解释婚姻并试图拉拢Eddard"),
            ("Jaime Lannister","Cersei twin、lover与三个royal children biological father"),
            ("Robert Baratheon","legal father与king，仍在hunt；Eddard判断其得知背叛后会杀children"),
            ("Jon Arryn","因追查同一genealogy truth而死的前Hand"),
            ("Pycelle","传递Tywin threat并被Eddard视为Cersei messenger"),
            ("Petyr Baelish","带来west与hunt消息，注意到genealogy book却以joke回应"),
            ("Tomard / Varly","在人手不足时协助Eddard移动并执行秘密guard、delivery命令"),
            ("Sansa Stark","以无意童言让Eddard看清Joffrey与Robert不相似的关键"),
        ],
        terms=[
            ("the seed is strong","Jon Arryn临终语；指Baratheon外貌特征在历代婚配children中稳定显现"),
            ("stag and lion","Baratheon与Lannister婚配及黑发、金发对照"),
            ("Wind Witch","三日后载Sansa、Arya秘密离城的Braavosi ship"),
            ("Free Cities","Narrow Sea东岸诸城邦，Eddard建议Cersei携children流亡之地"),
            ("game of thrones","Cersei对最高权力斗争的零和生死观"),
        ],
        synthesis="Chapter 45让证据链终于闭合，但也证明知道truth不等于知道怎样安全行动。Genealogy提供pattern，Cersei confession提供confirmation，Bran seeing them提供motive；然而Eddard仍面对Robert性格、children无辜、自己人手不足和Tywin mobilization。选择先警告Cersei体现他不愿复制Rhaegar children屠杀，也暴露其行动模型：他希望对手接受exile这个middle ground。Cersei则把同一善意看成未夺权、未控制敌人的致命错误。她的婚姻伤害、Robert暴力与Eddard同理都是真实的，但不能自动取消她对继承欺骗及Bran危险的责任。文本因此不让任何单一标签完成判断，而把私人创伤、parental love、state succession与child safety压进一次没有见证人的黄昏谈判。",
        contrasts=[
            "**milk of poppy／honeyed wine：** 强止痛牺牲清醒，轻酒保留更多思考却仍有代价。",
            "**tedious genealogy／致命truth：** 最枯燥的记录隐藏最危险的王位证据。",
            "**公开敌人／私人背叛：** Robert能宽恕战场勇敌，却未必宽恕家庭与继承欺骗。",
            "**Rhaegar children／Cersei children：** 旧日尸体迫Eddard为当下无辜者创造逃生窗口。",
            "**faceless oak／gods witness：** 缺少weirwood face不妨碍Eddard把场所当道德见证。",
            "**middle-ground exile／win-or-die game：** Eddard相信可兼顾truth与mercy，Cersei认为不彻底获胜即死亡。",
        ],
        questions=[
            "Cersei会接受警告携children流亡，还是利用Eddard给出的时间反击？",
            "Robert得知children paternity后会如何行动？",
            "Jon Arryn究竟由谁、以何种方式杀死？",
            "Bran被推落与后续dagger assassination分别由谁决定和执行？",
            "Eddard密封信寄给了谁，准备了什么后手？",
        ],
        extraction_notes="PDF pp.441–448校勘后共81段；共4处跨页续段：pp.441–442、443–444、445–446与447–448，无额外跨页合并。p.441章首源页缺开引号，p.443书名结尾源页引号方向异常，均按原文保留。第54段含露骨incest表达并追溯至childhood，保留核心承认、辩护逻辑和稳定定位，但以安全占位替代原段。",
    )
    print(f"Wrote Chapter 45 with {len(blocks)} paragraphs")

if __name__=="__main__":
    main()
